cdk/src/destinations/destination-runner.ts
cdk/src/logger.ts
destinations/faros-destination/resources/spec.json
destinations/faros-destination/src/index.ts
destinations/faros-destination/test/converters/github.test.ts

1. Dry run won create neither a revision nor write any records into Faros API
2. Minor rearrange in logger functions
3. Use stdin argument in destination

Proper Dry run in Faros destination + fixes

---

destinations/faros-destination/package.json
destinations/faros-destination/src/index.ts
destinations/faros-destination/test/converters/github.test.ts
faros-airbyte-cdk/package.json
lerna.json
package.json
scripts/publish-connector.sh
sources/example-source/package.json

1. Write stats by model in Faros destination
2. Airbyte container labels (required by Airbyte spec) https://docs.airbyte.io/connector-development#publishing-a-connector. Example - https://hub.docker.com/layers/airbyte/source-postgres/latest/images/sha256-ede6fe4d7e1a4b3f3c4d4f91089766be2caa9178830ef3e92a25f442f57ec691?context=explore

Write stats by model in Faros destination + Airbyte container labels

---

Dockerfile
README.md
destinations/faros-destination/package.json
destinations/faros-destination/src/converters/github/index.ts
destinations/faros-destination/src/index.ts
destinations/faros-destination/test/converters/github.test.ts
destinations/faros-destination/test/resources/github-catalog-raw.json
faros-airbyte-cdk/package.json
faros-airbyte-cdk/src/destinations/destination-runner.ts
faros-airbyte-cdk/src/protocol.ts
faros-airbyte-cdk/src/sources/source-runner.ts
faros-airbyte-cdk/src/utils.ts
lerna.json
package-lock.json
package.json
sources/example-source/package.json

Remove node user + Faros destination fixes
1. Remove `USER node` to avoid permission denied errors on EKS
```
❯ kubectl logs pods/destination-worker-.... main                       
sh: can't create /pipes/stderr: Permission denied
Using existing AIRBYTE_ENTRYPOINT: /home/node/airbyte/main
```
2. Avoid logging secrets when running source & destinations
3. Fix stream lookup for raw inputs

Remove node user + Faros destination fixes

---

destinations/faros-destination/package.json
destinations/faros-destination/src/index.ts
faros-airbyte-cdk/package.json
lerna.json
sources/example-source/package.json

Since Airbyte does not propagate `LOG_LEVEL` to the connector containers yet, we have to work with info level for now.

Switch logging to info in Faros destination

---

destinations/faros-destination/package.json
destinations/faros-destination/src/converters/github/commits.ts
destinations/faros-destination/src/converters/github/common.ts
destinations/faros-destination/src/converters/github/issues.ts
destinations/faros-destination/src/converters/github/pull_requests.ts
destinations/faros-destination/src/converters/github/releases.ts
destinations/faros-destination/src/converters/github/review_comments.ts
destinations/faros-destination/src/converters/github/reviews.ts
destinations/faros-destination/test/converters/github.test.ts
faros-airbyte-cdk/package.json
lerna.json
sources/example-source/package.json

Use user login instead of id in Github converters. Thanks @cjwooo for adding support for it in Airbyte sources!
> Fix [#1]() 
Requires Airbyte Github source >= 0.2.x

FAI-383 - Use user login instead of id in Github converters

---

faros-airbyte-cdk/src/sources/source-base.ts
package-lock.json
sources/phabricator-source/package.json
sources/phabricator-source/resources/schemas/commits.json
sources/phabricator-source/src/index.ts
sources/phabricator-source/src/phabricator.ts
sources/phabricator-source/src/streams/commits.ts
sources/phabricator-source/src/streams/index.ts
sources/phabricator-source/src/streams/repositories.ts

Cache repostories in Phabricator streams

Cache repostories in Phabricator streams

---

destinations/faros-destination/package.json
faros-airbyte-cdk/package.json
lerna.json
package-lock.json
package.json
sources/example-source/package.json
sources/jenkins-source/package.json
sources/jenkins-source/src/index.ts
sources/jenkins-source/src/jenkins.ts
sources/jenkins-source/src/streams/builds.ts
sources/jenkins-source/src/streams/jobs.ts
sources/jenkins-source/test/index.test.ts
sources/phabricator-source/package.json
sources/phabricator-source/resources/schemas/repositories.json
sources/phabricator-source/resources/schemas/revisions.json
sources/phabricator-source/resources/schemas/users.json
sources/phabricator-source/src/index.ts
sources/phabricator-source/src/phabricator.ts
sources/phabricator-source/src/streams/commits.ts
sources/phabricator-source/src/streams/index.ts
sources/phabricator-source/src/streams/repositories.ts
sources/phabricator-source/src/streams/revisions.ts
sources/phabricator-source/src/streams/users.ts
sources/phabricator-source/test_files/full_configured_catalog.json
sources/phabricator-source/test_files/incremental_configured_catalog.json

1. Added revisions & users streams to Phabricator source + bump version
2. Jenkins source fixes
FAI-441

FAI-441 - Added revisions & users streams to Phabricator source + bump version

---

destinations/faros-destination/package.json
destinations/faros-destination/src/index.ts
faros-airbyte-cdk/package.json
faros-airbyte-cdk/src/destinations/destination-runner.ts
faros-airbyte-cdk/src/sources/source-base.ts
lerna.json
package-lock.json
sources/example-source/package.json
sources/jenkins-source/package.json
sources/phabricator-source/package.json
sources/phabricator-source/resources/schemas/commits.json
sources/phabricator-source/resources/schemas/projects.json
sources/phabricator-source/resources/schemas/revisions.json
sources/phabricator-source/resources/spec.json
sources/phabricator-source/src/index.ts
sources/phabricator-source/src/phabricator.ts
sources/phabricator-source/src/streams/index.ts
sources/phabricator-source/src/streams/projects.ts
sources/phabricator-source/test_files/full_configured_catalog.json
sources/phabricator-source/test_files/incremental_configured_catalog.json
sources/phabricator-source/test_files/spec.json

Added projects stream to Phabricator + cleanup
FA-441

FA-441 - Added projects stream to Phabricator + cleanup

---

destinations/faros-destination/package.json
destinations/faros-destination/src/common/write-stats.ts
destinations/faros-destination/src/index.ts
destinations/faros-destination/test/converters/agileaccelerator.test.ts
destinations/faros-destination/test/converters/asana.test.ts
destinations/faros-destination/test/converters/bitbucket.test.ts
destinations/faros-destination/test/converters/github.test.ts
destinations/faros-destination/test/converters/gitlab.test.ts
destinations/faros-destination/test/converters/googlecalendar.test.ts
destinations/faros-destination/test/converters/harness.test.ts
destinations/faros-destination/test/converters/jenkins.test.ts
destinations/faros-destination/test/converters/jira.test.ts
destinations/faros-destination/test/converters/okta.test.ts
destinations/faros-destination/test/converters/pagerduty.test.ts
destinations/faros-destination/test/converters/phabricator.test.ts
destinations/faros-destination/test/converters/squadcast.test.ts
destinations/faros-destination/test/converters/statuspage.test.ts
destinations/faros-destination/test/converters/victorops.test.ts
destinations/faros-destination/test/index.test.ts

Skip failing on undefined converter + add skipped records counter in Faros Destination. This change should make Faros Destination more robust when processing records from a stream with an undefined converter, by simply skipping the records.

Skip failing on undefined converter + add skipped records counter in Faros Destination

---

destinations/faros-destination/package.json
destinations/faros-destination/src/converters/datadog/incidents.ts

The API that I was testing against did return the `status` and `state` in the previous locations, but I suspect that the DataDog v2 api client does not expose them there. I tested and they are exposed here.
```json
{
"record": {
"stream": "incidents",
"emitted_at": 1646193807077,
"data": {
"attributes": {
...
"fields": {
"severity": {
"type": "dropdown",
"value": "SEV-5"
},
...
"state": {
"type": "dropdown",
"value": "resolved"
}
...
}
...
},
...
}
},
"type": "RECORD"
}
```

DataDog source fix

---

package-lock.json
sources/backlog-source/package.json
sources/backlog-source/src/backlog.ts
sources/backlog-source/src/streams/issues.ts
sources/bitbucket-source/src/bitbucket/bitbucket.ts
sources/docker-source/src/docker.ts
sources/docker-source/src/streams/tags.ts
sources/docker-source/test/index.test.ts
sources/jenkins-source/package.json
sources/jenkins-source/src/jenkins.ts
sources/jenkins-source/src/streams/jobs.ts
sources/shortcut-source/package.json
sources/shortcut-source/src/shortcut.ts
sources/shortcut-source/src/streams/iterations.ts
sources/squadcast-source/src/squadcast.ts
sources/squadcast-source/src/streams/incidents.ts
sources/statuspage-source/package.json
sources/statuspage-source/src/statuspage.ts
sources/statuspage-source/src/streams/incidents.ts

The typescript-memoize library does not work for generators. Only the first call was yielding results. Therefore, I converted all the functions that utilize the `@Memoize` annotation to return normal lists.
> Fix [#1]() 

Fix use of memoize

---

destinations/airbyte-faros-destination/package.json
faros-airbyte-cdk/package.json
lerna.json
scripts/publish-connector.sh
sources/agileaccelerator-source/package.json
sources/backlog-source/package.json
sources/bitbucket-source/package.json
sources/customer-io-source/package.json
sources/datadog-source/package.json
sources/docker-source/package.json
sources/example-source/package.json
sources/googlecalendar-source/package.json
sources/harness-source/package.json
sources/jenkins-source/package.json
sources/okta-source/package.json
sources/pagerduty-source/package.json
sources/phabricator-source/package.json
sources/shortcut-source/package.json
sources/squadcast-source/package.json
sources/statuspage-source/package.json
sources/victorops-source/package.json

Instead of `docker.io/farosai/airbyte-airbyte-faros-destination:x.y.z` it should be `docker.io/farosai/airbyte-faros-destination:x.y.z`

Fix Docker image path for Faros Destination

---

destinations/airbyte-faros-destination/README.md
destinations/airbyte-faros-destination/src/converters/converter-registry.ts
destinations/airbyte-faros-destination/src/converters/converter.ts
destinations/airbyte-faros-destination/test/converter-registry.test.ts

Added ConverterTyped and DestinationRecordTyped to allow creating typed converters.
Below is an example of a customer converter typed with `FooBar`:
```typescript
interface FooBar { foo: string; bar: number; }
class CustomConverter extends ConverterTyped<FooBar> {
source = 'Custom';
destinationModels = ['test_Model'];
id(record: AirbyteRecord): string { return record.record.data.id; }
async convert(
record: AirbyteRecord,
ctx: StreamContext
): Promise<ReadonlyArray<DestinationRecordTyped<FooBar>>> {
const data = record.record.data;
return [{ model: 'test_Model', record: { foo: String(data.id), bar: 123 }}];
}
}
```
FAI-1665

FAI-1665 - Added ConverterTyped and DestinationRecordTyped

---

destinations/airbyte-faros-destination/src/converters/jenkins/builds.ts
destinations/airbyte-faros-destination/src/converters/jenkins/common.ts

If we are not going to allow for a configurable repo source fallback, it should just default to `VCS`.

Remove repoSourceFallback

---

.github/workflows/release.yml

This reverts commit d9e0b6bbb69340ffa18f5915324d10b03127cb16.
I believe major version only syntax only works for core GitHub actions.
> Fix [#1]() 

Revert "Use major version only (#388)"

---

scripts/publish-connector.sh

Add trailing slash to connector_path if missing 
https://github.com/faros-ai/airbyte-connectors/issues/449

Add trailing slash to connector_path if missing

---

destinations/airbyte-faros-destination/src/community/hasura-client.ts

```
2022-06-03 19:29:47 destination > Processed 0 records
2022-06-03 19:29:47 destination > Processed records by stream: {}
2022-06-03 19:29:47 destination > Wrote 0 records
2022-06-03 19:29:47 destination > Wrote records by model: {}
2022-06-03 19:29:47 destination > Skipped 0 records
2022-06-03 19:29:47 destination > Errored 0 records
2022-06-03 19:29:47 destination > Encountered an error while writing to destination: Cannot read property 'filter' of undefined
```

Added some empty checks

---

destinations/airbyte-faros-destination/resources/spec.json
destinations/airbyte-faros-destination/src/converters/asana/common.ts
destinations/airbyte-faros-destination/src/converters/servicenow/common.ts
destinations/airbyte-faros-destination/src/converters/servicenow/incidents.ts
sources/servicenow-source/resources/graphQL/listIncidentsQuery.gql
sources/servicenow-source/resources/schemas/incident.json
sources/servicenow-source/src/servicenow/models.ts
sources/servicenow-source/src/servicenow/servicenow.ts
sources/servicenow-source/test_files/incidents.json

Retrieve service information from ServiceNow incidents. Also pull all users when sys_updated_on not provided rather than falling back to cutoff.

FAI-2297: Impacted service information

---

sources/servicenow-source/test/index.test.ts

Add explicit tests to confirm that errors are being thrown out of readRecords.
Probably not worth bumping the version for this.

Test api errors thrown up

---

sources/datadog-source/README.md
sources/datadog-source/acceptance-test-config.yml
sources/datadog-source/resources/schemas/metric.json
sources/datadog-source/resources/spec.json
sources/datadog-source/src/datadog.ts
sources/datadog-source/src/index.ts
sources/datadog-source/src/streams/index.ts
sources/datadog-source/src/streams/metrics.ts
sources/datadog-source/test/index.test.ts
sources/datadog-source/test_files/metrics.json

* [datadog-source] Add support for fetching metrics via the /api/v1/query endpoint
N/A
N/A
This is my first time working with Airbyte and the Faros CDK, so comments/suggestions are welcome!
The biggest challenge I had building this connector is that the `api/v1/query` endpoint does not map directly to a specific resource like `users` or `incidents`. So I had to get creative in how to allow users to specify the metrics they'd like to fetch and keep a state for each of them.

[datadog-source] Add support for fetching metrics via the /api/v1/query endpoint

---

sources/datadog-source/resources/spec.json
sources/datadog-source/src/datadog.ts
sources/datadog-source/src/streams/metrics.ts
sources/datadog-source/test/index.test.ts

Airbyte UI does not support arrays of objects as configuration parameters for sources.
This change makes the Datadog source `metrics` config an array of strings instead of an array of objects.
This is a follow-up fix from #569 
When we tried the new stream introduced in #569 on the Airbyte UI, we got the following error:
> Internal Server Error: malformed JsonSchema array type, must have items field in {"item":{"type":"object","properties":{"query":"string"},"additionalProperties":false},"type":"array","order":3,"title":"Metrics","description":"list of metrics to fetch and their configuration"}

[datadog-source] Fix source configuration

---

destinations/airbyte-faros-destination/src/converters/gitlab/pipelines.ts
destinations/airbyte-faros-destination/test/converters/gitlab.test.ts

Add missing build createdAt and build commit association information to the GitLab pipeline converter
Example of cicd_Build and cicd_BuildCommitAssociation written by the updated converter:
```
{"model":"cicd_Build","record":{
"uid":"391934778",
"number":391934778,
"pipeline":{"organization":{"uid":"test5726","source":"GitLab"},"uid":"test"},
"status":{"category":"Success","detail":"success"},
"url":"https://gitlab.com/test5726/test/-/pipelines/391934778",
"createdAt":"2021-10-20T12:39:08.402Z",
"startedAt":"2021-10-20T12:39:08.402Z",
"endedAt":"2021-10-20T15:57:22.441Z",
"source":"GitLab"}}
{"model":"cicd_BuildCommitAssociation","record":{
"build":{"uid":"391934778","pipeline":{"organization":{"uid":"test5726","source":"GitLab"},"uid":"test"}}, …
```

GitLab build createdAt and commit association

---

sources/bamboohr-source/resources/spec.json
sources/datadog-source/resources/spec.json
sources/docker-source/resources/spec.json

The current spec is not a valid JSON Schema. 
See `items` [here](https://json-schema.org/understanding-json-schema/reference/array.html).
https://github.com/faros-ai/faros-community-edition/pull/203

Fix datadog spec

---

package-lock.json
sources/bitbucket-source/src/bitbucket/bitbucket.ts

Address certain cases where the `getEnvironment` endpoint of the Bitbucket API requires the environment id to be URIencoded.
Related thread: https://faroscommunity.slack.com/archives/C0335HMN2NQ/p1658348344173329
> Fix [#1]() 

Bitbucket source: try URIencoding environment id if first attempt fails

---

destinations/airbyte-faros-destination/resources/spec.json
sources/agileaccelerator-source/resources/spec.json
sources/azure-repos-source/resources/spec.json
sources/azureactivedirectory-source/resources/spec.json
sources/azurepipeline-source/resources/spec.json
sources/backlog-source/resources/spec.json
sources/bamboohr-source/resources/spec.json
sources/bitbucket-source/resources/spec.json
sources/buildkite-source/resources/spec.json
sources/circleci-source/resources/spec.json
sources/customer-io-source/resources/spec.json
sources/datadog-source/resources/spec.json
sources/docker-source/resources/spec.json
sources/example-source/resources/spec.json
sources/firehydrant-source/resources/spec.json
sources/gitlab-ci-source/resources/spec.json
sources/googlecalendar-source/resources/spec.json
sources/harness-source/resources/spec.json
sources/jenkins-source/resources/spec.json
sources/okta-source/resources/spec.json
sources/opsgenie-source/resources/spec.json
sources/pagerduty-source/resources/spec.json
sources/phabricator-source/resources/spec.json
sources/servicenow-source/resources/spec.json
sources/shortcut-source/resources/spec.json
sources/squadcast-source/resources/spec.json
sources/statuspage-source/resources/spec.json

Airbyte now requires `additionalProperties` = true in JSON schemas. https://github.com/airbytehq/airbyte/issues/14196
> Fix [#1]() 

Set additionalProperties: true

---

destinations/airbyte-faros-destination/src/converters/converter.ts
destinations/airbyte-faros-destination/test/converters/converter.test.ts

We need the sources to be lowercased so that the StreamName generated by a Converter is consistent with the StreamNames of dependencies.
Example:
The Jira Issues Converter needs to have the StreamName string `jira__issues` to match its dependencies https://github.com/faros-ai/airbyte-connectors/blob/main/destinations/airbyte-faros-destination/src/converters/jira/issues.ts#L60-L71
In a subsequent PR, I'm going to update all the converter dependencies to reference their own source instead of hardcoded strings, i.e. `this.source` instead of `'jira'`. However, `StreamName.asString()` still needs to lowercase the source to match the StreamNames used in generating the ConverterRegistry, where the paths to the converter files are used as keys.
> Fix [#1]() 
> …

Lowercase source when converting StreamName to string

---

destinations/airbyte-faros-destination/src/converters/servicenow/incidents.ts

Add missing destination models. @cjwooo this is needed to delete all written models during `full_refresh` mode, right?

ServiceNow: Correct destination model list

---

.github/workflows/dependabot-fix.yml

I'm not able to confirm if all the steps work yet, because [act](https://github.com/nektos/act) isn't letting my local workflow execution push to the repository.
> Fix [#1]() 

Add GitHub Actions Workflow to reformat package-lock.json on Dependabot PRs

---

package-lock.json
sources/datadog-source/package.json
sources/datadog-source/src/datadog.ts

Upgrade the Datadog API client to 1.2.0. There was some slight changes to the client's creation that needed to be updated. Also annoyingly they did not document correctly how to set unstable operations until yesterday.
**QUESTION:**
Are the changes in the package-lock.json correct? seems like a lot is changing...

FAI-2934 - Upgrade Datadog client to 1.2.0

---

sources/phabricator-source/resources/spec.json
sources/phabricator-source/src/phabricator.ts

Increase default Phabricator client timeout to 60 seconds + allow changing it

Increase default Phabricator client timeout to 60 seconds + allow changing it

---

destinations/airbyte-faros-destination/src/converters/phabricator/transactions.ts

Faros Destination: use set when counting unique commits per revision

Faros Destination: use Set when counting unique commits per revision

---

destinations/airbyte-faros-destination/resources/spec.json
destinations/airbyte-faros-destination/src/converters/bamboohr/common.ts
destinations/airbyte-faros-destination/src/converters/bamboohr/users.ts

This PR allows for the configuration of the custom 'employmentHistoryStatus' value that is equivalent to 'inactive' that should be used to determine if a user is inactive in Faros. If this configuration is not provided, the converter will fall back to doing what it was doing before: looking at the 'status' field.

FAI-3026 - Retrieve active status from employmentHistoryStatus

---

destinations/airbyte-faros-destination/src/common/graphql-client.ts

This PR fixes two issues:
1. The `errors` (if present) is a field under `response.data` instead of under `response`
2. We should always remove from the write buffer. We currently do not remove operations that fail in Hasura, so they are always kept around in the front of the buffer.
> Fix [#1]() 

Fix error handling in batch operations

---

destinations/airbyte-faros-destination/src/converters/common/common.ts
destinations/airbyte-faros-destination/src/converters/servicenow/incidents.ts
destinations/airbyte-faros-destination/test/converters/common.test.ts

Add uid to compute application model in ServiceNow (for Faros Community Edition)
> Fix [#1]() 

FAI-3028 Add uid to compute application model in ServiceNow

---

destinations/airbyte-faros-destination/src/common/graphql-client.ts
destinations/airbyte-faros-destination/src/community/hasura-backend.ts

Standardize response across `GraphQLBackend` implementations by extracting and returning the `data` field from Axios response in `HasuraBackend`.

FAI-3038: More GraphQL V2 Schema Updates

---

destinations/airbyte-faros-destination/src/converters/semaphoreci/pipelines.ts

Semaphore doesn't have a data model that represents uniqueness of a given pipeline. Currently we are taking the pipeline runs and using this to create a definition of a cicd_Pipeline. However, we are using the attribute `pipeline.name` as the unique identifier but this is not valid as pipelines across multiple repositories can have the same name.
This change concatenates the repository name to the `cicd_Pipeline`.`uid` which allow us to correctly create unique pipelines referencing their repository counter part
CICD data will need to be reloaded so that this change backfills existing loaded data

fix: create unique pipeline id based on project

---

destinations/airbyte-faros-destination/src/converters/circleci/common.ts
destinations/airbyte-faros-destination/src/converters/circleci/projects.ts

Fixes differences in pipeline and organization UIDs
> Currently different in the project vs pipeline streams. Leads to duplication of cicd_Pipeline entries with different IDs. 
> Full resync will be necessary
> We always use the full project slug and common methods, because the Circle CI API documentation is incorrect on fields like organization_slug.

CircleCI: Fixes differences in pipeline and organization UIDs

---

destinations/airbyte-faros-destination/src/common/graphql-client.ts

Ensure falsy values like `""` and `0` are valid field values.  This was discovered while reconciling Clio v1 vs. Hasura v2 Aion extract tables.  In a [converter](https://github.com/faros-ai/airbyte-connectors/blob/main/destinations/airbyte-faros-destination/src/converters/common/common.ts#L9) we explicitly set a field to `""`.  The prior logic was converting this back to `undefined`.

FAI-3587: Validate Dashboard sync for Faros tenant's V2 graph

---

destinations/airbyte-faros-destination/src/destination.ts
faros-airbyte-cdk/src/destinations/destination-runner.ts
faros-airbyte-cdk/src/logger.ts
faros-airbyte-cdk/src/protocol.ts
faros-airbyte-cdk/src/runner.ts
faros-airbyte-cdk/src/sources/source-base.ts
faros-airbyte-cdk/src/sources/source-runner.ts
sources/azureactivedirectory-source/src/azureactivedirectory.ts
sources/bitbucket-server-source/src/bitbucket-server/index.ts
sources/harness-source/src/harness.ts
sources/okta-source/src/okta.ts
sources/phabricator-source/src/phabricator.ts

Adds [`failure_type`](https://github.com/airbytehq/airbyte/blob/master/airbyte-protocol/protocol-models/src/main/resources/airbyte_protocol/airbyte_protocol.yaml#L194) to trace message and [`stack_trace`](https://github.com/airbytehq/airbyte/blob/master/airbyte-protocol/protocol-models/src/main/resources/airbyte_protocol/airbyte_protocol.yaml#L157) to log message
1. https://docs.airbyte.com/understanding-airbyte/airbyte-protocol/#airbytelogmessage
2. https://docs.airbyte.com/understanding-airbyte/airbyte-protocol/#changelog

Adds `failure_type` to trace message and `stack_trace` to log message

---

destinations/airbyte-faros-destination/src/converters/gitlab/pipelines.ts

Right now, it is empty. Given that each project has only one pipeline defined (we do not do anything with stages), that would be helpful.
Given https://github.com/airbytehq/airbyte/issues/18173, the git dashboard at https://github.com/faros-ai/faros-community-edition/pull/231 benefits from having the pipeline name always filled with the relevant details
* https://github.com/airbytehq/airbyte/issues/18173
* https://github.com/faros-ai/faros-community-edition/pull/231

Add project name as pipeline name in GitLab

---

destinations/airbyte-faros-destination/src/converters/gitlab/projects.ts

Important to properly filter "git" dashboard on one repository (including its issues).
Right now, repo/pipeline are e.g. `farosce-test` whereas board/project name are `FarosCE test` for https://gitlab.com/farosai/farosce-test
https://github.com/faros-ai/faros-community-edition/pull/231

GitLab: Harmonize project and board names with repo and pipeline name

---

destinations/airbyte-faros-destination/resources/spec.json
destinations/airbyte-faros-destination/src/common/types.ts
destinations/airbyte-faros-destination/src/community/hasura-backend.ts
destinations/airbyte-faros-destination/src/destination.ts

Axios keep alive defaults to false. Add an option to enable keep alive in Faros Destination.
https://github.com/axios/axios#request-config

Add an option to enable keep alive in Faros Destination

---

destinations/airbyte-faros-destination/src/converters/googlecalendar/common.ts
sources/googlecalendar-source/resources/spec.json
sources/googlecalendar-source/src/googlecalendar.ts
sources/googlecalendar-source/test/index.test.ts

1. Set default event visibility to Busy since Google Calendar doesn't return visibility value for "opaque" events
2. Added `cutoff_days` parameter for Google Calendar + logging

FAI-3916 - Google Calendar fixes

---

sources/buildkite-source/src/buildkite/buildkite.ts
sources/buildkite-source/test/index.test.ts
sources/buildkite-source/test_files/builds.json

Use paginated GraphQL API to list pipelines in build stream
Currently, the builds stream (contrary to the pipelines stream) uses the REST API to get the list of pipelines to iterate over. That method does not paginate, which means that when one has more than 30 pipelines, builds will be missed.
We switch to the GraphQL API for listing pipelines, for which we paginate properly.

[Buildkite] Fix missing builds when large number of pipelines

---

sources/azureactivedirectory-source/resources/spec.json

The new source acceptance test image version enforces config params with certain names to be secret.
https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_core.py#L58-L76
> Fix [#1]() 

Azure Active Directory: make tenant_id secret

---

sources/googlecalendar-source/README.md
sources/googlecalendar-source/src/googlecalendar.ts

This enable service account impersonation (in case the user is organization manager & want to use a service account to access memebers' calendars)
Current implementation of GoogleCalendar source connector only allows calendar owner or invited accounts to access calendar.
In normal case, this is fine. But in an organization, when admins need to access members' calendars to calculate necessary metrics to determine productivity, forcing all members to share their calendar with an account is tricky.
This PR enable service account impersonation (together with domain-wide delegation), so that an authenticated service account can access organization members' calendars.

Enable service account impersonation in GoogleCalendar source connector

---

faros-airbyte-cdk/src/sources/source-base.ts

1. Removed logging on every stream slice checkpoint operation (this should make logging less noisy)
2. Added logging on start & end of each stream slice with number of read records

Better logging for sources

---

sources/azurepipeline-source/resources/spec.json
sources/azurepipeline-source/src/azurepipeline.ts
sources/azurepipeline-source/src/streams/builds.ts
sources/azurepipeline-source/src/streams/pipelines.ts
sources/azurepipeline-source/src/streams/releases.ts
sources/azurepipeline-source/test/index.test.ts
sources/azurepipeline-source/test_files/invalid_config.json

Support syncing multiple projects for the `Azure pipelines` connector. This includes: pipelines, build and releases
Replace the config `project` with type `string` with `project_names` with type `string[]`

support multiple azure pipeline projects

---

destinations/airbyte-faros-destination/resources/spec.json
destinations/airbyte-faros-destination/src/common/graphql-client.ts
destinations/airbyte-faros-destination/src/destination.ts

Disabling the recently added upsert batching for CE.  The proximate issue is odd behavior from Hasura for batch inserts.  Specifically, the following query fails if it has more than one object:
```
mutation {
insert_tms_User(objects: [
{uid: "u1", source: "GitHub", origin: "mytestsource"},
{uid: "u2", name: "chalenge", source: "GitHub", origin: "mytestsource"}, 
], on_conflict: {constraint: tms_User_pkey, 
update_columns: [emailAddress, name, origin, refreshedAt]}) {
returning {
id
source
uid
}
}
}
```
The error given is:
```
{
"error": {
"exec_status": "FatalError",
"hint": null,
"message": "cannot insert into column 'id'",
"status_code": "42601",
"description": "Column 'id' is a generated column."
}
}
```
There is no attempt to insert `id` here.  Our use of permissions must be …

Disable upsert batching for CE

---

sources/faros-graphql-source/src/streams/faros-graph.ts
sources/faros-graphql-source/test/__snapshots__/index.test.ts.snap

Returning these fields causes issues in the destination:
```
errors":[{"extensions":{"code":"validation-failed","path":"$.selectionSet.insert_vcs_User.args.objects[0].refreshedAt"},"message":"field 'refreshedAt' not found in type: 'vcs_User_insert_input'"}]}}}
```
We could instead remove them in the destination, but since we only use them as a watermark for the incremental syncs and they get automatically updated on write, they're really not useful in the returned record.
> Fix [#1]() 

Remove metadata/refreshedAt from result record

---

package-lock.json
sources/faros-graphql-source/package.json
sources/faros-graphql-source/src/streams/faros-graph.ts
sources/faros-graphql-source/test/index.test.ts

Upgrade faros-js-client and use references info when creating incremental queries (`V2` only) 
Also, tweak state management by using the input query (if provided) as state key. Otherwise we use the model names as keys

Upgrade faros-js-client + tweak state

---

sources/agileaccelerator-source/README.md
sources/azure-repos-source/README.md
sources/azureactivedirectory-source/README.md
sources/azurepipeline-source/README.md
sources/backlog-source/README.md
sources/bamboohr-source/README.md
sources/bitbucket-server-source/README.md
sources/bitbucket-source/README.md
sources/buildkite-source/README.md
sources/circleci-source/README.md
sources/customer-io-source/README.md
sources/firehydrant-source/README.md
sources/gitlab-ci-source/README.md
sources/googlecalendar-source/README.md
sources/harness-source/README.md
sources/jenkins-source/README.md
sources/opsgenie-source/README.md
sources/pagerduty-source/README.md
sources/phabricator-source/README.md
sources/semaphoreci-source/README.md
sources/shortcut-source/README.md
sources/squadcast-source/README.md
sources/victorops-source/README.md

Change all references of `azure-repo` to `azure-repos` to match published image name and folder structure.
> Fix [#1]() 

Fix azure-repos-source readme and add version build-arg to all readmes

---

faros-airbyte-cdk/package.json
package-lock.json

Set pino version to 8.5.0. This should fix the release of cdk package.

Set pino version to 8.5.0

---

sources/datadog-source/resources/spec.json
sources/datadog-source/src/datadog.ts

Update to the datadog connector to allow multiple sites not just the default US one.
https://github.com/faros-ai/airbyte-connectors/issues/856
None there is now a default set to the original datadog site.

Update to the Datadog source to allow multiple sites not just the default US one.

---

destinations/airbyte-faros-destination/src/converters/faros-feeds/faros_feed.ts
destinations/airbyte-faros-destination/test/converters/faros_feeds.test.ts

I think I added this as a precaution to prevent accidentally dropping records, but it is actually unnecessary and results in different behavior of feed depending on whether it is run directly or via the Faros Feeds wrapper.
It is safe to remove because, if we run a full sync in Airbyte, [all](https://github.com/faros-ai/airbyte-connectors/blob/main/destinations/airbyte-faros-destination/src/converters/faros-feeds/model_names.ts) models are reset, so it doesn't matter what happens in the feed. Feeds will always issue deletion records for "non-incremental" models only (unless invoked with `--no-incremental`) so it's safe to process these deletion records.
> Fix [#1]() 

Honor deletion records

---

sources/opsgenie-source/resources/schemas/alerts.json
sources/opsgenie-source/src/index.ts
sources/opsgenie-source/src/opsgenie/models.ts
sources/opsgenie-source/src/opsgenie/opsgenie.ts
sources/opsgenie-source/src/streams/alerts.ts
sources/opsgenie-source/src/streams/index.ts
sources/opsgenie-source/test/index.test.ts
sources/opsgenie-source/test_files/alerts.json
sources/opsgenie-source/test_files/full_configured_catalog.json
sources/opsgenie-source/test_files/incremental_configured_catalog.json

> Adding Alerts stream in OpsGenie connector
```
➜  opsgenie-source git:(mudasir/adding_alerts_stream_opsgenie) npm test
> opsgenie-source@0.0.1 test
> jest --verbose --color
PASS  test/index.test.ts
index
✓ spec (2 ms)
✓ check connection (1 ms)
✓ check connection - incorrect config (1 ms)
✓ streams - incidents, use full_refresh sync mode (2 ms)
✓ streams - incidents, paginate
✓ streams - teams, use full_refresh sync mode (1 ms)
✓ streams - users, use full_refresh sync mode (1 ms)
✓ streams - users, paginate
✓ streams - alerts, use full_refresh sync mode (1 ms)
✓ streams - alerts, paginate (1 ms)
Test Suites: 1 passed, 1 total
Tests:       10 passed, 10 total
Snapshots:   0 total
Time:        0.45 s, estimated 5 s
Ran all test suites.
➜  opsgenie-source …
```

Adding alerts stream in OpsGenie Connector

---

destinations/airbyte-faros-destination/src/common/graphql-client.ts
destinations/airbyte-faros-destination/test/__snapshots__/graphql-client.test.ts.snap
destinations/airbyte-faros-destination/test/graphql-client.test.ts

Bug fix to address object count discrepancies between GraphQL v1 and v2 queries.  
Analysis of query results and input data indicated that v2 loading processing was not setting `origin` field in the same way as v1 process.  One major difference was v2 set `origin` on both root-level objects (i.e. those present as records in input file) and nested objects (aka references).  
After removing `origin` for reference objects a discrepancy remained.  This was traced to a bug in the `on_conflict` clause of the upsert and update statements.  Specifically, the `update_columns` field of `on_conflict` included all non-key fields regardless of the fields included in the data being processed. 
When updates were made the mismatch of `update_columns` and fields of object led to columns in …

FAI-4564: Read-path GraphQL v2 Perf Improvement

---

sources/clickup-source/acceptance-test-config.yml

ClickUp test: ignore status_history fields because they contain relative timestamps

---

sources/customer-io-source/src/customer-io/customer-io.ts

> Change Customer.io API base url to https://api.customer.io/v1 instead of https://beta-api.customer.io/v1/api as it is mentioned [here](https://customer.io/docs/release-notes/2022-02-28-beta-api-official-release/)

fix: change customer.io base url

---

destinations/airbyte-faros-destination/resources/spec.json
destinations/airbyte-faros-destination/src/converters/clickup/common.ts
destinations/airbyte-faros-destination/src/converters/clickup/folders.ts
destinations/airbyte-faros-destination/src/converters/clickup/lists.ts
destinations/airbyte-faros-destination/src/converters/clickup/spaces.ts
destinations/airbyte-faros-destination/src/converters/clickup/tasks.ts
destinations/airbyte-faros-destination/test/converters/clickup.test.ts

If users request it, we'll support more than one taskboard source, but that will also require Faros UI changes.
> Fix [#1]() 

FAI-3458: Clickup Converter - Only use one taskboard source

---

faros-airbyte-cdk/package.json
faros-airbyte-cdk/src/destinations/destination-runner.ts
faros-airbyte-cdk/src/help.ts
faros-airbyte-cdk/src/index.ts
faros-airbyte-cdk/src/sources/source-runner.ts
package-lock.json

Add spec-pretty subcommand to all connectors. This command generates a help table from the connector's spec to guide a user on how to configure the connector via the command line args when using Faros [airbyte-local-cli](https://github.com/faros-ai/airbyte-local-cli)
Example output for a source:
Example output for a destination (truncated):
> Fix [#1]() 

Add spec-pretty subcommand to all connectors

---

destinations/airbyte-faros-destination/src/common/graphql-client.ts

With [Hasura #45](https://github.com/faros-ai/hasura/pull/45), we've altered schema to store string arrays with array field (i.e. `text []`) instead of `jsonb`.  This requires input to be formatted as [postgres array literal](https://www.postgresql.org/docs/current/arrays.html#ARRAYS-INPUT).

FAI-4951: graph-to-graph copy object count discrepancies

---

sources/faros-graphql-source/resources/spec.json
sources/faros-graphql-source/src/index.ts
sources/faros-graphql-source/src/streams/faros-graph.ts
sources/faros-graphql-source/test/index.test.ts

So that we can split reading a full graph into N buckets concurrently.
> Fix [#1]() 

Make it possible to partition full model queries

---

destinations/airbyte-faros-destination/resources/spec.json

JSONata expressions can be long. This will make it easier for copy/pasting since longer expressions are not written as a one-liner.
> Fix [#1]() 

Make jsonata_expression multiline

---

destinations/airbyte-faros-destination/src/common/graphql-client.ts
destinations/airbyte-faros-destination/test/__snapshots__/graphql-client.test.ts.snap
destinations/airbyte-faros-destination/test/graphql-client.test.ts

This PR fixes 2 bugs that present in similar ways but due to different codes paths have different solutions 
In #862, we added a step to batch processing to separate objects into groups by the keys present in the objects.  We then constructed `on_conflict.update_columns` arrays based on the keys of each group.  This was done to fix a bug that nulled out fields of existing rows that were present in the `update_columns` array but not present in the object.
The (flawed) procedure for doing this was roughly:
1. for each batch separate objects into groups by keys of objects
2. add FKs to objects from prior batches
3. using first object of a group as prototype, construct `update_columns` for the group.
This procedure was flawed because the 2nd step could alter keys of a subset of group.  Said …

FAI-4901: Hasura End-to-End Testing

---

sources/datadog-source/resources/schemas/incident.json

When we tried to get incidents from datadog,  always throw the following error
Also, this json schema was malformed because it had a duplicate `properties` key
After update json schema for incidenst, it works.
> 
> Fix [#1]() 

fix: update json schema incidents for datadog

---

destinations/airbyte-faros-destination/src/converters/gitlab/common.ts
destinations/airbyte-faros-destination/src/converters/gitlab/group_milestones.ts
destinations/airbyte-faros-destination/src/converters/gitlab/groups.ts
destinations/airbyte-faros-destination/src/converters/gitlab/issues.ts
destinations/airbyte-faros-destination/src/converters/gitlab/jobs.ts
destinations/airbyte-faros-destination/src/converters/gitlab/pipelines.ts
destinations/airbyte-faros-destination/src/converters/gitlab/project_milestones.ts
destinations/airbyte-faros-destination/src/converters/gitlab/projects.ts
destinations/airbyte-faros-destination/src/converters/gitlab/releases.ts

GitLab supports nested groups which need to be considered when parsing the repo key. For example,
`top-level-group / nested-group / project`
Currently, `nested-group` is being treated as the project name and uid. This patch changes the parsing so that:
name = project
uid = nested-group / project
Fix #891

GitLab Converter: Process nested group repo keys correctly

---

destinations/airbyte-faros-destination/src/common/graphql-writer.ts
destinations/airbyte-faros-destination/src/converters/servicenow/incidents.ts

Remove model & origin in ServiceNow destination + make sure we use the correct values for origin, model and operation in GraphQL writer

Remove model & origin in ServiceNow destination + make sure we use the correct values in GraphQL writer

---

destinations/airbyte-faros-destination/src/converters/faros-feeds/faros_feed.ts

Ignore feeds reset records when not writing to V1
> Fix [#1]() 

Ignore feeds reset records when not writing to V1

---

destinations/airbyte-faros-destination/resources/source-specific-configs.json
destinations/airbyte-faros-destination/src/converters/servicenow/common.ts
destinations/airbyte-faros-destination/src/converters/servicenow/incidents.ts

Ensures that when an incident is associated to more than one application in the processed records, all the associations (`incidentApplicationImpacts`) are persisted.
Also changes the configuration setting and wording of the behavior when turned on.
> Fix [#1]() 

Remove previously stored incident-application association(s) for processed incident(s)

---

destinations/airbyte-faros-destination/src/converters/faros-feeds/faros_feed.ts

Because of the way [withDefaults](https://github.com/faros-ai/airbyte-connectors/blob/main/faros-airbyte-cdk/src/utils.ts#L43) works, `graphql_api` defaults to `V1` also for Community edition.
> Fix [#1]() 

Fix Graph API version check

---

faros-airbyte-cdk/src/help.ts

Properly handles [object with no props](https://github.com/faros-ai/airbyte-connectors/blob/43f941c863e3e9ef15da03da92caa3468a3613bb/destinations/airbyte-faros-destination/resources/source-specific-configs.json#L562)
Also moves the "Skip" choice up for `oneOf`s to be consistent with what we do for leaves
> Fix [#1]() 

Properly handles object with no props

---

destinations/airbyte-faros-destination/src/common/graphql-client.ts
destinations/airbyte-faros-destination/test/graphql-client.test.ts

Ensure null value replacement only happens for nullish keys.  
The use of `||` as a coalesce operator by itself was OK because we map keys to strings and strings to keys consistently.  
However, in the case of the `mock-data` feed we are inconsistent about the type of the `number` field for different model types.  
For example, notice the different types for `number` field in this record:
```
{
"record": {
"stream": "myfarosfeedssrc__faros_feeds__faros_feed",
"emitted_at": 1678482135607,
"data": {
"vcs_PullRequestComment": {
"pullRequest": {
"number": 0,
"repository": {
"name": "solaris",
"language": "javascript",
"mainBranch": "main",
"organization": {
"uid": "faros-ai",
"source": "Mock"
}
}
},
"number": "0",
"createdAt": "2023-02-26T17:44:21.846Z",
"author": {
"uid": "sirius",
"source": …
```

FAI-5403: Mock-data feed sync write failure to V2 graph

---

sources/statuspage-source/resources/spec.json

Non-string params marked as secrets cause Airbyte API errors, and are also not consumed properly during syncs.
> Fix [#1]() 

FAI-5468 - Make Statuspage page_ids param non-secret

---

sources/octopus-source/src/octopusClient.ts
sources/octopus-source/test/octopusClient.test.ts

Strip trailing `/` suffix off Octopus instance url if provided.

Octopus strip '/' instance URL suffix if provided

---

destinations/airbyte-faros-destination/src/converters/statuspage/incidents.ts
package-lock.json

Look through incident's historical updates and grab highest severity from those. This will fix the issue of incidents all having sev5 because they are eventually set back to operational once fixed.

[FAI-5472] Use highest historical severity for status page

---

sources/octopus-source/resources/spec.json
sources/octopus-source/src/models.ts
sources/octopus-source/src/octopus.ts

Older versions of octopus do not expose the API used to retrieve deployment processes. This PR allows disabling that call.

Octopus allow disabling fetching deployment process

---

destinations/airbyte-faros-destination/resources/source-specific-configs/agileaccelerator.json
destinations/airbyte-faros-destination/resources/source-specific-configs/azurepipeline.json
destinations/airbyte-faros-destination/resources/source-specific-configs/backlog.json
destinations/airbyte-faros-destination/resources/source-specific-configs/bamboohr.json
destinations/airbyte-faros-destination/resources/source-specific-configs/bitbucket.json
destinations/airbyte-faros-destination/resources/source-specific-configs/clickup.json
destinations/airbyte-faros-destination/resources/source-specific-configs/datadog.json
destinations/airbyte-faros-destination/resources/source-specific-configs/docker.json
destinations/airbyte-faros-destination/resources/source-specific-configs/firehydrant.json
destinations/airbyte-faros-destination/resources/source-specific-configs/jenkins.json
destinations/airbyte-faros-destination/resources/source-specific-configs/jira.json
destinations/airbyte-faros-destination/resources/source-specific-configs/notion.json
destinations/airbyte-faros-destination/resources/source-specific-configs/opsgenie.json
destinations/airbyte-faros-destination/resources/source-specific-configs/pagerduty.json
destinations/airbyte-faros-destination/resources/source-specific-configs/phabricator.json
destinations/airbyte-faros-destination/resources/source-specific-configs/servicenow.json
destinations/airbyte-faros-destination/resources/source-specific-configs/spec.json
destinations/airbyte-faros-destination/resources/source-specific-configs/squadcast.json
destinations/airbyte-faros-destination/resources/source-specific-configs/statuspage.json
destinations/airbyte-faros-destination/resources/source-specific-configs/victorops.json

Replaces https://github.com/faros-ai/airbyte-connectors/pull/865.
This PR makes the spec compatible for newer versions of Airbyte without changing the locations of anything in the resulting config object.
> Fix [#1]() 

Add shared consts to oneOf objects

---

destinations/airbyte-faros-destination/test/cli.ts
destinations/airbyte-faros-destination/test/index.test.ts

If the expected test output exceeds 8192 characters, `stdout` must be read and tested before `stderr`. 
> Fix [#1]() 

Fix test cli stream reading logic and spec test

---

sources/pagerduty-source/src/pagerduty.ts
sources/pagerduty-source/test/pagerduty.test.ts

pdjs (under the hood `cross-fetch`) does not reject 4xx responses. We need to check for them in non exceptional processing.

Handle Pagerduty pagination 10000 limit

---

sources/pagerduty-source/src/pagerduty.ts
sources/pagerduty-source/src/streams/incidentLogEntries.ts
sources/pagerduty-source/src/streams/incidents.ts
sources/pagerduty-source/src/streams/services.ts
sources/pagerduty-source/src/streams/teams.ts
sources/pagerduty-source/src/streams/users.ts
sources/pagerduty-source/test/pagerduty.test.ts

There is another way in which the API will response 400 when pagination exceeds 10,000 items. We need to handle that scenario as well.
```
Status code: 400: Bad Request. Data: {\"error\":{\"message\":\"Arguments Caused Error\",\"code\":2002,\"errors\":[\"Offset+limit exceeds maximum allowed value of 10000. Please try to refine your search to reduce the returned set of records below this number, like adding a date range.\"]}}"
```
I also noticed that we are including 2 `limit` params in our requests. We should not explicitly be setting `limit` but instead we should let the pd client set it based off of the configured page size (we are already setting this).
Notice the two limits:
```
https://api.pagerduty.com/incidents?limit=25&time_zone=UTC&since=2023-04-20T17%3A22%3A42.511%2B00%3A00&until …
```

Fix pd pagination scenario 2

---

sources/octopus-source/resources/spec.json
sources/octopus-source/src/octopus.ts
sources/octopus-source/src/octopusClient.ts
sources/octopus-source/test/index.test.ts

Improvements to the Octopus source:
- In certain situations, a nonretryable 500 is responded from the octopus API when attempting to request a source controlled resource without a source controlled url. We should not retry these requests.
- Sometimes the project deployment process cannot be retrieved but the deployment specific process can be. We should fall back to the deployment specific process.
- Do not pull deployment process by default

FAI-6073 - Octopus source improvements

---

sources/bitbucket-server-source/src/bitbucket-server/index.ts
sources/bitbucket-server-source/src/streams/commits.ts
sources/bitbucket-server-source/src/streams/common.ts
sources/bitbucket-server-source/src/streams/project_users.ts
sources/bitbucket-server-source/src/streams/pull_request_substream.ts
sources/bitbucket-server-source/src/streams/pull_requests.ts
sources/bitbucket-server-source/src/streams/repositories.ts
sources/bitbucket-server-source/src/streams/tags.ts

When a project name changes bitbucket will redirect the old project calls to the new ID. This was messing us up because some of our streams were using the provided name (old) while other were using the returned name (new). This change makes sure we're always using the returned key for consistency.

[FAI-6075] Fix repo key for consistency

---

destinations/airbyte-faros-destination/src/common/graphql-client.ts
destinations/airbyte-faros-destination/test/__snapshots__/graphql-client.test.ts.snap
destinations/airbyte-faros-destination/test/graphql-client.test.ts
destinations/airbyte-faros-destination/test/resources/hasura-schema.json

This PR changes the mutations created by `__Update` records from updates to upserts.  This change was necessary to allow `__Update` records to patch relationships.   When run as updates (that patch relationships), the prior implementation failed at in Hasura with errors like the following:
```
{
"errors": [
{
"extensions": {
"code": "validation-failed",
"path": "$.selectionSet.update_vcs_PullRequest.args._set.mergeCommit"
},
"message": "field 'mergeCommit' not found in type: 'vcs_PullRequest_set_input'"
}
]
}
```

FAI-6116: Interpret Updates as Upserts

---

destinations/airbyte-faros-destination/src/converters/converter.ts
destinations/airbyte-faros-destination/src/converters/faros-feeds/faros_feed.ts
destinations/airbyte-faros-destination/src/destination.ts

For Community Edition, we need to make sure the deletions are processed in topological order.
For Cloud V2, the deletion records coming from feeds are not valid (they look like `{"vcs_TeamMembership__Deletion":{"where":"my-source"}` with `my-source` being the origin)
We instead accumulate all the model _**names**_ for which we get a full model deletion record and reuse `resetData` which takes care of both problems for us.
No changes needed for Cloud V1.
> Fix [#1]() 

FAI-6076 Honor full model deletion records coming from feeds

---

sources/jenkins-source/resources/schemas/builds.json
sources/jenkins-source/src/jenkins.ts

This change is to add description field in Jenkins builds data-stream
For the [jenkins-source](https://github.com/faros-ai/airbyte-connectors/tree/main/sources/jenkins-source) connector
The builds table is currently having the below columns:
"result"
"duration"
"number"
"displayname"
"fulldisplayname"
"id"
"_class"
"actions"
"url"
building"
"timestamp"
"_airbyte_ab_id"
"_airbyte_emitted_at"
"_airbyte_normalized_at"
"_airbyte_builds_hashid"
description field is missing, which has the information like parameters used to execute the build job.
This is one of the important fields need.
The description field is available in the API response.
https://your.jenkins.url/job/$JOB_NAME/$BUILD_NUMBER/api/json?pretty=true
This can be be added to Jenkins connector by modifying the below files to …

added changes to include description field in jenkins build datastream

---

faros-airbyte-cdk/src/help.ts

Simplify boolean input by ignoring examples and just showing a dropdown with `false` and `true`. If there's a default, we indicate which one is it.

FAI-5599 Improve wizard boolean input

---

sources/statuspage-source/resources/schemas/component_groups.json
sources/statuspage-source/resources/schemas/components.json
sources/statuspage-source/src/index.ts
sources/statuspage-source/src/statuspage.ts
sources/statuspage-source/src/streams/component_groups.ts
sources/statuspage-source/src/streams/components.ts
sources/statuspage-source/src/streams/index.ts
sources/statuspage-source/src/types.ts
sources/statuspage-source/test/index.test.ts
sources/statuspage-source/test_files/component_groups.json
sources/statuspage-source/test_files/components.json
sources/statuspage-source/test_files/full_configured_catalog.json

- Add components and component_groups streams to Statuspage source.
- Faros Destination sets compute_Application platform field for Statuspage components to `<component group name>/<statuspage page name>`.
> Fix [#1]() 

FAI-6311 - Statuspage connector updates

---

destinations/airbyte-faros-destination/src/common/graphql-client.ts
destinations/airbyte-faros-destination/src/destination.ts

Current behavior is Airbyte connectors do not delete records that are referenced by other existing records when resetting non-incremental models or during a full sync. This was because the related model reset logic was developed with Faros CE as the only use case, and the model tables in Faros CE have foreign key relationships that do not allow deletions of records that are being referenced by records from other tables.
In Faros SaaS, we do allow such deletions, similar to our old phantom behavior. Airbyte connectors running in SaaS should be updated to delete model records that are referenced by other records. The referencing records will still maintain their references to the phantoms.
I tested this by running the Statuspage connector on a Faros graph in SaaS, and then marked generated …

FAI-6360 - Option to delete records that are referenced by other records when resetting models

---

destinations/airbyte-faros-destination/package.json
destinations/airbyte-faros-destination/src/common/graphql-client.ts
destinations/airbyte-faros-destination/test/__snapshots__/graphql-client.test.ts.snap
package-lock.json
sources/faros-graphql-source/package.json

Changes to eliminate or handle deadlocks for concurrent writes via Faros destination
1. bump `faros-js-client` to get `HTTP 409` retry behavior for `graphql` endpoint
2. order objects within upsert batch to eliminate deadlocks for concurrent inserts

FAI-6462: Avoid or handle deadlocks for concurrent writes with Faros destination

---

destinations/airbyte-faros-destination/src/common/graphql-client.ts
destinations/airbyte-faros-destination/test/graphql-client.test.ts

Fix handling of empty string by quoting strings and translating `nil` to `NULL`.

FAI-6560: handle nil/empty array literals properly

---

faros-airbyte-cdk/src/destinations/destination-runner.ts
faros-airbyte-cdk/src/sources/source-runner.ts

This will allow using the wizard with any airbyte connector, not just the ones developed with Faros CDK.
In the Airbyte local CLI we'll just need to output the non-Faros connectors' spec into a file and use any of the Faros connectors to run the wizard from that spec.
Example below runs the Faros destination wizard from an arbitrary Faros source.
> Fix [#1]() 

FAI-5603 Accept a spec from a given file path

---

destinations/airbyte-faros-destination/src/common/graphql-client.ts
destinations/airbyte-faros-destination/test/__snapshots__/graphql-client.test.ts.snap
destinations/airbyte-faros-destination/test/graphql-client.test.ts

Allow upserts of `nil` (i.e. null and undefined) values and relations.  Also, validate the `uid` fields are non-null while processing records.  This prevents a later db constraint violation that results in a full batch being discarded.

FAI-6714: ensure upserts update nil values and relations

---

Dockerfile

I don't know why this command is failing now in the docker build, and I want to unblock the connector acceptance tests and the release workflow now.
> Fix [#1]() 

Skip 'lerna version' command in Dockerfile

---

.github/workflows/ci.yml

Issues like the one which happened when we bumped Commander package which [had to be reverted](https://github.com/faros-ai/airbyte-connectors/pull/1063) might be able to be caught before merging by attempting the destination packaging within our CI workflow

[FAI-6768] Add destination packaging test to ci.yml

---

destinations/airbyte-faros-destination/src/converters/statuspage/incidents.ts

`startedAt` was not being written for some reason. Uptime is calculated using `startedAt` and `resolvedAt` so without `startedAt`, uptime would always be 100%.

FAI-6879 - StatusPage incidents should include startedAt

---

destinations/airbyte-faros-destination/package.json
package-lock.json
sources/faros-graphql-source/package.json

Bump client to get unlimited request/response sizes

FAI-6878: add request compression to faros-js-client

---

.github/workflows/skip-test-sources.txt
destinations/airbyte-faros-destination/src/converters/statuspage/component_uptimes.ts
sources/statuspage-source/resources/spec.json
sources/statuspage-source/src/statuspage.ts
sources/statuspage-source/src/streams/component_uptime.ts
sources/statuspage-source/test/index.test.ts

- Enable the option to disable syncing uptimes for components
- Ensure we only try to fetch a max of 90 days
- Fix uptime UID

FAI-6879: Enable option to disable syncing uptimes for components

---

sources/statuspage-source/src/statuspage.ts
sources/statuspage-source/src/streams/component_uptime.ts
sources/statuspage-source/test/index.test.ts

- Statuspage source should factor in component start date when fetching otherwise it fails with 422 for an invalid range_start
> Fix [#1]() 

Statuspage source should factor component start date when fetching

---

faros-airbyte-cdk/src/help.ts

Allows to use an exported variable instead of entering a password/multiline string.
> Fix [#1]() 

FAI-5601 Add choice to use variable for airbyte secrets/multiline

---

faros-airbyte-cdk/src/help.ts

Fix bug where, if an array field is marked required, we never show an option (`Done`) to stop entering values
> Fix [#1]() 

Fix handling of required array field

---

sources/pagerduty-source/resources/schemas/incidentLogEntries.json
sources/pagerduty-source/src/pagerduty.ts
sources/pagerduty-source/test/pagerduty.test.ts

The Agent field provides information about who made the respective log entry.
This PR adds that field to the data we ingest from the [Log Entries API
](https://developer.pagerduty.com/api-reference/c661e065403b5-list-log-entries)
nil
nil
nil

Add agent field

---

faros-airbyte-cdk/src/help.ts

The value [here](https://github.com/faros-ai/airbyte-connectors/blob/07516a04471d68bec9be1a3d343ed8b2398920f4/faros-airbyte-cdk/src/help.ts#L341) doesn't match the value in the switch [here](https://github.com/faros-ai/airbyte-connectors/blob/07516a04471d68bec9be1a3d343ed8b2398920f4/faros-airbyte-cdk/src/help.ts#L371)
As a result, we don't use the default value of an enum, but instead the string `Used default <some default>.`
> Fix [#1]() 

Fix enum default

---

sources/customer-io-source/resources/spec.json
sources/customer-io-source/src/customer-io/customer-io.ts

Allow configuring Customer.io API url
https://github.com/faros-ai/airbyte-connectors/issues/1118

Allow configuring Customer.io API url

---

sources/circleci-source/resources/spec.json
sources/circleci-source/src/circleci/circleci.ts

Also, removed `cutoff_days` from required fields, since it has a default.
> Fix [#1]() 

Add request_timeout to the CircleCI spec

---

destinations/airbyte-faros-destination/src/converters/asana/tasks.ts

`assignee` is an object with a `gid`, as we can see from the example source output record below:
```{"type":"RECORD","record":{"stream":"tasks","data":{"gid":"1205346703408262","assignee":{"gid":"7440298482110"},"completed":false,"completed_at":null,"completed_by":null,"created_at":"2023-08-24T15:52:00.014Z","custom_fields":[],"dependencies":[],"dependents":[],"due_at":null,"due_on":"2023-08-31","followers":[{"gid":"7440298482110"}],"hearted":false,"hearts":[],"html_notes":"<body></body>","is_rendered_as_separator":false,"liked":false,"likes":[],"memberships":[{"project":{"gid":"1205346703408259"},"section":{"gid":"1205346703408260"}}],"modified_at":"2023-08-24T15:52:17.456Z","name":"Task 1","notes":"","num_hearts":0,"num_likes":0,"num_subtasks":0,"parent":null,"permalink_url":"https://app …
```

Fix asana tasks converter

---

destinations/airbyte-faros-destination/resources/cloud.json
destinations/airbyte-faros-destination/src/destination.ts

`api_url` shouldn't be required since there's a default value in the spec
> Fix [#1]() 

Honor default Faros API URL

---

sources/workday-source/src/index.ts
sources/workday-source/src/streams/customreports.ts
sources/workday-source/src/streams/index.ts
sources/workday-source/test/index.test.ts

Stream name "customreports" was failing, so we changed the class name from "CustomReports" to "Customreports".
This made the fix. Thanks to @cjwooo for the tip.
- [ X] Bug fix

[FAI-2451] Replacing CustomReports with Customreports

---

destinations/airbyte-faros-destination/src/converters/azure-repos/commits.ts
destinations/airbyte-faros-destination/src/converters/azure-repos/common.ts
destinations/airbyte-faros-destination/src/converters/azure-repos/pull_requests.ts
destinations/airbyte-faros-destination/src/converters/bitbucket-server/pull_request_activities.ts
destinations/airbyte-faros-destination/src/converters/bitbucket/pull_request_activities.ts
destinations/airbyte-faros-destination/src/converters/github/review_comments.ts

Avoid writing very long comment messages into the graph.
The actual error:
```
index row requires 9352 bytes maximum size is 8191
```
reported in https://github.com/faros-ai/faros-community-edition/issues/312

Truncate comment in `vcs_PullRequestComment` records to 1000 chars

---

sources/circleci-source/src/streams/tests.ts

There is a scenario where we are double counting tests for jobs that are rebuilt. We should only pull the tests for a given job number once.

FAI-7679 - CircleCI test double counting fix

---

destinations/airbyte-faros-destination/src/converters/circleci/models.ts
destinations/airbyte-faros-destination/src/converters/circleci/tests.ts
sources/circleci-source/src/circleci/typings.ts
sources/circleci-source/src/streams/tests.ts
sources/circleci-source/test_files/tests.json

The CircleCI connector incorrectly double counts tests when a run is rebuilt. I suspect that the `job_number` is not unique enough and is reused for the reruns. `job_id` should be unique enough. I also added logic to ignore a job's tests when `job_number` is undefined. There are some control jobs that don't have job numbers, for example an approval step.

FAI-7679 - CircleCI should ignore undefined run numbers

---

destinations/airbyte-faros-destination/src/converters/circleci/tests.ts

We are still seeing double counting in the CircleCI connector's tests when a test is rerun. I have not been able to reproduce this double counting behavior but here is another guess at what might fix it.

FAI-7679 - Deduplicate test case results

---

sources/circleci-source/src/streams/tests.ts

Figured it out the root cause finally. Jobs are at the pipeline level and workflows can share jobs if a workflow is executed from the failed step. It will point to the same jobs up to the point of the failure and then create new jobs for the remained.

FAI-7679 - Dedup jobs shared by workflows

---

sources/faros-graphql-source/resources/spec.json
sources/faros-graphql-source/src/index.ts
sources/faros-graphql-source/test/index.test.ts

Honor `api_url` and `graphql_api` defaults
> Fix [#1]() 

Honor api_url and graphql_api defaults

---

destinations/airbyte-faros-destination/src/converters/azure-repos/models.ts
destinations/airbyte-faros-destination/src/converters/azure-repos/users.ts

If principalName is missing, we write User Records with empty uid.
This fix ensures principalName is included in order to properly write records.

[FAI-8170] Azure Repos principalName Fix

---

destinations/airbyte-faros-destination/src/converters/asana/projects.ts
destinations/airbyte-faros-destination/test/converters/__snapshots__/asana.test.ts.snap
destinations/airbyte-faros-destination/test/converters/asana.test.ts

Because of the order of the spread and the model name, I ended up writing two identical boards instead of a board and a project with the same uid+name.
> Fix [#1]() 

Fix Asana project stream

---

faros-airbyte-cdk/src/protocol.ts
faros-airbyte-cdk/src/sources/source-base.ts
faros-airbyte-cdk/src/sources/state.ts

I made this optional instead of enforced because this is a public cdk and usually people want uncompressed state for easier inspection/debugging/modifying.
> Fix [#1]() 

FAI-8191 - Add global source option to compress state

---

destinations/airbyte-faros-destination/src/converters/faros-feeds/model_names.ts

- Added org_EmployeeTool to model names
- records will start to be written with https://github.com/faros-ai/feeds/pull/1958

FAI-8225 | added org_EmployeeTool to model names

---

destinations/airbyte-faros-destination/src/converters/github/team_memberships.ts

Remove toLower funtion when insert user on team_membership stream, because this does not match with user when is created on stream user, on stream commit, on stream pull_request, and many other. 
> Fix [#1]() 

remove toLower function when insert teamMembership relation

---

destinations/airbyte-faros-destination/src/converters/github/commits.ts
destinations/airbyte-faros-destination/src/converters/github/pull_request_commits.ts
destinations/airbyte-faros-destination/src/converters/github/releases.ts

Validate that `author` key on response from github api is not empty. This is caused when a un-named user is used as a commit author. The log error is :
` Failure reason: Failed to write vcs_Commit record with query 'mutation { insert_vcs_Commit_one (object: {uid: "COMMIT_SHA", sha: "COMMIT_SHA", message: "Release\n\n - 1.2.1", vcs_User: {data: {source: "GitHub"}, on_conflict: {constraint: vcs_User_pkey, update_columns: [source, uid]}}, createdAt: "2023-10-18T21:51:40.000Z", vcs_Repository: {data: {name: "my-repository", uid: "my-repository", vcs_Organization: {data: {uid: "my-org", source: "GitHub"}, on_conflict: {constraint: vcs_Organization_pkey, update_columns: [source, uid]}}}, on_conflict: {constraint: vcs_Repository_pkey, update_columns: [organization, uid]}}, origin: …

fix: validate commit author is not empty

---

destinations/airbyte-faros-destination/src/common/graphql-client.ts
destinations/airbyte-faros-destination/test/__snapshots__/graphql-client.test.ts.snap
destinations/airbyte-faros-destination/test/graphql-client.test.ts
destinations/airbyte-faros-destination/test/resources/hasura-schema.json

Ensure that `timestamptz` primary keys are serialized consistently going into and out of the GraphQL database.   The batch upsert algorithm relies on serialization to compare and match keys of records in memory with those inserted into the GraphQL database.
In the case that led to this change, the primary key in the imported data used local timezone (e.g. `2021-10-14T00:53:33-06:00`) and the GraphQL database returned the same as UTC (e.g. `2021-10-14T06:53:33+00:00`).  The mismatch in timezones led to an assertion in the data processing.
We fixed this by enhancing the serialization logic to consider the type of the key field.  If we encounter a `timestamptz` field we normalize to epochs ensuring that timezones are irrelevant.

FAI-8599: Fix serialization of timestamptz key

---

sources/circleci-source/resources/spec.json
sources/circleci-source/src/circleci/circleci.ts
sources/circleci-source/src/index.ts
sources/circleci-source/test/index.test.ts

Allowing Faros users to get their ignored repos from the Faros Graph by setting input vars to the configs:
"pull_blocked_repos"
"faros_api_key"
"faros_api_url"
"graph"

[FAI-8458] [FAI-8704]  For Circle CI, adding option to pull repo names from Faros Graph

---

package-lock.json
sources/sheets-source/package.json

https://nvd.nist.gov/vuln/detail/CVE-2023-30533
We could just bump to 0.19.3, but I decided to go with the latest - https://git.sheetjs.com/sheetjs/sheetjs/src/branch/master/CHANGELOG.md

CVE-2023-30533 - Update xlsx to 0.20.1

---

.github/workflows/skip-test-sources.txt
sources/files-source/bin/main
sources/files-source/package.json
sources/files-source/resources/schemas/files.json
sources/files-source/resources/spec.json
sources/files-source/src/files-reader.ts
sources/files-source/src/index.ts
sources/files-source/src/streams/files.ts
sources/files-source/src/streams/index.ts
sources/files-source/src/tsconfig.json
sources/files-source/test/__snapshots__/index.test.ts.snap
sources/files-source/test/index.test.ts
sources/files-source/test/tsconfig.json

- Added Files Source which can be used to read files. 
- Currently it supports reading JSON files from S3 given a path on a bucket, but could be extended to reading from other sources as well as supporting other file formats.
- Incremental sync support.
- Pagination handling when listing S3 objects
> Fix [#1]() 

FAI-8579 - Added Files Source with S3 support

---

sources/circleci-source/resources/spec.json
sources/circleci-source/src/circleci/circleci.ts
sources/circleci-source/src/circleci/typings.ts
sources/circleci-source/src/index.ts

Reading at this URL, we see that Circle CI have two different formats for their project names.
This PR adds support for that case:
https://circleci.com/docs/api/v2/index.html#operation/getProjectBySlug
Also adding documentation and simplified logic for reading the "OnBeforeRead" function.
Documentation in this file:
sources/circleci-source/src/index.ts
under the function 'OnBeforeRead'

FAI-8724 FAI-8855 Circle CI Handles Github- Gitlab formats when getting all projects with wildcard

---

destinations/airbyte-faros-destination/src/converters/converter-registry.ts
destinations/airbyte-faros-destination/test/converter-registry.test.ts

`'aws_cloudwatch_metrics'.replace('_', '-')` is `aws-cloudwatch_metrics`
> Fix [#1]() 

Fix loading of converter by using global replace

---

sources/circleci-source/src/circleci/circleci.ts
sources/circleci-source/src/index.ts

Project Slugs can't sync once converted to lowercase, so we only convert to lowercase to check against blocklist

CircleCI lowercase applied only to check if equal to blocklist

---

sources/aws-cloudwatch-metrics-source/resources/spec.json
sources/aws-cloudwatch-metrics-source/src/cloudwatch.ts
sources/aws-cloudwatch-metrics-source/src/streams/metrics.ts
sources/aws-cloudwatch-metrics-source/test/__snapshots__/index.test.ts.snap
sources/aws-cloudwatch-metrics-source/test/index.test.ts

Support query groups to make it possible to use [metric math](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/using-metric-math.html).
> Fix [#1]() 

FAI-8918 Support query groups

---

destinations/airbyte-faros-destination/src/converters/circleci/projects.ts
sources/circleci-source/src/streams/tests.ts

To improve runtime for Circle CI, we combine debug logs into a single log.
We also avoid duplicate writes of cicd_Organization in the destination

CircleCI Optimization: Moving logs to end of stream and avoiding duplicate writes

---

faros-airbyte-cdk/src/logger.ts
package-lock.json

Before:
```
$ npm audit
axios  0.8.1 - 1.5.1
Severity: moderate
Axios Cross-Site Request Forgery Vulnerability - https://github.com/advisories/GHSA-wf5p-g6vw-rhxx
fix available via `npm audit fix`
node_modules/analytics-node/node_modules/axios
node_modules/condoit/node_modules/axios
node_modules/google-spreadsheet/node_modules/axios
node_modules/victorops-api-client/node_modules/axios
analytics-node  >=3.1.0
Depends on vulnerable versions of axios
node_modules/analytics-node
condoit  *
Depends on vulnerable versions of axios
node_modules/condoit
google-spreadsheet  3.0.0 - 3.3.0
Depends on vulnerable versions of axios
node_modules/google-spreadsheet
victorops-api-client  *
Depends on vulnerable versions of axios
node_modules/victorops-api-client
semver  7.0.0 - 7.5.1
Severity: moderate …
```

Update vuln dependencies

---

faros-airbyte-cdk/src/protocol.ts
faros-airbyte-cdk/src/sources/source-base.ts

Allows for continuing processing of slices even if N (configurable maximum up to unlimited represented by -1) of them fail. 
We want to do as much processing as possible. If a slice fails, it seems reasonable that we would want there to be a way to attempt processing other stream slices. This way, if a slice has a transient failure, it doesn't affect the processing of other slices.

FAI-9009 - Isolate stream slice failures

---

package-lock.json
package.json

Follow up to #1305 
analytics-node depends on axios 0.27.2 even on its latest version
https://github.com/segmentio/analytics-node/blob/87d6e03cecb5f26f178f9f9b468dffe65bdbd0d3/package.json#L38

FAI-8633 Force update axios

---

faros-airbyte-cdk/src/protocol.ts
faros-airbyte-cdk/src/sources/source-base.ts

Similar to what we did for slice resiliency, this PR allows setting the number of allowed stream failures before the source process is failed. `-1` mean unlimited failures are allowed. If any stream fails, the source will fail in the end after attempting the configured allowed number.

FAI-9368 - Configurable stream failure resiliency

---

destinations/airbyte-faros-destination/src/converters/asana/tasks.ts
destinations/airbyte-faros-destination/test/converters/__snapshots__/asana.test.ts.snap
destinations/airbyte-faros-destination/test/converters/asana.test.ts
sources/asana-source/src/asana.ts

Import the `completed_at` field in Asana tasks and save its value in `tms_Task:resolvedAt`
Based on https://developers.asana.com/reference/tasks this field should be available

Add Asana tasks `completed_at` field import

---

package-lock.json
sources/azurepipeline-source/package.json
sources/azurepipeline-source/resources/spec.json
sources/azurepipeline-source/src/azurepipeline.ts
sources/azurepipeline-source/src/index.ts
sources/azurepipeline-source/src/streams/builds.ts
sources/azurepipeline-source/src/streams/pipelines.ts
sources/azurepipeline-source/src/streams/releases.ts

Internally handle failing requests to Azure DevOps APIs by retrying the failing request.
None.
No migration needed.
Azure's APIs might never return as what it seems to be a rate-limiting / anti-DDOS mechanism. 
I could observe this behavior only when Airbyte was deployed on Kubernetes, never locally. It was preventing our sources to be imported 100% of the cases.
Users who are not experiencing this issue _should not_ have any impact on their imports.
This PR introduces a new dependency.

Internally retry failing Azure DevOps Pipeline requests

---

destinations/airbyte-faros-destination/src/converters/trello/cards.ts

My change removes these changelog items from being uploaded, since I wasn't sure if theres's a way to keep them in the record.
> Fix [#1]() 

Trello converter: handle card status changelog items with no timestamp

---

sources/jira-source/src/streams/issue_pull_requests.ts
sources/jira-source/test/index.test.ts

Added streamSlice usage in the readRecords function to make use of the stream slices we are returning and parallelize runs per project.
- [ x ] Bug fix
> Fix [#1]() 

FAI-10277 - Use streamSlice for issue_pull_requests read records.

---

destinations/airbyte-faros-destination/src/converters/jira/faros_sprints.ts
destinations/airbyte-faros-destination/test/converters/jira.test.ts
destinations/airbyte-faros-destination/test/resources/jira/all-streams.log
destinations/airbyte-faros-destination/test/resources/jira/catalog.json
sources/jira-source/resources/queries/tms-sprint-board.gql
sources/jira-source/resources/schemas/farosSprintReports.json
sources/jira-source/resources/schemas/farosSprints.json
sources/jira-source/src/index.ts
sources/jira-source/src/jira.ts
sources/jira-source/src/models.ts
sources/jira-source/src/streams/faros_sprints.ts
sources/jira-source/test/__snapshots__/index.test.ts.snap
sources/jira-source/test/index.test.ts
sources/jira-source/test_files/sprints.json

Jira Sprints source stream and converter and some refactor to sprint-reports stream to remove unnecessary checks and projectKey, and also support update range for faros gql query
> Fix [#1]() 

FAI-10151 - Jira Sprints source stream and converter

---

destinations/airbyte-faros-destination/src/converters/github/workflow_runs.ts

Add `run_attempt` info for github actions builds
Depends of https://github.com/faros-ai/faros-community-edition/pull/351
> Fix [#1]() 

add run_attempt to workflow runs

---

destinations/airbyte-faros-destination/src/destination.ts

If a stream has a non-fatal error,  our source cdk outputs a source status message with state instead of a standard state message. The Faros destination should output that state data instead of ignoring it.
> Fix [#1]() 

Save incremental state from source status messages

---

.gitignore

Our dependabot PRs have started pushing their nx cache (caused by our package-lock.json reformatting step).
https://github.com/faros-ai/airbyte-connectors/pull/1434
> Fix [#1]() 

Add .nx/ to gitignore

---

sources/jira-source/src/jira.ts
sources/jira-source/src/project-board-filter.ts
sources/jira-source/src/streams/common.ts
sources/jira-source/src/streams/faros_board_issues.ts

Adds error handling for `searchForIssuesUsingJql`
Adds `ProjectBoardFilter` to encapsulate the logic that determines which projects and boards to pull (this includes a fix to make sure that boards to be pulled belong to a project being pulled as well).
> Fix [#1]() 

FAI-11028 Refactor project/board slicing + handle 400

---

package-lock.json
package.json

When override markdown to be at least 13.0.2, it turns out that was moving the version back from 14 to 13. This change intends to keep markdown at 14

Markdown override for vuln

---

destinations/airbyte-faros-destination/src/converters/circleci/tests.ts

Currently, the CircleCI converter stores all test executions it sees so that it can aggregate all of the test case result stats based off of test records it converts. This has caused issues where the destination will run out of memory. However, we can instead only worry about on test execution at a time because the source emits records related to a single test execution in order. Since we can assume that all test case results related to a test execution will be processed in order before moving onto the next test execution, we can aggregate one TestExecution at a time until we  see the first record that is from a new TestExecution at which point we send in the TestExecution and start aggregating the next. The final TestExecution needs to be sent in the onProcessComplete logic

FAI-11383: CircleCI Memory fix

---

sources/jira-source/src/jira.ts
sources/jira-source/src/project-board-filter.ts
sources/jira-source/src/streams/faros_projects.ts
sources/jira-source/test/__snapshots__/index.test.ts.snap
sources/jira-source/test/index.test.ts

- Optimize calls to only fetch the listed projects

FAI-11182: Jira source when project list is supplied only fetch those

---

faros-airbyte-common/package.json
package-lock.json
sources/jira-source/package.json
sources/jira-source/src/retry.ts
sources/jira-source/test/client.test.ts

- Upgrade to https://github.com/MrRefactoring/jira.js?tab=readme-ov-file#error-handling
- Increase base sleep to 5s instead of 3s

Jira migrate to 4.0.0 client

---

sources/jira-source/test/index.test.ts

Add test to check Jira SourceJSON schema required fields for each stream

---

sources/faros-graphdoctor-source/src/graphdoctor/timeTests.ts

distinct_on is expensive for queries. It is unnecessary in the cases where it's removed.

Removing distinct_on from queries which don't need it

---

destinations/airbyte-faros-destination/src/converters/trello/cards.ts

We need to convert the timestamp retrieved from the graph (as ISO string) to `Date` before comparison [here](https://github.com/faros-ai/airbyte-connectors/blob/b2031087e06b0650862427e4f774025a9e5ee604/destinations/airbyte-faros-destination/src/converters/trello/cards.ts#L481)
> Fix [#1]() 

Convert changedAt before comparison

---

destinations/airbyte-faros-destination/src/destination.ts
faros-airbyte-cdk/src/destinations/destination-runner.ts
faros-airbyte-cdk/src/destinations/destination.ts
faros-airbyte-cdk/src/protocol.ts
faros-airbyte-cdk/src/sources/source-base.ts
faros-airbyte-cdk/src/sources/source.ts
faros-airbyte-common/package.json
faros-airbyte-common/src/common/index.ts
faros-airbyte-common/test/common/__snapshots__/index.test.ts.snap
faros-airbyte-common/test/common/index.test.ts
sources/jira-source/resources/spec.json
sources/jira-source/src/jira.ts
sources/jira-source/src/streams/common.ts
sources/jira-source/test/index.test.ts

Adds support for backfills. When a source is configured with `backfill`, the streams state will be ignored and unmodified. The destination will NOT reset the models. This way, one can temporarily reuse a configured sync for backfill, by setting `backfill` to `true` and providing `start_date` and `end_date`. Once the backfill is completed, one can turn `backfill` off and the configured sync will continue normally from where it left off.
Also adds some utility function to deal with calculating the date range to sync based on `start_date`, `end_date` and `cutoff_days`
> Fix [#1]() 

Support backfills

---

sources/faros-graphdoctor-source/resources/spec.json
sources/faros-graphdoctor-source/src/graphdoctor/graphdoctor.ts

It seems that the data generated by the queries which are computing Z Scores and more sophisticated data aren't being used, so let's save the computing space for now.

Removing unused dataquality tests

---

sources/workday-source/resources/schemas/customreports.json

Workday schema didn't pass because it missed "properties"

FAI-11771 | Workday Schema Adding properties

---

faros-airbyte-cdk/src/sources/source-base.ts
faros-airbyte-cdk/src/sources/streams/stream-base.ts

It'd be nice to have access to the slice being processed when computing the updated state. Very frequently we need to update an object keyed by something in the slice, and the only way to do that now is to ensure that we include it in the stream output object so that we can access it from the `latestRecord`.
> Fix [#1]() 

Pass the slice being processed (if any) to getUpdatedState

---

destinations/airbyte-faros-destination/resources/spec.json
destinations/airbyte-faros-destination/src/destination.ts

This option is only meant for non-Faros sources, which don't use our expanded message protocol.
> Fix [#1]() 

FAI-12025 - Disable skip_source_success_check for Faros sources

---

sources/github-source/src/index.ts

Fix run_mode param behavior when not passed (GitHub).
If not passed keep streams passed from original catalog.

FAI-11601 | Fix run_mode param behavior when not passed (GitHub)

---

sources/jira-source/resources/queries/tms-project-boards.gql

While running the source in `WebhookSupplement` mode found this error:
"Invalid integer: faros-tasks-with-no-board-FAI","stack_trace":"VError: Invalid integer: faros-tasks-with-no-board-FAI"
When we sync `sprint_reports` stream for `WebhookSupplement` we get boards from Faros graph. If [virtual boards](https://github.com/faros-ai/airbyte-connectors/blob/4d25a2f5b389453dd093af9ac440e550918da3a1/sources/jira-source/src/streams/faros_boards.ts#L27-L32) to hold board-less tasks exist, we want to filter them as we will not associate anything to them in the graph.
The regex condition is added to get only boards that came from Jira, with a numeric uid.
> Fix [#1]() 

Filter virtual boards in Faros tms-project-boards query

---

faros-airbyte-cdk/src/sources/source-runner.ts
faros-airbyte-cdk/src/utils.ts
faros-airbyte-cdk/test/__snapshots__/utils.test.ts.snap
faros-airbyte-cdk/test/utils.test.ts

`./bin/main spec | jq`
(Last fragment of the Jira spec)
`./bin/main spec-pretty`
`./bin/main airbyte-local-cli-wizard`

FAI-11094 Make it possible to specify common config fields for all sources

---

sources/agileaccelerator-source/acceptance-test-config.yml
sources/azure-repos-source/acceptance-test-config.yml
sources/azureactivedirectory-source/acceptance-test-config.yml
sources/azurepipeline-source/acceptance-test-config.yml
sources/backlog-source/acceptance-test-config.yml
sources/bamboohr-source/acceptance-test-config.yml
sources/bitbucket-server-source/acceptance-test-config.yml
sources/bitbucket-source/acceptance-test-config.yml
sources/buildkite-source/acceptance-test-config.yml
sources/circleci-source/acceptance-test-config.yml
sources/clickup-source/acceptance-test-config.yml
sources/customer-io-source/acceptance-test-config.yml
sources/docker-source/acceptance-test-config.yml
sources/firehydrant-source/acceptance-test-config.yml
sources/gitlab-ci-source/acceptance-test-config.yml
sources/googlecalendar-source/acceptance-test-config.yml
sources/harness-source/acceptance-test-config.yml
sources/okta-source/acceptance-test-config.yml
sources/pagerduty-source/acceptance-test-config.yml
sources/semaphoreci-source/acceptance-test-config.yml
sources/shortcut-source/acceptance-test-config.yml
sources/squadcast-source/acceptance-test-config.yml
sources/statuspage-source/acceptance-test-config.yml
sources/victorops-source/acceptance-test-config.yml

The acceptance tests compare the output of the `spec` command against the contents of a file (we use `spec.json`)
These tests now fail since we're adding common properties programmatically since #1571 
We can skip those tests given that we're covered by unit tests:
1. Sources have tests that compare the source's spec output against it's spec file ([example](https://github.com/faros-ai/airbyte-connectors/blob/876e5a328526ac001561f9dd171cc4132d992a50/sources/agileaccelerator-source/test/index.test.ts#L43))
2. The cdk has a [test](https://github.com/faros-ai/airbyte-connectors/blob/876e5a328526ac001561f9dd171cc4132d992a50/faros-airbyte-cdk/test/utils.test.ts#L72) that covers the addition of the common properties.

Skip spec check in acceptance tests

---

sources/jira-source/src/project-board-filter.ts
sources/jira-source/test/__snapshots__/project-board-filter.test.ts.snap
sources/jira-source/test/project-board-filter.test.ts

Fix projects list check in project-board-filter. If `projects` is `[]` (empty array) we should sync all projects, which is the same behaviour as projects being `undefined`.
> Fix [#1]() 

Fix bug in Jira Source Project filter

---

sources/github-source/resources/spec.json
sources/github-source/src/streams/common.ts
sources/github-source/test/resources/config.json
sources/jira-source/resources/spec.json
sources/jira-source/src/streams/common.ts

Added "Custom" run mode option including ALL streams, so that Full/Standard (default) run mode can be a subset of all possible streams. When Custom is selected the stream selection is done through Airbyte stream settings.

FAI-12482 | Added "Custom" run mode option including ALL streams

---

faros-airbyte-cdk/src/sources/source-runner.ts

Noticed that my previous [PR](https://github.com/faros-ai/airbyte-connectors/pull/1633) , which uses the state, was not working. We're passing the possibly compressed state to the `onBeforeRead` function, so that's why [this](https://github.com/faros-ai/airbyte-connectors/blob/902803d196fb2e2c519819c63c7a947f447dbe71/sources/asana-source/src/index.ts#L78C43-L78C56) wouldn't work.
> Fix [#1]() 

Pass decompressed state to onBeforeRead

---

destinations/airbyte-faros-destination/src/converters/github/faros_commits.ts
sources/github-source/resources/spec.json
sources/github-source/src/github.ts
sources/github-source/src/octokit.ts
sources/github-source/src/types.ts

Dynamic page size for PRs query to avoid timeout failures on PR stream. Applied same workaround and values (page size, multipliers) from [feeds implementation](https://github.com/faros-ai/feeds/blob/2f9f1ed6b189252bd3f8fca2c6c9229aff0ce185/feeds/vcs/github-feed/src/feed.ts#L1121)

FAI-12666 | Dynamic page size for PRs query to avoid timeout failures

---

destinations/airbyte-faros-destination/src/converters/trello/cards.ts

`task.uid` and `task.source` are always missing since they're not queried for 🤦‍♂️ 
> Fix [#1]() 

FAI-12660 Fix missing task keys in Trello converter

---

sources/sheets-source/resources/spec.json
sources/sheets-source/src/sheets-reader.ts

Google sheet source support for sheet filters and first row offset (local file and S3 support would need a bigger refactor).
> Fix [#1]() 

FAI-12259 | Google sheet source support for sheet filters and first row offset

---

sources/sheets-source/src/sheets-reader.ts

Sheets source only parse private key json if it's a string

FAI-12259 | Sheets source only parse private key json if it's a string

---

destinations/airbyte-faros-destination/src/converters/asana/project_tasks.ts
destinations/airbyte-faros-destination/src/converters/asana/projects.ts
destinations/airbyte-faros-destination/src/converters/asana/tasks.ts
destinations/airbyte-faros-destination/src/converters/asana/tasks_full.ts
destinations/airbyte-faros-destination/test/converters/__snapshots__/asana.test.ts.snap
destinations/airbyte-faros-destination/test/converters/asana.test.ts
sources/asana-source/resources/spec.json
sources/asana-source/src/asana.ts
sources/asana-source/src/index.ts
sources/asana-source/src/streams/tasks_full.ts
sources/asana-source/test/__snapshots__/index.test.ts.snap
sources/asana-source/test/index.test.ts

There are cases where the project-tasks relationship is so costly that it accounts for the majority of the records pulled in a sync.
This PR introduces an optimization where, if the number of tasks pulled in a full sync is << number of records in the project-tasks relationship (always full sync), it could be more efficient to pull tasks in full sync (the tasks records would include the associated projects) VS tasks incrementally + projects(full) + project-tasks(full).
If the `optimize_fetching_projects_and_tasks_with_full_tasks_sync` is enabled, we simply remove the unwanted streams from the catalog and add `tasks_full`. A new stream (pretty much an alias) is needed so that we make sure that the destination receives the appropriate destination sync mode (`OVERWRITE`)
Another wrinkle that …

FAI-12550 Add option to always full sync tasks and skip costly project-tasks streams

---

destinations/airbyte-faros-destination/src/converters/workday/customreports.ts

Workday connector logs when there is more than one employee record per employee (employee ID determines employee), so if an employee is on two teams, this can handle it

FAI-12868 | More than one record

---

.github/workflows/dependabot-fix.yml

Reverts faros-ai/airbyte-connectors#1681
Should follow https://github.com/stefanzweifel/git-auto-commit-action?tab=readme-ov-file#signing-commits instead

Revert "Sign package-lock.json formatting commits"

---

sources/testrails-source/resources/spec.json

Set correct field type. It's currently failing on airbyte cause it expects a string and its receiving an array.
> Fix [#1]() 

Fix project_names type in TestRail source spec

---

sources/bitbucket-server-source/package.json
sources/bitbucket-server-source/src/bitbucket-server/index.ts
sources/bitbucket-server-source/test/index.test.ts

Use a stream to read PR raw diff instead of storing it into a string in memory to avoid error: "Cannot create a string longer than 0x1fffffe8 characters"
> Fix [#1]() 

FAI-11183: Process PR raw diffs as a streamed response

---

sources/example-source/test_files/spec.json

Needed after #1660 which adds a common config field to all sources specs

Update example source spec to make acceptance tests pass

---

sources/github-source/src/github.ts

Handle 4xx errors for GitHub security streams without throwing fatal error
> Fix [#1]() 

FAI-13325 FAI-13333 | Handle 4xx errors for GitHub security streams

---

destinations/airbyte-faros-destination/src/converters/asana/tasks_full.ts

In [here](https://github.com/faros-ai/airbyte-connectors/blob/3cbecfc43c42188bb2fdcb3de6f42db4d91a82ac/destinations/airbyte-faros-destination/src/destination.ts#L556) we use the stream name without any kind of prefix (origin, source). I was incorrectly marking the stream for reset using the source prefix.
> Fix [#1]() 

FAI-13343 Fix force-marking streams for reset in Asana converter

---

faros-airbyte-common/resources/common/queries/faros-vcs-repository-options.gql
faros-airbyte-common/src/common/index.ts
sources/github-source/test/org-repo-filter.test.ts

Fix repositories inclusion/exclusions query used when `use_faros_graph_repos_selection` param is true on GitHub source.
Tested locally with airbyte-cli.

FAI-13204 FAI-13424 | Fix repositories inclusion/exclusions query

---

sources/github-source/src/github.ts
sources/github-source/src/streams/faros_copilot_seats.ts

Ignore state cutoff if copilot licenses fix is disabled. This is to avoid having to run the sync 2 times after disabling the toggle because state is reset after the first sync.
Follow-up PR to https://github.com/faros-ai/airbyte-connectors/pull/1732

FAI-13447 | Ignore state cutoff if copilot licenses fix is disabled

---

sources/github-source/src/github.ts

Handle PRs gql response nested connections returning null

FAI-13370 | Handle PRs gql response nested connections returning null

---

destinations/airbyte-faros-destination/src/common/graphql-client.ts
destinations/airbyte-faros-destination/src/common/graphql-writer.ts
destinations/airbyte-faros-destination/src/converters/converter.ts
destinations/airbyte-faros-destination/src/converters/servicenow/incidents.ts
destinations/airbyte-faros-destination/src/destination.ts
destinations/airbyte-faros-destination/test/__snapshots__/graphql-client.test.ts.snap
destinations/airbyte-faros-destination/test/graphql-client.test.ts
faros-airbyte-cdk/src/sources/source-runner.ts

When using `round_robin_bucket_execution`, we must suffix the `origin` with the bucket id so that resets only operate on records written by the corresponding sync (otherwise, e.g., the sync for bucket 2 would delete the records written by the sync for bucket 1 for full refresh streams)
In addition, when running a reset sync, we need to make sure we're deleting data for the origin AND for the origins with bucket suffix (which may or may not exist)

Fix origin logic in dst for round robin syncs

---

sources/github-source/src/github.ts
sources/github-source/test/index.test.ts

Fixed GitHub actions API response iterator
Octokit is already extracting from the API response the field that's being iterated, but the inferred type from the library wasn't taking that into account
API Response example:
```
{
"total_count": 0,
"workflows": []
}
```

FAI-13247 | Fixed GitHub actions API response iterator

---

destinations/airbyte-faros-destination/src/converters/github/faros_copilot_seats.ts
destinations/airbyte-faros-destination/test/converters/__snapshots__/faros_github.test.ts.snap
package-lock.json

Populates the `recordedAt` field on `vcs_UserToolUsage` from the `emitted_at` timestamp on the source.

[FAI-13519] - GitHub Copilot usage recordedAt timestamp

---

sources/github-source/src/github.ts
sources/github-source/src/octokit.ts

Add retries for 422 error on PR files API (GitHub)
- Added custom plugin / hook because retries plugin doNotRetry parameter is fixed after initializing Octokit instance ([#1](https://github.com/octokit/plugin-retry.js/blob/e3f082e7b6dc996ca1d157b1a5c322ab708f1c84/src/error-request.ts#L10)  [#2](https://github.com/octokit/plugin-retry.js/blob/main/src/index.ts#L14))  and to avoid having to do retry logic manually.
> Fix [#1]() 

FAI-13600 | Add retries for 422 error on PR files API (GitHub)

---

sources/jira-source/src/issue_transformer.ts
sources/jira-source/test/resources/issues/issues.json

- We use the user [key for uid ](https://github.com/faros-ai/airbyte-connectors/blob/main/sources/jira-source/src/streams/faros_users.ts#L22)

FAI-13927: Fix assignees to prefer user keys

---

faros-airbyte-cdk/src/testing-tools.ts
sources/github-source/src/github.ts
sources/github-source/src/streams/faros_copilot_seats.ts
sources/github-source/src/streams/faros_copilot_usage.ts
sources/github-source/test/__snapshots__/index.test.ts.snap
sources/github-source/test/index.test.ts

Save Copilot usage state with latest date to sync records only if newer date received on the org usage response

FAI-14167 | Save Copilot usage state to sync records only if new date added

---

faros-airbyte-common/package.json

This is not a problem in this repo because the package is symlinked but it fails in other repos:
> Fix [#1]() 

Include resources in faros-airbyte-common package

---

sources/azure-repos-source/src/streams/users.ts
sources/github-source/src/streams/faros_users.ts

If a stream is incremental but doesn't specify a cursor field, the Airbyte UI does not let you update the connection catalog.
> Fix [#1]() 

FAI-14237 - Add placeholder cursor fields to pseudo-incremental streams

---

faros-airbyte-cdk/src/sources/streams/stream-base.ts

So that users of the utility function are alerted at compile time when they're using e.g., an unsupported type for cutoff.
Exporting `StreamState` since the majority of our streams use this simple shape for state.
> Fix [#1]() 

Better type for param and ret type of calculateUpdatedStreamState

---

destinations/airbyte-faros-destination/src/converters/azure-repos/models.ts
destinations/airbyte-faros-destination/src/converters/azure-repos/pull_requests.ts
destinations/airbyte-faros-destination/test/converters/__snapshots__/azure-repos.test.ts.snap

mergedAt: use mergeCommit timestamps if available and only set if a mergeCommit exists
updatedAt: use max of thread lastUpdated timestamps
diffStats: only set in record if exists
> Fix [#1]() 

Azure Repos: mergedAt, updatedAt, and diffStats logic

---

sources/github-source/src/github.ts

[Query](https://github.com/faros-ai/airbyte-connectors/blob/ccc993d874b0fc37debd00b119ba1cce8bcc7020/faros-airbyte-common/resources/github/queries/pull-request-review-requests-query.gql#L1) expects var called number instead of pull_number
> Fix [#1]() 

Fix GitHub PR review request query params

---

sources/jira-source/src/jira.ts

Fixes [https://github.com/faros-ai/airbyte-connectors/security/code-scanning/34](https://github.com/faros-ai/airbyte-connectors/security/code-scanning/34)
To fix the problem, we need to escape the `.` meta-character in the regular expression to ensure it matches a literal dot. This will make the regular expression more precise and prevent it from matching unintended hostnames. Specifically, we should replace `(.*).atlassian.net` with `(.*)\.atlassian\.net`.
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._
Note from @ypc-faros 
Previous regex would match incorrect URLs e.g., `https://x.yatlassian.net`

Fix code scanning alert no. 34: Incomplete regular expression for hostnames

---

destinations/airbyte-faros-destination/src/destination.ts
sources/github-source/test/__snapshots__/index.test.ts.snap
sources/github-source/test/index.test.ts

It's safe to persist the state even when running in backfill because we don't modify the streams' state. But we want to persist the state anyway so that we advance the bucket id when using round robin bucketing in a backfill

Always persist state (even in backfill syncs)

---

destinations/airbyte-faros-destination/src/converters/github/common.ts
destinations/airbyte-faros-destination/src/converters/github/faros_repositories.ts

Follow-up fix for https://github.com/faros-ai/airbyte-connectors/pull/1847
- Only write tms models if syncing repo data
- Add models to destination models
> Fix [#1]() 

FAI-14359 | GitHub - Only write tms models if syncing repo data

---

sources/circleci-source/src/streams/tests.ts

Didn't remove the `streamSlices` impl from the tests stream in https://github.com/faros-ai/airbyte-connectors/pull/1836
> Fix [#1]() 

FAI-14536 Fix bucketing for circleci tests stream

---

faros-airbyte-common/src/common/bucket-set.ts
faros-airbyte-common/src/common/bucketing.ts
faros-airbyte-common/src/common/index.ts
faros-airbyte-common/test/common/bucket-set.test.ts
faros-airbyte-common/test/common/bucketing.test.ts
sources/bitbucket-source/resources/spec.json
sources/bitbucket-source/src/bitbucket.ts
sources/bitbucket-source/src/types.ts
sources/circleci-source/resources/spec.json
sources/circleci-source/src/circleci/circleci.ts
sources/github-source/resources/spec.json
sources/github-source/src/github.ts
sources/github-source/src/types.ts
sources/jira-source/resources/spec.json
sources/jira-source/src/jira.ts

Configured to sync buckets `3-5` and `7` => `[3, 4, 5, 7]`
First sync => 3
Second sync => 4
Third sync => 5
Fourth sync => 7
Fifth sync => 3

FAI-14477 Make it possible for a source to handle a range of buckets

---

sources/github-source/resources/spec.json
sources/github-source/src/github.ts
sources/github-source/src/types.ts
sources/github-source/test/index.test.ts

Use copilot metrics GA API by default instead of the preview API (announced to be shutdown by end of January)

FAI-14659 | GitHub - use copilot metrics GA API by default

---

sources/github-source/src/github.ts

GraphQL paginate plugin for octokit has a crashing bug when processing a response with nulls / undefined that's returned by the API instead of a proper response with empty nodes.
Updated code to handle pagination manually.
> Fix [#1]() 

FAI-14886 | GitHub - Fix SAML SSO error when processing gql paginated response

---

sources/faros-graphql-source/src/streams/faros-graph.ts

Refactor introduced a bug.  The first boolean used to be `avoidCollisions` not `scalarsOnly`

FAI-14934: Fix regression in graph source

---

destinations/airbyte-faros-destination/src/converters/converter.ts
destinations/airbyte-faros-destination/src/converters/wolken/configuration_items.ts
destinations/airbyte-faros-destination/src/destination.ts

This helps with memory usage. For example, for Wolken, the [dependent stream](https://github.com/faros-ai/airbyte-connectors/blob/0d3c38c8f0e7c287d26d434e9882297e9e623c4a/destinations/airbyte-faros-destination/src/converters/wolken/incidents.ts#L133) only really needs the `serviceIdFlexField` from the input `ConfigurationItem`
> Fix [#1]() 

Make it possible to store compact representation of input record in ctx for dependent streams

---

sources/azure-workitems-source/resources/spec.json
sources/azure-workitems-source/src/azure-workitems.ts
sources/azure-workitems-source/src/index.ts
sources/azure-workitems-source/test/__snapshots__/index.test.ts.snap
sources/azure-workitems-source/test/index.test.ts
sources/azurepipeline-source/resources/spec.json
sources/azurepipeline-source/src/azurepipeline.ts

- Add support for Azure server urls

FAI-14966: Add support for Azure server urls

---

destinations/airbyte-faros-destination/src/destination.ts

Treat the mock data feed syncs as a special case wrt model resets
Discussion here: https://faros-ai.slack.com/archives/C05LXTGRHK6/p1736530200559179
> Fix [#1]() 

FAI-14708 Mock data feed should reset models BEFORE writing new records

---

destinations/airbyte-faros-destination/src/destination.ts

Fixes `Cannot access 'isResetSync' before initialization`
It's safe to assume `isResetSync => false` since the [definition](https://github.com/faros-ai/airbyte-connectors/blob/fc9f84feb3be6109b513ba9c59ad27dd7ec55d1d/destinations/airbyte-faros-destination/src/destination.ts#L949) has `!sourceConfigReceived` as one of its conditions. And `sourceConfigReceived` is set to `true` in the same [code path](https://github.com/faros-ai/airbyte-connectors/blob/fc9f84feb3be6109b513ba9c59ad27dd7ec55d1d/destinations/airbyte-faros-destination/src/destination.ts#L814).
> Fix [#1]() 

FAI-14708 Fix initialization bug

---

sources/circleci-source/src/circleci/circleci.ts
sources/circleci-source/src/index.ts
sources/circleci-source/src/streams/common.ts
sources/circleci-source/src/streams/pipelines.ts
sources/circleci-source/src/streams/projects.ts
sources/circleci-source/src/streams/tests.ts

The `CircleCI` singleton is created in [onBeforeRead](https://github.com/faros-ai/airbyte-connectors/blob/514d989c4ff01f0188b6beb3e165d2cff13e3b2d/sources/circleci-source/src/index.ts#L57) and it has the [bucketId and bucketTotal](https://github.com/faros-ai/airbyte-connectors/blob/main/sources/circleci-source/src/circleci/circleci.ts#L45-L46) as instance variables. So they're never updated (because of the singleton behavior) hence we only process the same bucket every time.
This PR moves the bucketing related vars out of the `CircleCI` class to avoid this issue.
> Fix [#1]() 

FAI-15078 Fix circleci bucketing

---

sources/circleci-source/src/circleci/circleci.ts

In the circleci source, we [cache](https://github.com/faros-ai/airbyte-connectors/blob/352c2f37d53592c73e8cd0900e898511c2cba7a9/sources/circleci-source/src/circleci/circleci.ts#L345) the workflows for (pipelineId, since). This cached data is only used if the `since` lines up between streams (pipelines and tests). Otherwise we’re wasting memory without any benefit.
I think we should:
(This PR)
Remove the memoization from the source to try to resolve the OOM.
(Next steps)
Fix the caching issues by: fusing the pipelines and tests streams OR changing the logic to improve the odds of a cache hit.
> Fix [#1]() 

FAI-15182 Address memory usage issues in circleci source

---

destinations/airbyte-faros-destination/src/converters/github/faros_pull_requests.ts

Handle possible null requested reviewer on GitHub pull requests
Based on [GitHub gql schema](https://docs.github.com/en/graphql/reference/objects#reviewrequest), requestedReviewer is nullable and we experienced null read errors because of this. Haven't found a reason, documentation or proof on why this would happen (maybe the referenced user was deleted from the GitHub instance?)
> Fix [#1]() 

FAI-15197 | Handle possible null requested reviewer on GitHub pull requests

---

destinations/airbyte-faros-destination/src/converters/jira/faros_issues.ts
destinations/airbyte-faros-destination/test/converters/__snapshots__/faros_jira.test.ts.snap

Deletes all taskTags, flushes and writes current ones. Same strategy as task dependencies.
> Fix [#1]() 

FAI-15510: Make task labels consistent with Jira

---

destinations/airbyte-faros-destination/package.json
package-lock.json

This client update has a fix where we will only delete models that match the initial deletion criteria.

FAI-15611 - Bump faros-js-client to v0.6.3

---

sources/files-source/resources/schemas/files.json
sources/files-source/resources/spec.json
sources/files-source/src/files-reader.ts
sources/files-source/src/streams/files.ts
sources/files-source/test/__snapshots__/index.test.ts.snap
sources/files-source/test/index.test.ts

- Files source support for reading S3 files in chunks
- Allow filtering and provide order to read specific files
> Fix [#1]() 

FAI-15199 | Files source support for reading S3 files in chunks

---

sources/jenkins-source/src/jenkins.ts

Fix this since [upgrade to client version](https://github.com/faros-ai/airbyte-connectors/pull/1954)
```
Class constructor Jenkins cannot be invoked without 'new' Stack Trace: TypeError: Class constructor Jenkins cannot be invoked without 'new' at Jenkins.instance
```

FAI-16074: Fix jenkins class constructor initialization

---

.github/workflows/release.yml
faros-airbyte-cdk/package.json

[airbyte-faros-destination](https://www.npmjs.com/package/airbyte-faros-destination/v/0.11.0?activeTab=code) and [faros-airbyte-common](https://www.npmjs.com/package/faros-airbyte-common/v/0.14.1?activeTab=code) packages have been missing their code on their npm packages since [0.11.0](https://github.com/faros-ai/airbyte-connectors/compare/v0.10.87...v0.11.0) and [0.14.1](https://github.com/faros-ai/airbyte-connectors/compare/v0.14.0...v0.14.1) respectively. On those releases prepare script was removed on their packages to avoid dependency errors on npm install. As a result the release workflow doesn't build those packages on install.

Fix Faros destination and common packages release

---

faros-airbyte-common/src/azure-devops/azure-devops.ts
faros-airbyte-common/src/azure-devops/types.ts
faros-airbyte-common/test/azure-devops/azure-devops.test.ts
sources/azure-repos-source/src/azure-repos.ts
sources/azure-repos-source/test/index.test.ts
sources/azure-workitems-source/src/azure-workitems.ts
sources/azure-workitems-source/test/index.test.ts
sources/azurepipeline-source/test/index.test.ts

- AzureDevOps add support for generic REST api to fallback when the client azure-devops-node-api doesn't work as expected, e.g. for listRuns for AzureDevOp Server 2020.
- Follow-up PR to use rest to azurepipeline-source

FAI-16059: AzureDevOps add support for generic REST API

---

destinations/airbyte-faros-destination/src/converters/workday/README.md
destinations/airbyte-faros-destination/src/converters/workday/customreports.ts
destinations/airbyte-faros-destination/src/converters/workday/models.ts

Adds org_EmployeeTag matching employee to vendor - if vendor is provided by Workday.
Can potentially filter them by an input or by some other method-

FAI-16144 | Workday allows to add Employee Tag for Vendor

---

sources/github-source/src/octokit.ts

`stack_trace` is a string in the Airbyte protocol [1](https://github.com/airbytehq/airbyte-protocol/blob/75443bd525c63faf814f4eee080cca1132bc0414/protocol-models/src/main/resources/airbyte_protocol/airbyte_protocol.yaml#L240) [2](https://github.com/faros-ai/airbyte-connectors/blob/b6f5dab728ee7a8fb0f69b17ede656e7f8b6a15c/faros-airbyte-cdk/src/protocol.ts#L153)
We were passing an object and that was making the deserializer throw here: [1](https://github.com/airbytehq/airbyte-platform/blob/34a31e95f54d83dd544b79611218ce9549efe416/airbyte-commons-worker/src/main/java/io/airbyte/workers/internal/VersionedAirbyteStreamFactory.java#L328) [2](https://github.com/airbytehq/airbyte-platform/blob/34a31e95f54d83dd544b79611218ce9549efe416/airbyte-commons/src/main/java/io/airbyte/commons/json/Jsons.java …

FAI-16116 Stringify additionalInfo

---

destinations/airbyte-faros-destination/src/converters/faros-org-import/teams.ts

Looking at existing code, it looks like this is the correct way to get the origin in the context of a converter?

FAI-16627 - Use getOrigin() method

---

destinations/airbyte-faros-destination/src/converters/faros-org-import/employees.ts

Allow processing of duplicate employee records so that multiple team and user information can be passed across multiple rows. Employee information will only be processed for the first record that is seen for each `employeeId`.

FAI-16813 - faros-org-import to allow processing duplicate employee rows

---

Dockerfile
package-lock.json
sources/github-source/package.json

Reverts faros-ai/airbyte-connectors#2070
The optimization makes each connector build have a different build context (`COPY ./sources/github-source` vs `COPY ./sources/jira-source`), so Docker can't reuse layers between different connectors like it could before when all connectors shared the same `COPY ./sources ./sources` instruction. This turns ~50
fast cached builds into ~50 slow fresh builds, causing the 20-minute timeout.

Revert "Optimize Docker build for selective connector copying"
