faros-ai/airbyte-connectors

cdk/package.json
destinations/faros-destination/package.json
destinations/faros-destination/src/converters/converter.ts
destinations/faros-destination/src/converters/github/assignees.ts
destinations/faros-destination/src/converters/github/collaborators.ts
destinations/faros-destination/src/converters/github/commits.ts
destinations/faros-destination/src/converters/github/pull-requests.ts
destinations/faros-destination/src/converters/jsonata.ts
destinations/faros-destination/src/index.ts
destinations/faros-destination/test/index.test.ts
sources/example-source/package.json
sources/example-source/src/index.ts
sources/example-source/src/stream.ts

Rename cdk to faros-airbyte-cdk

---

cdk/README.md
cdk/package.json

CDK package changes

---

cdk/README.md
cdk/package.json
destinations/faros-destination/package.json
lerna.json
sources/example-source/package.json

Add cdk package info

---

.github/workflows/release.yml

Added npm install + update path

---

.github/workflows/release.yml

Fix docker arg

---

.github/workflows/release.yml
cdk/package.json

Added registry-url

---

destinations/faros-destination/src/converters/github/branches.ts
destinations/faros-destination/src/converters/github/collaborators.ts
destinations/faros-destination/src/converters/github/comments.ts
destinations/faros-destination/src/converters/github/commit-comments.ts
destinations/faros-destination/src/converters/github/commits.ts
destinations/faros-destination/src/converters/github/common.ts
destinations/faros-destination/src/converters/github/events.ts
destinations/faros-destination/src/converters/github/issue-events.ts
destinations/faros-destination/src/converters/github/issue-labels.ts
destinations/faros-destination/src/converters/github/issue-milestones.ts
destinations/faros-destination/src/converters/github/issues.ts
destinations/faros-destination/src/converters/github/organizations.ts
destinations/faros-destination/src/converters/github/projects.ts
destinations/faros-destination/src/converters/github/pull-request-stats.ts
destinations/faros-destination/src/converters/github/pull-requests.ts
destinations/faros-destination/src/converters/github/releases.ts
destinations/faros-destination/src/converters/github/repositories.ts
destinations/faros-destination/src/converters/github/review-comments.ts
destinations/faros-destination/src/converters/github/reviews.ts
destinations/faros-destination/src/converters/github/stargazers.ts
destinations/faros-destination/src/converters/github/tags.ts
destinations/faros-destination/src/converters/github/teams.ts
destinations/faros-destination/src/converters/github/users.ts
destinations/faros-destination/src/converters/index.ts
destinations/faros-destination/src/index.ts
destinations/faros-destination/test/converters/github.test.ts
package-lock.json
package.json
sources/example-source/src/index.ts

More Github converters for Faros destination

More Github converters for Faros destination

---

.github/workflows/ci.yml

Skip acceptance tests for PRs

---

destinations/faros-destination/package.json
destinations/faros-destination/src/converters/github/pull-request-stats.ts
faros-airbyte-cdk/package.json
lerna.json
sources/example-source/package.json

Fix PR update converted record

Fix PR update converted record

---

destinations/faros-destination/resources/spec.json

Update Faros destination specs

Update Faros destination specs

---

destinations/faros-destination/package.json
faros-airbyte-cdk/package.json
faros-airbyte-cdk/src/logger.ts
faros-airbyte-cdk/src/protocol.ts
lerna.json
sources/example-source/package.json

Consider LOG_LEVEL env var in Airbyte logger + apply logging level on log messages (i.e with type `AirbyteMessageType.LOG`)

Consider LOG_LEVEL env var in Airbyte logger + apply logging level on log messages

---

destinations/faros-destination/package.json
destinations/faros-destination/resources/spec.json
faros-airbyte-cdk/package.json
lerna.json
sources/example-source/package.json

Update Faros destination spec + bump version

Update Faros destination spec + bump version

---

destinations/faros-destination/package.json
destinations/faros-destination/resources/spec.json
destinations/faros-destination/src/converters/github/commit_comment_reactions.ts
destinations/faros-destination/src/converters/github/issue_comment_reactions.ts
destinations/faros-destination/src/converters/github/issue_reactions.ts
destinations/faros-destination/src/converters/github/pull_request_comment_reactions.ts
faros-airbyte-cdk/package.json
lerna.json
sources/example-source/package.json

Added GitHub converter stubs + sync modes - https://docs.airbyte.io/connector-development/tutorials/building-a-python-destination#step-3-implement-spec

Added GitHub converter stubs + added sync modes

---

destinations/faros-destination/package.json
destinations/faros-destination/src/index.ts
faros-airbyte-cdk/package.json
faros-airbyte-cdk/src/destinations/destination-runner.ts
faros-airbyte-cdk/src/sources/source-base.ts
lerna.json
sources/example-source/package.json

Fix build for newer Typescript compiler (fixes - https://github.com/faros-ai/airbyte-connectors/issues/71)

Fix build for newer Typescript compiler

---

destinations/faros-destination/package.json
destinations/faros-destination/src/converters/github/commits.ts
destinations/faros-destination/test/converters/github.test.ts
faros-airbyte-cdk/package.json
lerna.json
sources/example-source/package.json

Add branch-commit association for GitHub commits converter

FAI-439 - Add branch-commit association for GitHub commits converter

---

package-lock.json
package.json

`LOG_LEVEL=debug lerna run test --scope faros-destination` fails to run, this comes to fix it

Bump pino-pretty dependency

---

destinations/faros-destination/src/converters/jira/issues.ts
destinations/faros-destination/src/converters/jira/sprints.ts

Use lodash to replace some boilerplate code that fetches dependency records for some Jira streams.
> Fix [#1]() 

Refactor Jira converter logic

---

destinations/faros-destination/package.json
faros-airbyte-cdk/package.json
lerna.json
sources/customer-io-source/package.json
sources/example-source/package.json
sources/harness-source/package.json
sources/jenkins-source/package.json
sources/pagerduty-source/package.json
sources/phabricator-source/package.json
sources/statuspage-source/package.json
sources/victorops-source/package.json

Bump version to 0.1.24

---

destinations/faros-destination/package.json
destinations/faros-destination/src/converters/jira/issues.ts
faros-airbyte-cdk/package.json
lerna.json
package-lock.json
sources/customer-io-source/package.json
sources/example-source/package.json
sources/harness-source/package.json
sources/jenkins-source/package.json
sources/pagerduty-source/package.json
sources/phabricator-source/package.json
sources/squadcast-source/package.json
sources/statuspage-source/package.json
sources/victorops-source/package.json

Fix missing field error and bump version

---

destinations/faros-destination/package.json
destinations/faros-destination/src/converters/statuspage/common.ts
destinations/faros-destination/src/converters/statuspage/incident_updates.ts
destinations/faros-destination/src/converters/statuspage/incidents.ts

Remove StatusPage dependency from Faros-destination

---

sources/googlecalendar-source/README.md

> Update README.md file
> Fix [#1]() 

Update Google Calendar

---

destinations/faros-destination/src/converters/okta/groups.ts
sources/okta-source/package.json

Fix writing user of group from okta.
Remove writing of arbitrary team lead.
> Fix [#1]() 

Fix writing user of group from okta

---

.github/workflows/ci.yml
destinations/faros-destination/package.json
faros-airbyte-cdk/package.json
lerna.json
sources/agileaccelerator-source/package.json
sources/bitbucket-source/package.json
sources/customer-io-source/package.json
sources/example-source/package.json
sources/googlecalendar-source/package.json
sources/harness-source/package.json
sources/jenkins-source/package.json
sources/okta-source/package.json
sources/pagerduty-source/package.json
sources/phabricator-source/package.json
sources/squadcast-source/package.json
sources/statuspage-source/package.json
sources/victorops-source/package.json

Bump version and disable harness SAT pending investigation

---

destinations/faros-destination/package.json
destinations/faros-destination/src/community/hasura-client.ts
destinations/faros-destination/src/community/types.ts
destinations/faros-destination/src/converters/github/pull_requests.ts
destinations/faros-destination/src/converters/jira/epics.ts
destinations/faros-destination/src/converters/jira/issues.ts
destinations/faros-destination/src/index.ts
faros-airbyte-cdk/package.json
lerna.json
sources/agileaccelerator-source/package.json
sources/bitbucket-source/package.json
sources/customer-io-source/package.json
sources/example-source/package.json
sources/googlecalendar-source/package.json
sources/harness-source/package.json
sources/jenkins-source/package.json
sources/okta-source/package.json
sources/pagerduty-source/package.json
sources/phabricator-source/package.json
sources/squadcast-source/package.json
sources/statuspage-source/package.json
sources/victorops-source/package.json

Community edition: handle special mutation types

---

package-lock.json

Fix dep vuln

---

destinations/faros-destination/package.json
destinations/faros-destination/resources/spec.json
destinations/faros-destination/src/index.ts
package-lock.json
package.json

Added a segment_user_id field under the Community edition configuration. If specified, it will be used to track the write stats with Segment.
If no segment user id is specified we just not track the stats.

Adds Segment tracking support to Community Edition

---

destinations/faros-destination/package.json

Bump version to release latest changes

Bump faros-destination version

---

destinations/faros-destination/package.json
destinations/faros-destination/resources/spec.json
destinations/faros-destination/src/converters/converter.ts
destinations/faros-destination/src/index.ts
package-lock.json

Make origin optional

---

destinations/faros-destination/package.json
destinations/faros-destination/src/community/hasura-writer.ts
package-lock.json

Add origin to timestamped records

---

destinations/faros-destination/package.json
destinations/faros-destination/resources/spec.json
destinations/faros-destination/src/index.ts
destinations/faros-destination/test/index.test.ts
destinations/faros-destination/test/testing-tools.ts
package-lock.json
package.json

This makes Airbyte 
> Fix [#1]() 

Force segment user id to be a uuid

---

Dockerfile
destinations/faros-destination/package.json
destinations/faros-destination/src/community/hasura-client.ts
destinations/faros-destination/src/converters/jira/issues.ts
package-lock.json
package.json

Fix Jira status changelog and convert Date objects to milliseconds for CE

---

destinations/faros-destination/package.json
destinations/faros-destination/src/index.ts

https://segment.com/docs/connections/sources/catalog/libraries/server/node/#track

Pass stats in Segment event properties

---

destinations/faros-destination/package.json
destinations/faros-destination/src/index.ts

Flush stats

---

faros-airbyte-cdk/package.json
lerna.json
sources/agileaccelerator-source/package.json
sources/bitbucket-source/package.json
sources/customer-io-source/package.json
sources/example-source/package.json
sources/googlecalendar-source/package.json
sources/harness-source/package.json
sources/jenkins-source/package.json
sources/okta-source/package.json
sources/pagerduty-source/package.json
sources/phabricator-source/package.json
sources/squadcast-source/package.json
sources/statuspage-source/package.json
sources/victorops-source/package.json

Hoping to fix the release on the CDK

Bump all versions to 0.1.35

---

faros-airbyte-cdk/package.json
lerna.json
sources/agileaccelerator-source/package.json
sources/bitbucket-source/package.json
sources/customer-io-source/package.json
sources/example-source/package.json
sources/googlecalendar-source/package.json
sources/harness-source/package.json
sources/jenkins-source/package.json
sources/okta-source/package.json
sources/pagerduty-source/package.json
sources/phabricator-source/package.json
sources/squadcast-source/package.json
sources/statuspage-source/package.json
sources/victorops-source/package.json

Bump version

---

.github/workflows/ci.yml

Enable running source acceptance tests manually

---

destinations/faros-destination/src/index.ts

Await for write stats event to be send + catch error

Await for write stats event to be send + catch error

---

destinations/faros-destination/package.json
package-lock.json
sources/datadog-source/package.json

Update faros-airbyte-cdk version

---

destinations/faros-destination/package.json
faros-airbyte-cdk/package.json
lerna.json
sources/agileaccelerator-source/package.json
sources/bitbucket-source/package.json
sources/customer-io-source/package.json
sources/datadog-source/package.json
sources/datadog-source/resources/spec.json
sources/datadog-source/src/datadog.ts
sources/datadog-source/test/index.test.ts
sources/example-source/package.json
sources/googlecalendar-source/package.json
sources/harness-source/package.json
sources/jenkins-source/package.json
sources/okta-source/package.json
sources/pagerduty-source/package.json
sources/phabricator-source/package.json
sources/squadcast-source/package.json
sources/statuspage-source/package.json
sources/victorops-source/package.json

Config also needs to reflect the variable rename.

Datadog variable name fix

---

.github/workflows/ci.yml

Increase CI timeout to 20 mins

Increase CI timeout to 20 mins

---

package-lock.json
sources/bitbucket-source/acceptance-test-config.yml
sources/bitbucket-source/package.json
sources/bitbucket-source/resources/schemas/pull_request_activities.json
sources/bitbucket-source/resources/spec.json
sources/bitbucket-source/src/bitbucket/bitbucket.ts
sources/bitbucket-source/src/bitbucket/types.ts
sources/bitbucket-source/src/index.ts
sources/bitbucket-source/src/streams/pipeline_steps.ts
sources/bitbucket-source/src/streams/pipelines.ts
sources/bitbucket-source/src/streams/pull_request_activities.ts
sources/bitbucket-source/src/streams/pull_requests.ts
sources/bitbucket-source/src/tsconfig.json
sources/bitbucket-source/test/index.test.ts
sources/bitbucket-source/test/tsconfig.json
sources/bitbucket-source/test_files/abnormal_state.json
sources/bitbucket-source/test_files/config.json
sources/bitbucket-source/test_files/full_configured_catalog.json
sources/bitbucket-source/test_files/incremental_configured_catalog.json

- PipelineSteps and PullRequestActivities streams use the results of Pipeline and PullRequest streams respectively to determine their stream slices.
- PullRequestActivities stream supports incremental mode.
> Fix [#1]() 

Fix bitbucket source

---

destinations/faros-destination/package.json
destinations/faros-destination/src/converters/datadog/incidents.ts
faros-airbyte-cdk/package.json
lerna.json
sources/agileaccelerator-source/package.json
sources/backlog-source/package.json
sources/bitbucket-source/package.json
sources/customer-io-source/package.json
sources/datadog-source/package.json
sources/docker-source/package.json
sources/example-source/package.json
sources/googlecalendar-source/package.json
sources/harness-source/package.json
sources/jenkins-source/package.json
sources/okta-source/package.json
sources/pagerduty-source/package.json
sources/phabricator-source/package.json
sources/shortcut-source/package.json
sources/squadcast-source/package.json
sources/statuspage-source/package.json
sources/victorops-source/package.json

`detected` is not equivalent to `acknowledgedAt`.

Fix Datadog timestamp mapping

---

destinations/airbyte-faros-destination/package.json
destinations/airbyte-faros-destination/resources/spec.json
destinations/airbyte-faros-destination/src/community/hasura-client.ts
destinations/airbyte-faros-destination/src/destination.ts
faros-airbyte-cdk/package.json
lerna.json
sources/agileaccelerator-source/package.json
sources/backlog-source/package.json
sources/bitbucket-source/package.json
sources/customer-io-source/package.json
sources/datadog-source/package.json
sources/docker-source/package.json
sources/example-source/package.json
sources/googlecalendar-source/package.json
sources/harness-source/package.json
sources/jenkins-source/package.json
sources/okta-source/package.json
sources/pagerduty-source/package.json
sources/phabricator-source/package.json
sources/shortcut-source/package.json
sources/squadcast-source/package.json
sources/statuspage-source/package.json
sources/victorops-source/package.json

Accepts an optional Hasura admin-secret and sets the header in the Hasura client if present.

Accept Hasura admin secret

---

destinations/airbyte-faros-destination/package.json
destinations/airbyte-faros-destination/src/converters/converter.ts
destinations/airbyte-faros-destination/src/destination.ts
faros-airbyte-cdk/package.json
lerna.json
sources/agileaccelerator-source/package.json
sources/backlog-source/package.json
sources/bitbucket-source/package.json
sources/customer-io-source/package.json
sources/datadog-source/package.json
sources/docker-source/package.json
sources/example-source/package.json
sources/firehydrant-source/package.json
sources/googlecalendar-source/package.json
sources/harness-source/package.json
sources/jenkins-source/package.json
sources/okta-source/package.json
sources/pagerduty-source/package.json
sources/phabricator-source/package.json
sources/shortcut-source/package.json
sources/squadcast-source/package.json
sources/statuspage-source/package.json
sources/victorops-source/package.json

Adds AirbyteLogger to StreamContext

Add AirbyteLogger to stream ctx

---

destinations/airbyte-faros-destination/package.json
destinations/airbyte-faros-destination/resources/spec.json
faros-airbyte-cdk/package.json
lerna.json
sources/agileaccelerator-source/package.json
sources/backlog-source/package.json
sources/bitbucket-source/package.json
sources/customer-io-source/package.json
sources/datadog-source/package.json
sources/docker-source/package.json
sources/example-source/package.json
sources/firehydrant-source/package.json
sources/googlecalendar-source/package.json
sources/harness-source/package.json
sources/jenkins-source/package.json
sources/okta-source/package.json
sources/pagerduty-source/package.json
sources/phabricator-source/package.json
sources/shortcut-source/package.json
sources/squadcast-source/package.json
sources/statuspage-source/package.json
sources/victorops-source/package.json

Hides the Hasura admin secret in the destination settings.

Hide the Hasura admin secret in the Airbyte UI

---

destinations/airbyte-faros-destination/src/converters/bitbucket/issues.ts
destinations/airbyte-faros-destination/test/converters/bitbucket.test.ts

Bitbucket- link issues to a tms_Project, tms_TaskBoard

---

destinations/airbyte-faros-destination/package.json
destinations/airbyte-faros-destination/src/destination.ts
faros-airbyte-cdk/package.json
lerna.json
sources/agileaccelerator-source/package.json
sources/azureactivedirectory-source/package.json
sources/backlog-source/package.json
sources/bitbucket-source/package.json
sources/customer-io-source/package.json
sources/datadog-source/package.json
sources/docker-source/package.json
sources/example-source/package.json
sources/firehydrant-source/package.json
sources/googlecalendar-source/package.json
sources/harness-source/package.json
sources/jenkins-source/package.json
sources/okta-source/package.json
sources/pagerduty-source/package.json
sources/phabricator-source/package.json
sources/shortcut-source/package.json
sources/squadcast-source/package.json
sources/statuspage-source/package.json
sources/victorops-source/package.json

Faros Destination: Only output final state message

---

package-lock.json
sources/bitbucket-source/package.json
sources/bitbucket-source/src/bitbucket/bitbucket.ts
sources/customer-io-source/src/customer-io/customer-io.ts
sources/harness-source/src/harness.ts

Fix date bugs

---

destinations/airbyte-faros-destination/package.json
faros-airbyte-cdk/package.json
lerna.json
package-lock.json
sources/agileaccelerator-source/package.json
sources/azureactivedirectory-source/package.json
sources/backlog-source/package.json
sources/bitbucket-source/package.json
sources/customer-io-source/package.json
sources/datadog-source/package.json
sources/docker-source/package.json
sources/docker-source/resources/spec.json
sources/example-source/package.json
sources/firehydrant-source/package.json
sources/firehydrant-source/resources/spec.json
sources/googlecalendar-source/package.json
sources/harness-source/package.json
sources/jenkins-source/package.json
sources/okta-source/package.json
sources/pagerduty-source/package.json
sources/phabricator-source/package.json
sources/shortcut-source/package.json
sources/squadcast-source/package.json
sources/squadcast-source/resources/spec.json
sources/squadcast-source/src/squadcast.ts
sources/squadcast-source/test/index.test.ts
sources/statuspage-source/package.json
sources/victorops-source/package.json

https://github.com/faros-ai/airbyte-connectors/issues/375
> Fix https://github.com/faros-ai/airbyte-connectors/issues/375 

Squadcast: Make content length configurable

---

sources/agileaccelerator-source/resources/spec.json
sources/azureactivedirectory-source/resources/spec.json
sources/backlog-source/resources/spec.json
sources/customer-io-source/resources/spec.json
sources/docker-source/resources/spec.json
sources/firehydrant-source/resources/spec.json
sources/googlecalendar-source/resources/spec.json
sources/harness-source/resources/spec.json
sources/jenkins-source/resources/spec.json
sources/okta-source/resources/spec.json
sources/pagerduty-source/resources/spec.json
sources/phabricator-source/resources/spec.json
sources/shortcut-source/resources/spec.json
sources/statuspage-source/resources/spec.json
sources/victorops-source/resources/spec.json

- [ #368] New feature
> Fix [#368]() 

Add descriptions for all the fields in the spec.json files that don’t currently have descriptions

---

.github/workflows/release.yml

Use major version only for other steps

---

destinations/airbyte-faros-destination/package.json
destinations/airbyte-faros-destination/src/converters/datadog/incidents.ts
destinations/airbyte-faros-destination/src/converters/victorops/incidents.ts
destinations/airbyte-faros-destination/test/converters/datadog.test.ts
destinations/airbyte-faros-destination/test/converters/victorops.test.ts
faros-airbyte-cdk/package.json
lerna.json
sources/agileaccelerator-source/package.json
sources/azureactivedirectory-source/package.json
sources/azurepipeline-source/package.json
sources/backlog-source/package.json
sources/bitbucket-source/package.json
sources/customer-io-source/package.json
sources/datadog-source/package.json
sources/docker-source/package.json
sources/example-source/package.json
sources/firehydrant-source/package.json
sources/googlecalendar-source/package.json
sources/harness-source/package.json
sources/jenkins-source/package.json
sources/okta-source/package.json
sources/pagerduty-source/package.json
sources/phabricator-source/package.json
sources/shortcut-source/package.json
sources/squadcast-source/package.json
sources/statuspage-source/package.json
sources/victorops-source/package.json

Destination: Create application from VictorOps incident

---

destinations/airbyte-faros-destination/package.json
faros-airbyte-cdk/package.json
lerna.json
sources/agileaccelerator-source/package.json
sources/azureactivedirectory-source/package.json
sources/azurepipeline-source/package.json
sources/backlog-source/package.json
sources/bitbucket-source/package.json
sources/customer-io-source/package.json
sources/datadog-source/package.json
sources/datadog-source/src/datadog.ts
sources/docker-source/package.json
sources/example-source/package.json
sources/firehydrant-source/package.json
sources/firehydrant-source/resources/spec.json
sources/googlecalendar-source/package.json
sources/harness-source/package.json
sources/jenkins-source/package.json
sources/okta-source/package.json
sources/pagerduty-source/package.json
sources/phabricator-source/package.json
sources/shortcut-source/package.json
sources/shortcut-source/resources/spec.json
sources/squadcast-source/package.json
sources/statuspage-source/package.json
sources/victorops-source/package.json

Datadog: handle 404 error when account doesn't have incidents enabled
Use json schema draft-07 for all specs
> Fix [#1]() 

Datadog and source spec fixes

---

destinations/airbyte-faros-destination/package.json
package-lock.json

Update async package and fix bootstrap warning

---

sources/buildkite-source/src/buildkite/buildkite.ts

Increase buildkite api timeout to 15s

---

destinations/airbyte-faros-destination/package.json
faros-airbyte-cdk/package.json
lerna.json
sources/agileaccelerator-source/package.json
sources/azureactivedirectory-source/package.json
sources/azurepipeline-source/package.json
sources/backlog-source/package.json
sources/bitbucket-source/package.json
sources/buildkite-source/package.json
sources/customer-io-source/package.json
sources/datadog-source/package.json
sources/docker-source/package.json
sources/example-source/package.json
sources/firehydrant-source/package.json
sources/gitlab-ci-source/package.json
sources/googlecalendar-source/package.json
sources/harness-source/package.json
sources/jenkins-source/package.json
sources/okta-source/package.json
sources/opsgenie-source/package.json
sources/pagerduty-source/package.json
sources/phabricator-source/package.json
sources/servicenow-source/package.json
sources/shortcut-source/package.json
sources/squadcast-source/package.json
sources/statuspage-source/package.json
sources/victorops-source/package.json

Bump version to 0.1.70

---

destinations/airbyte-faros-destination/package.json
faros-airbyte-cdk/package.json
lerna.json
sources/agileaccelerator-source/package.json
sources/azureactivedirectory-source/package.json
sources/azurepipeline-source/package.json
sources/backlog-source/package.json
sources/bitbucket-source/package.json
sources/buildkite-source/package.json
sources/customer-io-source/package.json
sources/datadog-source/package.json
sources/docker-source/package.json
sources/example-source/package.json
sources/firehydrant-source/package.json
sources/gitlab-ci-source/package.json
sources/googlecalendar-source/package.json
sources/googlecalendar-source/src/googlecalendar.ts
sources/harness-source/package.json
sources/jenkins-source/package.json
sources/okta-source/package.json
sources/opsgenie-source/package.json
sources/pagerduty-source/package.json
sources/phabricator-source/package.json
sources/servicenow-source/package.json
sources/shortcut-source/package.json
sources/squadcast-source/package.json
sources/statuspage-source/package.json
sources/victorops-source/package.json

This will support config values sent by UI.
> Fix [#1]() 

GoogleCalendar Source: Replace escaped newlines with real ones in config

---

destinations/airbyte-faros-destination/package.json
destinations/airbyte-faros-destination/src/destination.ts
faros-airbyte-cdk/package.json
lerna.json
sources/agileaccelerator-source/package.json
sources/azureactivedirectory-source/package.json
sources/azurepipeline-source/package.json
sources/backlog-source/package.json
sources/bitbucket-source/package.json
sources/buildkite-source/package.json
sources/customer-io-source/package.json
sources/datadog-source/package.json
sources/docker-source/package.json
sources/example-source/package.json
sources/firehydrant-source/package.json
sources/gitlab-ci-source/package.json
sources/googlecalendar-source/package.json
sources/harness-source/package.json
sources/jenkins-source/package.json
sources/okta-source/package.json
sources/opsgenie-source/package.json
sources/pagerduty-source/package.json
sources/phabricator-source/package.json
sources/servicenow-source/package.json
sources/shortcut-source/package.json
sources/squadcast-source/package.json
sources/statuspage-source/package.json
sources/victorops-source/package.json

https://faros-ai.atlassian.net/browse/FAI-1909
https://faros-ai.atlassian.net/browse/FAI-1910

FAI-1910 - Set default revision expiration + tiny refactor on config

---

destinations/airbyte-faros-destination/package.json
destinations/airbyte-faros-destination/src/converters/github/issues.ts
faros-airbyte-cdk/package.json
lerna.json
sources/agileaccelerator-source/package.json
sources/azure-repos-source/package.json
sources/azureactivedirectory-source/package.json
sources/azurepipeline-source/package.json
sources/backlog-source/package.json
sources/bitbucket-source/package.json
sources/buildkite-source/package.json
sources/customer-io-source/package.json
sources/datadog-source/package.json
sources/docker-source/package.json
sources/example-source/package.json
sources/firehydrant-source/package.json
sources/gitlab-ci-source/package.json
sources/googlecalendar-source/package.json
sources/harness-source/package.json
sources/jenkins-source/package.json
sources/okta-source/package.json
sources/opsgenie-source/package.json
sources/pagerduty-source/package.json
sources/phabricator-source/package.json
sources/servicenow-source/package.json
sources/shortcut-source/package.json
sources/squadcast-source/package.json
sources/statuspage-source/package.json
sources/victorops-source/package.json

GitHub: Fix issue label lookup

---

destinations/airbyte-faros-destination/package.json
destinations/airbyte-faros-destination/src/converters/bitbucket/pull_requests.ts
faros-airbyte-cdk/package.json
lerna.json
sources/agileaccelerator-source/package.json
sources/azure-repos-source/package.json
sources/azureactivedirectory-source/package.json
sources/azurepipeline-source/package.json
sources/backlog-source/package.json
sources/bitbucket-source/package.json
sources/buildkite-source/package.json
sources/customer-io-source/package.json
sources/datadog-source/package.json
sources/docker-source/package.json
sources/example-source/package.json
sources/firehydrant-source/package.json
sources/gitlab-ci-source/package.json
sources/googlecalendar-source/package.json
sources/harness-source/package.json
sources/jenkins-source/package.json
sources/okta-source/package.json
sources/opsgenie-source/package.json
sources/pagerduty-source/package.json
sources/phabricator-source/package.json
sources/servicenow-source/package.json
sources/shortcut-source/package.json
sources/squadcast-source/package.json
sources/statuspage-source/package.json
sources/victorops-source/package.json

Add missing uid to commit

---

destinations/airbyte-faros-destination/src/converters/github/pull_requests.ts

Add draft indicator for GitHub pull requests

Add draft indicator for GitHub pull requests

---

destinations/airbyte-faros-destination/src/converters/github/pull_requests.ts

Add PR description into GitHub converter

GitHub converter - Add PR body as description

---

package-lock.json
package.json

Upgrade to Lerna 5.0.0

---

destinations/airbyte-faros-destination/src/converters/github/organizations.ts

Use GitHub org login name is name is missing

Use GitHub org login name if name is missing

---

package-lock.json
package.json

Bump dev deps

---

destinations/airbyte-faros-destination/src/converters/datadog/incidents.ts
destinations/airbyte-faros-destination/src/converters/firehydrant/incidents.ts
destinations/airbyte-faros-destination/src/converters/harness/executions.ts
destinations/airbyte-faros-destination/src/converters/opsgenie/incidents.ts
destinations/airbyte-faros-destination/src/converters/pagerduty/incidents.ts
destinations/airbyte-faros-destination/src/converters/pagerduty/priorities_resource.ts
destinations/airbyte-faros-destination/test/converters/datadog.test.ts
destinations/airbyte-faros-destination/test/converters/pagerduty.test.ts

Only write unique apps in all converters for Faros destination

Only write unique apps in all converters for Faros destination

---

destinations/airbyte-faros-destination/src/converters/azure-repos/pull_requests.ts
destinations/airbyte-faros-destination/src/converters/azure-repos/repositories.ts
destinations/airbyte-faros-destination/src/converters/gitlab-ci/pipelines.ts

Follow up to #511 . Missed a few places.

Additional fixes for uid fields in vcs_ entities

---

destinations/airbyte-faros-destination/package.json
faros-airbyte-cdk/package.json
lerna.json
sources/agileaccelerator-source/package.json
sources/azure-repos-source/package.json
sources/azureactivedirectory-source/package.json
sources/azurepipeline-source/package.json
sources/backlog-source/package.json
sources/bitbucket-source/package.json
sources/buildkite-source/package.json
sources/circleci-source/package.json
sources/customer-io-source/package.json
sources/datadog-source/package.json
sources/docker-source/package.json
sources/example-source/package.json
sources/firehydrant-source/package.json
sources/gitlab-ci-source/package.json
sources/googlecalendar-source/package.json
sources/harness-source/package.json
sources/jenkins-source/package.json
sources/okta-source/package.json
sources/opsgenie-source/package.json
sources/pagerduty-source/package.json
sources/phabricator-source/package.json
sources/servicenow-source/package.json
sources/servicenow-source/src/servicenow/servicenow.ts
sources/shortcut-source/package.json
sources/squadcast-source/package.json
sources/statuspage-source/package.json
sources/victorops-source/package.json

ServiceNow default cutoff

---

destinations/airbyte-faros-destination/src/community/hasura-writer.ts
destinations/airbyte-faros-destination/src/destination.ts

Pass logger and invalidRecordStrategy explicitely

Substitute with handler 

---

destinations/airbyte-faros-destination/package.json
faros-airbyte-cdk/package.json
lerna.json
sources/agileaccelerator-source/package.json
sources/azure-repos-source/package.json
sources/azureactivedirectory-source/package.json
sources/azurepipeline-source/package.json
sources/backlog-source/package.json
sources/bitbucket-source/package.json
sources/buildkite-source/package.json
sources/circleci-source/package.json
sources/customer-io-source/package.json
sources/datadog-source/package.json
sources/docker-source/package.json
sources/example-source/package.json
sources/firehydrant-source/package.json
sources/gitlab-ci-source/package.json
sources/googlecalendar-source/package.json
sources/harness-source/package.json
sources/jenkins-source/package.json
sources/okta-source/package.json
sources/opsgenie-source/package.json
sources/pagerduty-source/package.json
sources/phabricator-source/package.json
sources/servicenow-source/package.json
sources/shortcut-source/package.json
sources/squadcast-source/package.json
sources/statuspage-source/package.json
sources/victorops-source/package.json

bump after #529

---

.github/workflows/release.yml

fixes - https://github.com/faros-ai/airbyte-connectors/runs/6928504741?check_suite_focus=true

Fix package update in destination release

---

.github/workflows/skip-test-sources.txt
destinations/airbyte-faros-destination/src/converters/bamboohr/users.ts

Free BambooHR accounts only last for 7 days, so we don't have any long-lived credentials to test with.
> Fix [#1]() 

Remove team chain calculation from BambooHR converter + disable BambooHR acceptance test

---

destinations/airbyte-faros-destination/src/converters/bamboohr/models.ts
destinations/airbyte-faros-destination/src/converters/bamboohr/users.ts

Update BambooHR location and email data

---

destinations/airbyte-faros-destination/resources/spec.json

Fix destination spec

---

destinations/airbyte-faros-destination/src/converters/opsgenie/incidents.ts
destinations/airbyte-faros-destination/test/converters/opsgenie.test.ts
package-lock.json

OpsGenie: default to impacted service name for application

---

sources/opsgenie-source/src/opsgenie/opsgenie.ts
sources/opsgenie-source/test/index.test.ts

Do not fail when service cannot be retrieved. Only retrieve each service once.

Opsgenie: fix impacted service retrieval

---

sources/opsgenie-source/src/opsgenie/models.ts
sources/opsgenie-source/src/opsgenie/opsgenie.ts
sources/opsgenie-source/test/index.test.ts

Users were not being paginated but should be. Note: I also checked Teams, the API does not allow pagination.

OpsGenie: paginate users

---

destinations/airbyte-faros-destination/src/converters/opsgenie/incidents.ts

We need to make sure to protect against undefined things

OpsGenie: undefined protection

---

faros-airbyte-cdk/src/protocol.ts

Sanitize errors before converting to error trace messages

---

destinations/airbyte-faros-destination/src/destination.ts
package-lock.json

> Fix [#575](https://github.com/faros-ai/airbyte-connectors/issues/575) 

Dont reset incremental models

---

sources/bitbucket-source/src/bitbucket/bitbucket.ts

https://faroscommunity.slack.com/archives/C0350CRSC3C/p1658239288039309

Bitbucket: fix null errors in pull_requests stream

---

sources/bitbucket-source/src/bitbucket/bitbucket.ts

Bitbucket: fix null errors in pull_request_activities stream

---

sources/servicenow-source/resources/spec.json
sources/servicenow-source/src/servicenow/servicenow.ts
sources/servicenow-source/test/index.test.ts

Support a configurable service identifier so that any fields can be used to populate the `compute_Application.name`

FAI-2713  - ServiceNow configurable cmdb_ci/cmdb_ci_service identifier

---

destinations/airbyte-faros-destination/src/converters/converter.ts
destinations/airbyte-faros-destination/src/destination.ts
destinations/airbyte-faros-destination/test/index.test.ts

> Fix [#589](https://github.com/faros-ai/airbyte-connectors/issues/589) 

Fix circular dependency check

---

destinations/airbyte-faros-destination/src/converters/bamboohr/users.ts
sources/bamboohr-source/src/bamboohr.ts
sources/bamboohr-source/test/index.test.ts

…as default parent team
> Fix [#1]() 

BambooHR: warn when unable to fetch employee details ; use all_teams as default parent team

---

destinations/airbyte-faros-destination/src/converters/bamboohr/users.ts
destinations/airbyte-faros-destination/test/converters/bamboohr.test.ts

BambooHR: dont write teams if manager is missing

---

sources/buildkite-source/resources/gql/pipeline-builds-query.gql
sources/buildkite-source/resources/gql/pipelines-query.gql

Buildkite source: fix gql queries

---

sources/phabricator-source/src/phabricator.ts

Revision that doesn't return a diff: https://phabricator.services.mozilla.com/D150362
The Condoit library doesn't handle the API error properly.
> Fix [#1]() 

Phabricator Source: Don't fail on fetching raw diffs

---

destinations/airbyte-faros-destination/src/converters/bitbucket/deployments.ts

https://faroscommunity.slack.com/archives/C0335HMN2NQ/p1659987181484929
> Fix [#1]() 

Bitbucket: check both deployment env and fullEnv for slugs

---

package-lock.json

Update feeds sdk to 0.13.1
[clio](https://github.com/faros-ai/clio/pull/441)
[faros-feeds-sdk](https://github.com/faros-ai/feeds-sdk/pull/311)

FAI-2979: Alter Clio Schema Endpoint

---

sources/phabricator-source/src/phabricator.ts

Phabricator: Warn when unable to find repo for commit for revision

---

destinations/airbyte-faros-destination/src/converters/phabricator/revision_diffs.ts

Reduce size of warning messages for revision diffs

---

sources/pagerduty-source/src/pagerduty.ts

Log pagerduty url upon error

---

sources/phabricator-source/src/phabricator.ts

Phabricator: add repo phid to the warning message

Phabricator: add repo phid to the warning message

---

destinations/airbyte-faros-destination/src/converters/phabricator/common.ts
destinations/airbyte-faros-destination/src/converters/phabricator/projects.ts
destinations/airbyte-faros-destination/src/converters/phabricator/transactions.ts
sources/phabricator-source/src/phabricator.ts
sources/phabricator-source/test_files/revision_diffs.json
sources/phabricator-source/test_files/revision_diffs_records.json

Phabricator: repo name fallback logic

Phabricator: repo name fallback logic

---

destinations/airbyte-faros-destination/src/converters/phabricator/commits.ts

Phabricator: Warn unable to parse commit message

---

sources/pagerduty-source/src/pagerduty.ts

PagerDuty: log url upon api error

---

destinations/airbyte-faros-destination/src/converters/bamboohr/users.ts
sources/bamboohr-source/src/bamboohr.ts

The field is already being pulled, we just need to add it to the written org_User in the faros destination.

FAI-3026 - Retrieve active status from BambooHR

---

destinations/airbyte-faros-destination/src/converters/jira/users.ts

Write the tms_User inactive flag using the active flag provided by the user stream.

FAI-3025 - Faros destination Jira converter tms_User inactive flag

---

destinations/airbyte-faros-destination/src/converters/bamboohr/users.ts

For privacy reasons, we no longer want to save the users' addresses.

FAI-3003 - Remove exact address

---

sources/pagerduty-source/resources/spec.json
sources/pagerduty-source/src/pagerduty.ts
sources/pagerduty-source/src/streams/incidents.ts
sources/pagerduty-source/test/index.test.ts
sources/pagerduty-source/test_files/incidents.json
sources/pagerduty-source/test_files/services.json

PagerDuty: Add option to exclude incidents from specific services

---

sources/pagerduty-source/resources/spec.json
sources/pagerduty-source/src/pagerduty.ts
sources/pagerduty-source/test/index.test.ts

Retry PD API requests

---

Dockerfile

Faros Community Edition user report: https://faroscommunity.slack.com/archives/C0335HMN2NQ/p1663094521469029
I was able to reproduce on my M1 and fix with the change in this PR.
Reference for the fix: https://github.com/nodejs/docker-node/blob/main/docs/BestPractices.md#node-gyp-alpine

Install missing dependencies for docker build

---

destinations/airbyte-faros-destination/src/converters/github/pull_request_commits.ts

Check if repository is empty

---

destinations/airbyte-faros-destination/package.json
package-lock.json

FAI-3278: [airbyte-connectors] Remove FK constraints from Hasura Database

---

sources/bitbucket-server-source/resources/spec.json
sources/bitbucket-server-source/src/bitbucket-server/index.ts

Bitbucket Server: Add option to disable cert validation

---

destinations/airbyte-faros-destination/src/converters/bitbucket-server/common.ts

https://faroscommunity.slack.com/archives/C0350CRSC3C/p1664297577318389?thread_ts=1664181840.462559&cid=C0350CRSC3C
> Fix [#1]() 

Bitbucket Server: Change source field to "Bitbucket"

---

sources/bitbucket-server-source/src/bitbucket-server/index.ts

Bitbucket Server: Dont fail if repository main branch is invalid

---

destinations/airbyte-faros-destination/src/converters/bitbucket-server/pull_request_activities.ts
destinations/airbyte-faros-destination/src/converters/common/vcs.ts

Check file.to and file.from in Bitbucket Server source

Check file.to and file.from in Bitbucket Server source 

---

destinations/airbyte-faros-destination/src/converters/azurepipeline/pipelines.ts
destinations/airbyte-faros-destination/src/converters/bitbucket/deployments.ts
destinations/airbyte-faros-destination/src/converters/common/common.ts
destinations/airbyte-faros-destination/src/converters/common/vcs.ts
destinations/airbyte-faros-destination/src/converters/datadog/incidents.ts
destinations/airbyte-faros-destination/src/converters/firehydrant/incidents.ts
destinations/airbyte-faros-destination/src/converters/harness/common.ts
destinations/airbyte-faros-destination/src/converters/harness/executions.ts
destinations/airbyte-faros-destination/src/converters/opsgenie/incidents.ts
destinations/airbyte-faros-destination/src/converters/pagerduty/incidents.ts
destinations/airbyte-faros-destination/src/converters/servicenow/incidents.ts
destinations/airbyte-faros-destination/src/converters/squadcast/incidents.ts
destinations/airbyte-faros-destination/src/converters/squadcast/services.ts
destinations/airbyte-faros-destination/src/converters/statuspage/incidents.ts
destinations/airbyte-faros-destination/src/converters/victorops/incidents.ts
destinations/airbyte-faros-destination/test/converters/azurepipeline.test.ts
destinations/airbyte-faros-destination/test/converters/bitbucket.test.ts
destinations/airbyte-faros-destination/test/converters/firehydrant.test.ts
destinations/airbyte-faros-destination/test/converters/statuspage.test.ts

Add 'uid' to 'compute_Application' + use common function

Add `uid` to `compute_Application` + use common function

---

sources/jenkins-source/src/jenkins.ts
sources/jenkins-source/test/index.test.ts
sources/jenkins-source/test_files/jobs.json

- Add support for multi-branch pipeline

Add support for more Jenkins container types

---

destinations/airbyte-faros-destination/src/common/graphql-client.ts
destinations/airbyte-faros-destination/src/destination.ts

Add graphql queries to DEBUG log level

FAI-3587: Validate Dashboard sync for Faros tenant's V2 graph

---

destinations/airbyte-faros-destination/src/converters/googlecalendar/events.ts

Added geo_Coordinates to models list

Added geo_Coordinates to models list

---

faros-airbyte-cdk/src/destinations/destination-runner.ts
faros-airbyte-cdk/src/sources/source-base.ts
faros-airbyte-cdk/src/sources/source-runner.ts

Better logging for config and state messages

Better logging for config and state messages

---

.github/workflows/cla.yml

Exclude dependabot from CLA

---

destinations/airbyte-faros-destination/package.json
package-lock.json

FAI-3690: Rename GraphQL header

---

destinations/airbyte-faros-destination/src/converters/jira/issues.ts

Normalize statuses is JIRA issue converter

FAI-3765: JIRA converter should normalize task status

---

destinations/airbyte-faros-destination/src/converters/github/common.ts
destinations/airbyte-faros-destination/src/converters/github/pull_requests.ts
destinations/airbyte-faros-destination/src/converters/github/reviews.ts
destinations/airbyte-faros-destination/test/converters/github.test.ts

Return undefined for users without login

FAI-3830: Write to faros destination v2 fails

---

sources/googlecalendar-source/test_files/config.json

Add calendar_id to config.json

Add calendar_id to config.json

---

destinations/airbyte-faros-destination/src/converters/bitbucket-server/common.ts
destinations/airbyte-faros-destination/src/converters/bitbucket-server/pull_requests.ts
destinations/airbyte-faros-destination/src/converters/common/vcs.ts
destinations/airbyte-faros-destination/test/converters/bitbucket-server.test.ts
faros-airbyte-common/src/bitbucket-server/index.ts

FAI-3954 - [Bitbucket Server] Write vcs_Users from pull_request stream records

---

sources/firehydrant-source/resources/spec.json
sources/firehydrant-source/src/firehydrant/firehydrant.ts

Should help stabilize the source acceptance tests.
> Fix [#1]() 

FireHydrant Source: Make client timeout configurable

---

sources/circleci-source/src/streams/pipelines.ts
sources/circleci-source/test/index.test.ts
sources/circleci-source/test_files/pipelines.json
sources/circleci-source/test_files/pipelines_input.json
sources/circleci-source/test_files/pipelines_state.json

Current pipeline stream state is global, which can lead to missing pipelines during incremental syncs if one has more than one repo (aka slices).

[Circle CI] makes pipeline stream state slice specific

---

scripts/publish-connector.sh
scripts/source-acceptance-test.sh

Always pull latest images from Docker Hub

---

sources/googlecalendar-source/README.md
sources/googlecalendar-source/resources/spec.json
sources/googlecalendar-source/src/googlecalendar.ts
sources/googlecalendar-source/src/index.ts
sources/googlecalendar-source/src/streams/calendars.ts
sources/googlecalendar-source/src/streams/events.ts
sources/googlecalendar-source/test/index.test.ts
sources/googlecalendar-source/test_files/config.json

Add support for providing multiple calendars with domain wide-delegation.
https://github.com/faros-ai/airbyte-connectors/pull/788

FAI-4028 - Add support for multiple calendars with domain wide-delegation

---

.gitignore
Dockerfile
README.md
package-lock.json
package.json
scripts/publish-connector.sh
scripts/source-acceptance-test.sh

Package version wasn't set correctly for published Docker images. This change fixes it + updates Lerna to 6.0.3

Set package version in Docker images + update Lerna to 6.0.3

---

package-lock.json
sources/googlecalendar-source/src/googlecalendar.ts

Fix incremental sync in Google Calendar source + update deps

FAI-4028 - Fix incremental sync in Google Calendar source + update deps

---

package-lock.json
sources/faros-graphql-source/package.json
sources/faros-graphql-source/src/streams/faros-graph.ts

Use primary keys info while generating incremental queries
> Fix [#1]() 

Use primary keys info while generating incremental queries

---

destinations/airbyte-faros-destination/resources/spec.json
destinations/airbyte-faros-destination/src/common/graphql-client.ts
destinations/airbyte-faros-destination/src/destination.ts
destinations/airbyte-faros-destination/test/graphql-client.test.ts

Fix batch size configuration and set defaults at current optimal.

FAI-3971: Batch mutations in Faros Destination

---

package-lock.json
sources/azure-repos-source/src/azure-repos.ts

Gracefully handle 404 responses in Azure repos client + update deps
https://github.com/faros-ai/airbyte-connectors/issues/800

Gracefully handle 404 responses in Azure repos client + update deps

---

package-lock.json
sources/faros-graphql-source/package.json

Update faros-js-client to v0.2.7

Update faros-js-client to v0.2.7

---

faros-airbyte-cdk/package.json
package-lock.json
package.json

Remove @types/pino + bump pino

Remove @types/pino + bump pino

---

destinations/airbyte-faros-destination/src/converters/azure-repos/pull_requests.ts
destinations/airbyte-faros-destination/src/converters/azure-repos/repositories.ts

[Azure Repos] More guardrails around undefined properties

---

package-lock.json
sources/azure-repos-source/resources/spec.json
sources/azure-repos-source/src/azure-repos.ts
sources/azure-repos-source/src/index.ts
sources/azure-repos-source/src/streams/pullrequests.ts
sources/azure-repos-source/src/streams/repositories.ts
sources/azure-repos-source/src/streams/users.ts
sources/azure-repos-source/test/index.test.ts

Paginate pull requests & branch commits in Azure Repositories source.
Additionally added:
1. `max_commits_per_branch` param to limit number of commits we fetch per branch
2. `page_size` to control the page size while paginating
3. `request_timeout` param to allow controlling the timeout of the requests we make
4.  bump defaults of `api_version` and `graph_version` to 7.x
We should follow up and split branches and commits into separate streams - https://github.com/faros-ai/airbyte-connectors/issues/832
As a stop gap I added `max_commits_per_branch` argument to limit the number of commits we fetch.

Paginate pull requests & branch commits in Azure Repositories source

---

sources/azure-repos-source/resources/spec.json
sources/azure-repos-source/src/azure-repos.ts
sources/azure-repos-source/src/index.ts
sources/azure-repos-source/src/streams/pullrequests.ts
sources/azure-repos-source/src/streams/repositories.ts
sources/azure-repos-source/src/streams/users.ts
sources/azure-repos-source/test/index.test.ts

Azure repos: added await & retry logic based on rate limit headers
Assuming Axios response headers are lowercased

Azure repos: added await & retry logic based on rate limit headers

---

destinations/airbyte-faros-destination/package.json
package-lock.json
sources/azure-repos-source/package.json
sources/azure-repos-source/src/azure-repos.ts
sources/faros-graphql-source/package.json

Azure repos: added retry on network errors + update feeds-sdk & faros-js-client deps

Azure repos: added retry on network errors + update feeds-sdk & faros-js-client deps

---

package-lock.json
sources/azure-repos-source/resources/spec.json
sources/azure-repos-source/src/azure-repos.ts

Added branch pattern and retry on all argument

Added branch pattern and retry on all argument

---

package-lock.json
sources/azure-repos-source/package.json
sources/azure-repos-source/resources/spec.json
sources/azure-repos-source/src/azure-repos.ts

Azure Repos - retry on network & 5xx errors

---

package-lock.json
sources/faros-graphql-source/package.json
sources/faros-graphql-source/resources/spec.json
sources/faros-graphql-source/src/index.ts
sources/faros-graphql-source/src/streams/faros-graph.ts
sources/faros-graphql-source/test/__snapshots__/index.test.ts.snap
sources/faros-graphql-source/test/helpers.ts
sources/faros-graphql-source/test/index.test.ts

Make it possible to query a V2 graph using a V1 query
> Fix [#1]() 

Make it possible to query a V2 graph using a V1 query

---

destinations/airbyte-faros-destination/resources/spec.json
destinations/airbyte-faros-destination/src/common/graphql-writer.ts
destinations/airbyte-faros-destination/src/common/types.ts
destinations/airbyte-faros-destination/src/destination.ts
sources/faros-graphql-source/resources/spec.json
sources/faros-graphql-source/src/index.ts
sources/faros-graphql-source/src/streams/faros-graph.ts
sources/faros-graphql-source/test/__snapshots__/index.test.ts.snap
sources/faros-graphql-source/test/index.test.ts

Add option to accept incoming records origin and possibly replace them according to a mapping.
> Fix [#1]() 

Add option to accept incoming records origin

---

package-lock.json
sources/jenkins-source/resources/spec.json
sources/jenkins-source/src/jenkins.ts

Jenkins instances can be configured to expose jobs and builds to unauthenticated users
> Fix [#870](https://github.com/faros-ai/airbyte-connectors/issues/870) 
> No migrations

[Jenkins Source] - Change user and token to be optional

---

destinations/airbyte-faros-destination/package.json
destinations/airbyte-faros-destination/src/converters/faros-feeds/faros_feed.ts
destinations/airbyte-faros-destination/src/converters/jsonata.ts
package-lock.json
sources/faros-graphql-source/package.json

Integrates https://github.com/faros-ai/faros-js-client/pull/89

Integrate fixTimestampFields handling of operation records

---

sources/azure-repos-source/resources/spec.json
sources/azure-repos-source/src/azure-repos.ts

Support '*' to sync all projects. Update field description. Provide Item to array type field.

FAI-4937 - Support * to sync all projects

---

sources/clickup-source/resources/schemas/goals.json

FAI-3458: Fix goals schema

---

destinations/airbyte-faros-destination/package.json
package-lock.json

Update feeds sdk version to fix publish step

---

sources/faros-graphql-source/src/streams/faros-graph.ts
sources/faros-graphql-source/test/__snapshots__/index.test.ts.snap
sources/faros-graphql-source/test/index.test.ts

`_.set` doesn't mutate the object when `path` is `[]`
> Fix [#1]() 

Fix root level id replacement

---

package-lock.json
sources/azure-repos-source/resources/spec.json
sources/gitlab-ci-source/resources/spec.json
sources/squadcast-source/resources/spec.json
sources/squadcast-source/src/squadcast.ts
sources/squadcast-source/src/streams/incidents.ts
sources/squadcast-source/test/index.test.ts

Allow filtering Squadcast services & incidents by service slugs

Allow filtering Squadcast services & incidents by service slugs + update deps

---

faros-airbyte-cdk/src/help.ts

Example output for src without `order` fields: https://github.com/faros-ai/airbyte-connectors/blob/main/sources/agileaccelerator-source/resources/spec.json

Improve sorting function which determines what properties to output first

---

destinations/airbyte-faros-destination/resources/spec.json
destinations/airbyte-faros-destination/src/converters/jsonata.ts

Allows * shortcut to mean all models in jsonata_destination_models
> Fix [#1]() 

Allows * shortcut to mean all models in jsonata_destination_models

---

destinations/airbyte-faros-destination/src/common/graphql-client.ts

Added missing flush after resetting data

FAI-5100: V2 Sources not writing all records for full_refresh

---

destinations/airbyte-faros-destination/src/common/graphql-client.ts

Remove GraphQL Debug Statements

---

destinations/airbyte-faros-destination/resources/source-specific-configs.json
destinations/airbyte-faros-destination/src/converters/converter.ts
destinations/airbyte-faros-destination/src/converters/servicenow/common.ts
destinations/airbyte-faros-destination/src/converters/servicenow/incidents.ts
destinations/airbyte-faros-destination/src/destination.ts

Clean up `ims_IncidentApplicationImpact` association records so that there's at most one per incident
> Fix [#1]() 

Clean up ims_IncidentApplicationImpact association records so that there's at most one per incident

---

destinations/airbyte-faros-destination/src/converters/servicenow/incidents.ts

Improves ServiceNow incident converter

---

.github/workflows/skip-test-sources.txt
sources/circleci-source/acceptance-test-config.yml
sources/circleci-source/resources/spec.json
sources/circleci-source/src/circleci/circleci.ts
sources/circleci-source/src/index.ts
sources/circleci-source/src/streams/pipelines.ts
sources/circleci-source/src/streams/projects.ts
sources/circleci-source/test/index.test.ts
sources/circleci-source/test_files/abnormal_state.json
sources/circleci-source/test_files/invalid_config.json

Handle 404 errors from CircleCI API.
Fix spec to refer to projects, not repos, because that's what they are in CircleCI.
Reenable acceptance test.
> Fix [#1]() 

FAI-5257 - CircleCI Source Improvements Part 1

---

sources/azure-repos-source/src/azure-repos.ts
sources/azure-repos-source/src/models.ts

Potentially fixes: https://github.com/faros-ai/airbyte-connectors/issues/800#issuecomment-1434758597. Still trying to figure out how this error got through the handleNotFound logic

Fix annotatedTag not found error causing feed to fail

---

sources/bitbucket-source/resources/spec.json

Fix bitbucket spec to refer to workspace ids

---

faros-airbyte-cdk/package.json
faros-airbyte-cdk/src/destinations/destination-runner.ts
faros-airbyte-cdk/src/help.ts
faros-airbyte-cdk/src/prompts.ts
faros-airbyte-cdk/src/sources/source-runner.ts

Add interactive helper for building Airbyte local CLI commands
**Example for source**
**Example for destination**
> Fix [#1]() 

Add interactive helper for building Airbyte local CLI commands

---

destinations/airbyte-faros-destination/src/converters/servicenow/incidents.ts

Handle the case where the incident wasn't processed at all.
> Fix [#1]() 

Fix shouldDeleteRecord

---

sources/azure-repos-source/src/streams/pullrequests.ts

Following up on user reported issue: https://faroscommunity.slack.com/archives/C0350CRSC3C/p1677420267316059
> Fix [#1]() 

Fix state handling in azure-repos-source

---

sources/azure-repos-source/resources/spec.json
sources/azure-repos-source/src/azure-repos.ts
sources/azure-repos-source/test/index.test.ts

Honor [default](https://github.com/faros-ai/airbyte-connectors/blob/4a42b2d942d3270b5c9ef385d2a09155be20027a/sources/azure-repos-source/resources/spec.json#L31) `branch_pattern`
> Fix [#1]() 

Honor default branch_pattern

---

sources/azure-repos-source/src/azure-repos.ts

Azure repos annotatedTag fix

---

scripts/source-acceptance-test.sh
sources/pagerduty-source/resources/schemas/incidentLogEntries.json

Fix pagerduty incident log entries schema

---

package-lock.json
sources/pagerduty-source/src/pagerduty.ts
sources/pagerduty-source/src/streams/incidentLogEntries.ts
sources/pagerduty-source/src/streams/incidents.ts
sources/pagerduty-source/test/index.test.ts

Deal with PagerDuty response size 10k limit by paginating over days.

Deal with PagerDuty response size 10k limit by paginating over days

---

sources/agileaccelerator-source/src/agileaccelerator/agileaccelerator.ts
sources/azureactivedirectory-source/src/azureactivedirectory.ts
sources/bamboohr-source/src/bamboohr.ts
sources/clickup-source/resources/spec.json
sources/clickup-source/src/clickup.ts
sources/clickup-source/src/index.ts
sources/squadcast-source/resources/spec.json
sources/squadcast-source/src/squadcast.ts
sources/statuspage-source/src/statuspage.ts
sources/victorops-source/resources/spec.json
sources/victorops-source/src/victorops.ts
sources/workday-source/src/workday.ts

Make Axios max_content_length to Infinity

---

faros-airbyte-cdk/src/help.ts

Use description in prompts + handle missing (undefined) description
> Fix [#1]() 

Use description in prompts + handle missing (undefined) description

---

sources/octopus-source/resources/spec.json
sources/octopus-source/src/octopus.ts

Allow setting reject unauthorized for octopus source.

Octopus reject_unauthorized

---

.github/workflows/skip-test-sources.txt

Skip octopus source acceptance tests

---

faros-airbyte-cdk/src/utils.ts
sources/azure-repos-source/resources/spec.json
sources/azure-repos-source/src/azure-repos.ts
sources/azure-workitems-source/resources/spec.json
sources/azure-workitems-source/src/azure-workitems.ts
sources/azurepipeline-source/resources/spec.json
sources/azurepipeline-source/src/azurepipeline.ts

Azure sources should require unaltered access tokens

Azure sources should all require unaltered access tokens

---

destinations/airbyte-faros-destination/resources/spec.json
destinations/airbyte-faros-destination/src/common/types.ts
destinations/airbyte-faros-destination/src/converters/converter.ts
destinations/airbyte-faros-destination/src/destination.ts
destinations/airbyte-faros-destination/test/converters/converter.test.ts
destinations/airbyte-faros-destination/test/converters/github.test.ts
destinations/airbyte-faros-destination/test/testing-tools.ts
package-lock.json

Allow excluding records fields by model in Faros Destination

FAI-5663 - Allow excluding specific model record fields in Faros Destination

---

sources/faros-graphql-source/resources/spec.json

Make `legacy_v1_schema` secret so it wont be logged

Make `legacy_v1_schema` secret so it wont be logged

---

sources/pagerduty-source/src/pagerduty.ts
sources/pagerduty-source/test/pagerduty.test.ts

Handle exception response when pagination limit is exceeded.

Handle pagination exception when offset > 10000

---

faros-airbyte-cdk/src/destinations/destination-runner.ts
faros-airbyte-cdk/src/help.ts
faros-airbyte-cdk/src/sources/source-runner.ts

Make it possible to output a JSON config instead of Airbyte local CLI args

---

destinations/airbyte-faros-destination/src/converters/converter.ts

Fix prototype-polluting vuln

---

Dockerfile

FAI-5989 - Keep system packages updated

---

sources/octopus-source/src/octopusClient.ts

`axios-retry`'s default retryCondition did not seem to be working so I am explicitly defining one.

Octopus explicit retryCondition

---

destinations/airbyte-faros-destination/package.json
package-lock.json
sources/faros-graphql-source/package.json

For https://github.com/faros-ai/faros-js-client/pull/133

Faros js client => v0.2.27

---

destinations/airbyte-faros-destination/package.json
package-lock.json
sources/faros-graphql-source/package.json

For https://github.com/faros-ai/faros-js-client/pull/134

Faros js client => v0.2.28

---

destinations/airbyte-faros-destination/src/converters/statuspage/common.ts
destinations/airbyte-faros-destination/src/converters/statuspage/incidents.ts

Pull impact start and end for downtime calculation. Depends on a canonical-model change.

FAI-5450 - Application Impact startedAt & endedAt for downtime

---

destinations/airbyte-faros-destination/package.json
package-lock.json
sources/faros-graphql-source/package.json

For https://github.com/faros-ai/faros-js-client/pull/140

Upgrade faros-js-client

---

faros-airbyte-cdk/src/help.ts
faros-airbyte-cdk/src/prompts.ts

Add password input support to wizard
> Fix [#1]() 

Add password input support to wizard

---

destinations/airbyte-faros-destination/package.json
package-lock.json
sources/faros-graphql-source/package.json

FAI-6249: bump faros-js-client

---

sources/statuspage-source/src/streams/component_groups.ts

FAI-6311 - Fix statuspage component_groups stream schema

---

destinations/airbyte-faros-destination/src/converters/statuspage/components.ts
destinations/airbyte-faros-destination/src/converters/statuspage/incidents.ts

FAI-6311 - Populate Statuspage component converter destination models

---

sources/datadog-source/resources/spec.json
sources/datadog-source/src/datadog.ts

Datadog client debug

---

destinations/airbyte-faros-destination/src/converters/servicenow/incidents.ts

The current logic incorrectly deletes associations for incidents that were not processed.
> Fix [#1]() 

Actually fix shouldDeleteRecord logic

---

sources/datadog-source/src/datadog.ts

Datadog source: handle case where metrics unit is not provided

Datadog source: handle case where metrics unit is not provided

---

faros-airbyte-cdk/src/help.ts

Accept multiple items for array fields

---

faros-airbyte-cdk/src/logger.ts
faros-airbyte-cdk/test/logger.test.ts

FAI-6714 - Convert undefined source record property values to nulls

---

faros-airbyte-cdk/src/logger.ts
faros-airbyte-cdk/test/logger.test.ts

FAI-6714 - Only convert undefineds in actual record object

---

faros-airbyte-cdk/src/logger.ts
faros-airbyte-cdk/test/logger.test.ts

FAI-6714 - Don't treat dates as objects for undefined conversion

---

sources/octopus-source/resources/schemas/deployments.json
sources/octopus-source/resources/schemas/releases.json

Removing _extra from JSON Schemas

Cleanup Octopus schema

---

destinations/airbyte-faros-destination/package.json
package-lock.json
sources/faros-graphql-source/package.json

FAI-6878: add request compression to faros-js-client

---

.github/workflows/ci.yml
package-lock.json
package.json

Upgrade `mockttp` to address critical vulnerability

 FAI-6951: GHSA-g644-9gfx-q4q4 - update vm2 dependency

---

destinations/airbyte-faros-destination/src/converters/converter.ts
destinations/airbyte-faros-destination/test/converters/converter.test.ts

Handle double underscores in stream names

---

package-lock.json
sources/faros-graphql-source/resources/spec.json
sources/faros-graphql-source/src/index.ts
sources/faros-graphql-source/src/streams/faros-graph.ts

Added models filter to Faros GraphQL source

Added models filter to Faros GraphQL source + audit fix

---

faros-airbyte-cdk/src/help.ts

Removes extra `}`
> Fix [#1]() 

Fix array value formatting

---

sources/pagerduty-source/resources/schemas/users.json
sources/pagerduty-source/src/pagerduty.ts

Add some extra properties from the pagerduty users API
https://developer.pagerduty.com/api-reference/b3A6Mjc0ODIzMw-list-users
> Fix Resolves #1087
N/A - non-breaking schema change

Pagerduty: Add timezone, role, description and job_title

---

sources/pagerduty-source/resources/schemas/users.json

Update Pagerduty Users stream schema

---

sources/customer-io-source/resources/spec.json
sources/customer-io-source/src/customer-io/customer-io.ts

Honor `cutoff_days` default
> Fix [#1]() 

Honor cutoff_days default

---

sources/workday-source/resources/spec.json

oneOf has strict formatting requirements. This adds the const

[FAI-2451] fix oneOf

---

faros-airbyte-cdk/src/destinations/destination-runner.ts
faros-airbyte-cdk/src/help.ts
faros-airbyte-cdk/src/sources/source-runner.ts
faros-airbyte-cdk/test/__snapshots__/help.test.ts.snap
faros-airbyte-cdk/test/help.test.ts
faros-airbyte-cdk/test/resources/help/one-of-airbyte-hidden.json

Adds support for `airbyte_hidden` https://docs.airbyte.com/connector-development/connector-specification-reference/#hiding-inputs-in-the-ui
> Fix [#1]() 

FAI-7388 Support airbyte_hidden

---

faros-airbyte-cdk/src/help.ts
faros-airbyte-cdk/test/__snapshots__/help.test.ts.snap
faros-airbyte-cdk/test/help.test.ts

I missed one filter in #1149 [here](https://github.com/faros-ai/airbyte-connectors/blob/d0199c33c8e8df9cfa3a258fef3281889ec27658/faros-airbyte-cdk/src/help.ts#L86)
Also, refactors the filter function to remove duplication
> Fix [#1]() 

fix bug + refactor

---

.github/workflows/release.yml

FAI-7919 - Workaround for empty GITHUB_REF bug

---

sources/asana-source/resources/spec.json
sources/asana-source/src/asana.ts

Adds `cutoff_days` for consistency with other sources
Leaves `start/end` date as hidden

Asana spec nits + add cutoff

---

destinations/airbyte-faros-destination/src/common/graphql-client.ts
destinations/airbyte-faros-destination/test/__snapshots__/graphql-client.test.ts.snap
destinations/airbyte-faros-destination/test/graphql-client.test.ts

Fix serialization of primary keys that contain objects

FAI-8329: Fix serialization of primary keys that contain objects

---

faros-airbyte-cdk/src/sources/source-base.ts

FAI-8191 - Pass sourceStatus if present in compressed state message

---

destinations/airbyte-faros-destination/package.json
destinations/airbyte-faros-destination/src/converters/asana/tasks.ts
package-lock.json
sources/faros-graphql-source/package.json

Created FAI-8342 to use this in other cases as needed in our codebase

Upgrade faros-js-client to 0.3.7 + use cleanAndTruncate

---

sources/bitbucket-server-source/src/bitbucket-server/index.ts

I'm not able to reproduce this error locally.
> Fix [#1]() 

FAI-8191 - Bitbucket Server: Handle missing default branch error

---

sources/bitbucket-server-source/src/bitbucket-server/index.ts

FAI-8191 - Fix error message in prev commit

---

destinations/airbyte-faros-destination/src/converters/abstract-surveys/models.ts

- Added Coding Assistants question category for AI module
https://github.com/faros-ai/canonical-models/pull/206

FAI-7910 | Added Coding Assistants question category

---

destinations/airbyte-faros-destination/resources/spec.json
destinations/airbyte-faros-destination/src/common/types.ts
destinations/airbyte-faros-destination/src/destination.ts
faros-airbyte-cdk/src/protocol.ts
faros-airbyte-cdk/src/sources/source-base.ts

FAI-8380 - Only reset non-incremental models when Airbyte Source sends a success message

---

sources/bitbucket-server-source/resources/more-routes.json
sources/bitbucket-server-source/src/bitbucket-server/index.ts

FAI-8380 - Ignore missing bitbucket server commits

---

destinations/airbyte-faros-destination/src/converters/abstract-surveys/surveys.ts
destinations/airbyte-faros-destination/test/converters/__snapshots__/abstract-surveys.test.ts.snap
destinations/airbyte-faros-destination/test/converters/abstract-surveys.test.ts

FAI-8457 | Add string array column value support for surveys lookup column type

---

destinations/airbyte-faros-destination/resources/source-specific-configs/surveys.json
destinations/airbyte-faros-destination/src/converters/abstract-surveys/surveys.ts
destinations/airbyte-faros-destination/test/converters/__snapshots__/abstract-surveys.test.ts.snap
destinations/airbyte-faros-destination/test/converters/__snapshots__/sheets.test.ts.snap
destinations/airbyte-faros-destination/test/converters/abstract-surveys.test.ts

FAI-8400 | Survey exclude columns

---

destinations/airbyte-faros-destination/resources/source-specific-configs/bitbucket.json
destinations/airbyte-faros-destination/resources/source-specific-configs/datadog.json
destinations/airbyte-faros-destination/resources/source-specific-configs/firehydrant.json
destinations/airbyte-faros-destination/resources/source-specific-configs/notion.json
destinations/airbyte-faros-destination/resources/source-specific-configs/opsgenie.json
destinations/airbyte-faros-destination/resources/source-specific-configs/pagerduty.json
destinations/airbyte-faros-destination/resources/source-specific-configs/servicenow.json
destinations/airbyte-faros-destination/resources/source-specific-configs/squadcast.json
destinations/airbyte-faros-destination/resources/source-specific-configs/statuspage.json
destinations/airbyte-faros-destination/resources/source-specific-configs/victorops.json

Modifying config for more clarity

[FAI-8547] Applying mt's comments

---

destinations/airbyte-faros-destination/src/converters/faros-feeds/model_names.ts

Added vcs tool org/user model names
> Fix [#1]() 

FAI-8227 | added vcs tool org/user model names

---

sources/circleci-source/src/circleci/circleci.ts
sources/circleci-source/src/index.ts

Make the new params in https://github.com/faros-ai/airbyte-connectors/pull/1230 optional for backwards compatibility.
> Fix [#1]() 

FAI-8458 - Make new circleci params optional

---

destinations/airbyte-faros-destination/src/common/graphql-writer.ts

FAI-8759 - Submit non-timestamped record deletions as they are received

---

sources/sheets-source/src/sheets-reader.ts

FAI-8817 | Add check to avoid fetching rows out of range from sheet

---

sources/circleci-source/src/circleci/circleci.ts

Not enough logging to debug issues with Circle CI

FAI-8827  CircleCI - More logging and more performant request

---

faros-airbyte-cdk/package.json
package-lock.json

Possible regression with 8.17.0 https://github.com/pinojs/pino/issues/1864
> Fix [#1]() 

Pin pino to 8.16.0

---

destinations/airbyte-faros-destination/README.md
destinations/airbyte-faros-destination/src/converters/aws-cloudwatch-metrics/metrics.ts
destinations/airbyte-faros-destination/test/converters/aws-cloudwatch-metrics.test.ts
destinations/airbyte-faros-destination/test/converters/data.ts
destinations/airbyte-faros-destination/test/resources/aws-cloudwatch-metrics/all-streams.log
destinations/airbyte-faros-destination/test/resources/aws-cloudwatch-metrics/catalog.json
destinations/airbyte-faros-destination/test/resources/aws-cloudwatch-metrics/config.json
destinations/airbyte-faros-destination/test/resources/aws-cloudwatch-metrics/input.json
destinations/airbyte-faros-destination/test/resources/aws-cloudwatch-metrics/output.json
faros-airbyte-cdk/package.json

[FAI-8798](https://faros-ai.atlassian.net/browse/FAI-8798)
[FAI-8798]: https://faros-ai.atlassian.net/browse/FAI-8798?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[FAI-8798] add codewhisperer converter

---

sources/sheets-source/src/sheets-reader.ts

Fix logging for Sheets Source

---

package-lock.json
sources/faros-graphql-source/package.json

Upgrade faros-js-client to 0.4.1

---

sources/circleci-source/resources/spec.json
sources/circleci-source/test_files/invalid_config.json

Fix propagating the spec change.

CircleCI spec fix

---

sources/circleci-source/resources/spec.json
sources/circleci-source/src/circleci/circleci.ts
sources/circleci-source/src/faros/faros.ts
sources/circleci-source/src/index.ts

CircleCI should validate Faros API input when pull_blocklist_from_graph.

CircleCI input validation fix

---

sources/circleci-source/src/circleci/circleci.ts
sources/circleci-source/src/index.ts

We should lowercase all fields that are compared for a less fragile comparison.

FAI-8724 - CircleCI exclusion improvement

---

faros-airbyte-cdk/src/logger.ts

Package Release failing due to pino complaint

Fix Package Release

---

destinations/airbyte-faros-destination/test/__snapshots__/graphql-client.test.ts.snap
destinations/airbyte-faros-destination/test/graphql-client.test.ts

Add tests of duplicate object merging behavior

---

destinations/airbyte-faros-destination/src/converters/circleci/tests.ts

To know if onProcessingComplete started in the lgos

CCI Tests onProcessing Complete logging message

---

destinations/airbyte-faros-destination/src/converters/faros-feeds/model_names.ts

Introduced here: https://github.com/faros-ai/feeds/pull/2033

FAI-9076 Add faros_MetricValueTag to models

---

destinations/airbyte-faros-destination/src/destination.ts

FAI-9123 - Reset models when Airbyte "Reset your data" sync is run

---

.github/workflows/release.yml

Fix GITHUB_REF bug workaround

---

sources/faros-graphdoctor-source/src/graphdoctor/duplicateNames.ts
sources/faros-graphdoctor-source/src/graphdoctor/timeTests.ts
sources/faros-graphdoctor-source/src/graphdoctor/utils.ts
sources/faros-graphdoctor-source/test/index.test.ts

Modifying logging settings from "info" to "debug" and removing test logs.

GraphDoctor Logging

---

sources/workday-source/README.md

Updating README to include new fields

Workday Connector README update

---

faros-airbyte-cdk/src/errors.ts
faros-airbyte-cdk/src/index.ts
faros-airbyte-cdk/src/sources/source-base.ts

FAI-9312 - Support non-fatal errors that are passed to destination via state message

---

package-lock.json
package.json

Bumping dependencies to remediate vulnerabilities

FAI-8961 - Bump dependencies

---

package-lock.json
package.json

Reverts faros-ai/airbyte-connectors#1307
We can't have nice things

Revert "FAI-8961 - Bump dependencies"

---

package-lock.json
package.json

FAI-9003 - Audit fix

---

package-lock.json
sources/workday-source/resources/spec.json
sources/workday-source/src/workday.ts
sources/workday-source/test/index.test.ts
sources/workday-source/test_files/config_tokens.json
sources/workday-source/test_files/config_unpw.json

Looks like default URL was displayed incorrectly (creates double backslash).

workday source spec fix

---

destinations/airbyte-faros-destination/src/converters/workday/customreports.ts

Workday logs can grow too large if the number of teams is very large

Workday logs less

---

destinations/airbyte-faros-destination/package.json
destinations/airbyte-faros-destination/resources/spec.json
destinations/airbyte-faros-destination/src/common/types.ts
destinations/airbyte-faros-destination/src/common/write-stats.ts
destinations/airbyte-faros-destination/src/destination.ts
destinations/airbyte-faros-destination/src/sync.ts
destinations/airbyte-faros-destination/test/converters/github.test.ts
destinations/airbyte-faros-destination/test/sync.test.ts
destinations/airbyte-faros-destination/test/testing-tools.ts
faros-airbyte-cdk/src/protocol.ts
faros-airbyte-cdk/src/sources/source-base.ts

FAI-9525 - First iteration of sync statuses

---

destinations/airbyte-faros-destination/src/destination.ts
destinations/airbyte-faros-destination/src/sync.ts

Send logId from Airbyte and disable for hybrid until more fleshed out

---

package-lock.json

Fix "ip" package vulnerability

---

destinations/airbyte-faros-destination/src/converters/workday/customreports.ts

Storing email in correct location

Workday primary email storage

---

Dockerfile
local/Dockerfile

Fixes acceptance test error from https://github.com/faros-ai/airbyte-connectors/commit/5c83f47cd92808639a870d10348e37579de2215a.
> Fix [#1]() 

Put back AIRBYTE_ENTRYPOINT docker var

---

Dockerfile

Revert dockerfile changes

---

destinations/airbyte-faros-destination/src/converters/faros-feeds/model_names.ts

https://github.com/faros-ai/canonical-models/commit/a29ae50aa078da855e875ff2046295bed69a87a8

[FAI-9075] Add new model vcs_UserEmail

---

.github/workflows/skip-test-sources.txt

Add jira-source to skip test sources

---

destinations/airbyte-faros-destination/src/converters/jira/issues.ts
destinations/airbyte-faros-destination/src/converters/jira/pull_requests.ts

Jira converters are being used by Faros Community Edition with Jira Community Airbyte source. So we should maintain for now this converters as they are and add new ones for our jira source.
> Fix [#1]() 

Undo changes made to jira converters

---

faros-airbyte-cdk/src/sources/streams/stream-base.ts
package-lock.json

FAI-10201 - Work around Airbyte UI nested cursor field bug

---

destinations/airbyte-faros-destination/src/destination.ts
destinations/airbyte-faros-destination/src/sync.ts
destinations/airbyte-faros-destination/test/converters/github.test.ts
destinations/airbyte-faros-destination/test/sync.test.ts
faros-airbyte-cdk/src/protocol.ts
faros-airbyte-cdk/src/sources/source-base.ts

FAI-10249 - Support "partial success" statuses and warnings

---

destinations/airbyte-faros-destination/src/sync.ts

FAI-10269 - Update sync status error logging

---

destinations/airbyte-faros-destination/resources/cloud.json
destinations/airbyte-faros-destination/src/destination-logger.ts
destinations/airbyte-faros-destination/src/destination.ts

FAI-10035 - Option to disable log upload

---

.github/workflows/skip-test-sources.txt
sources/vanta-source/README.md

Adding README to vanta source and skipping source connector test

FAI-10306 | README and skip test source

---

sources/workday-source/resources/spec.json
sources/workday-source/src/workday.ts
sources/workday-source/test/index.test.ts
sources/workday-source/test/workday.test.ts
sources/workday-source/test_files/config_tokens.json
sources/workday-source/test_files/config_unpw.json

FAI-10335 - Fix workday source url handling

---

sources/workday-source/src/workday.ts

FAI-10335 - Fix bug from last PR

---

sources/trello-source/src/trello.ts

Fix Trello checkConnection error

---

destinations/airbyte-faros-destination/src/destination.ts
faros-airbyte-cdk/src/logger.ts
faros-airbyte-cdk/src/sources/source-base.ts

FAI-10381 - Complete sync status upon destination error

---

destinations/airbyte-faros-destination/src/destination-logger.ts
destinations/airbyte-faros-destination/src/sync.ts

Use utf-8 for log upload operations

---

faros-airbyte-cdk/src/sources/source-base.ts

FAI-10258 - Full-refresh streams can create state

---

destinations/airbyte-faros-destination/src/destination.ts
destinations/airbyte-faros-destination/src/sync.ts
destinations/airbyte-faros-destination/test/sync.test.ts

Don't try to upload sync logs if url not available, and improve error logging

---

destinations/airbyte-faros-destination/resources/spec.json
destinations/airbyte-faros-destination/src/common/types.ts
destinations/airbyte-faros-destination/src/destination.ts
destinations/airbyte-faros-destination/src/record-redactor.ts
destinations/airbyte-faros-destination/test/record-redactor.test.ts

Updated PII redactor custom regex parameter to receive a list of stringified regex's instead of a single one.

FAI-10349 | Updated PII redactor custom regex parameter to array instead of string

---

destinations/airbyte-faros-destination/resources/spec.json
destinations/airbyte-faros-destination/src/common/types.ts
destinations/airbyte-faros-destination/src/destination.ts

FAI-10415 - Add destination option to fail on any source error

---

package-lock.json
sources/circleci-source/package.json
sources/circleci-source/src/index.ts
sources/circleci-source/test/index.test.ts

- Allow pattern matching for wildcards in CircleCI connector to enable easier filtering of slugs

FAI-10449: Support for wildcards blacklist/whitelist in Circle CI connector

---

destinations/airbyte-faros-destination/src/converters/zendesk/common.ts
destinations/airbyte-faros-destination/src/converters/zendesk/groups.ts
destinations/airbyte-faros-destination/src/converters/zendesk/satisfaction_ratings.ts
destinations/airbyte-faros-destination/test/converters/__snapshots__/zendesk.test.ts.snap
destinations/airbyte-faros-destination/test/converters/zendesk.test.ts
package-lock.json
sources/sheets-source/package.json

- Add mapping when group is not in context

FAI-10378: Add mapping when group is not in context

---

sources/circleci-source/resources/spec.json
sources/circleci-source/src/circleci/circleci.ts
sources/circleci-source/src/circleci/types.ts
sources/circleci-source/src/index.ts
sources/circleci-source/test/index.test.ts

- CircleCI fix incremental sync, make project slugs consistent and incorrect lastUpdated
- Fix block_list param inconsistency

FAI-10447: CircleCI fix incremental sync

---

sources/jira-source/resources/spec.json
sources/jira-source/src/index.ts
sources/jira-source/src/jira.ts
sources/jira-source/src/streams/common.ts
sources/jira-source/test/__snapshots__/index.test.ts.snap
sources/jira-source/test/index.test.ts
sources/jira-source/test_files/catalog.json

Check for  WebhookGaps mode to select streams before records read.
TODO: 
> Fix [#1]() 

FAI-10607 - Add run_mode config to support WebhookGaps mode 

---

faros-airbyte-common/package.json
faros-airbyte-common/src/common/index.ts
sources/bitbucket-server-source/src/bitbucket-server/index.ts
sources/jira-source/package.json
sources/jira-source/resources/spec.json
sources/jira-source/src/jira.ts
sources/jira-source/src/streams/common.ts
sources/jira-source/test/__snapshots__/index.test.ts.snap
sources/jira-source/test/index.test.ts
sources/jira-source/test_files/config.json

FAI-10626 - Add bucketing to Jira Conector

---

faros-airbyte-cdk/src/sources/source-runner.ts

Missed the source part in #1420

FAI-10324 Minimize large specs

---

sources/jira-source/resources/schemas/farosIssuePullRequests.json
sources/jira-source/src/models.ts

FAI-10569 - Fix issuePullRequest schema to include missing fields

---

destinations/airbyte-faros-destination/src/converters/jira/faros_sprints.ts
destinations/airbyte-faros-destination/test/converters/jira.test.ts
destinations/airbyte-faros-destination/test/resources/jira/all-streams.log
sources/jira-source/resources/schemas/farosSprints.json
sources/jira-source/src/models.ts
sources/jira-source/src/streams/faros_sprint_reports.ts
sources/jira-source/src/streams/faros_sprints.ts
sources/jira-source/test/__snapshots__/index.test.ts.snap

Replace our Sprint model with Jira Agile Sprint mode and include tms_SprintBoardRelationship in faros_sprint converter.
> Fix [#1]() 

FAI-10151 - Jira Agile Sprint model instead of ours and tms_SprintBoardRelationship

---

destinations/airbyte-faros-destination/src/sync.ts
faros-airbyte-cdk/src/sources/source-logger.ts

Log axios error response

---

package-lock.json
package.json

FAI-10573: Fix protobuf vulnerability

---

sources/jira-source/src/client.ts
sources/jira-source/test/client.test.ts

Was able to port these unchanged from the feed

FAI-11093 Jira tests -- client

---

sources/jira-source/src/jira.ts
sources/jira-source/src/jql-builder.ts
sources/jira-source/src/streams/faros_board_issues.ts
sources/jira-source/src/streams/faros_issue_pull_requests.ts
sources/jira-source/src/streams/faros_issues.ts
sources/jira-source/test/__snapshots__/jql-builder.test.ts.snap
sources/jira-source/test/jql-builder.test.ts

In a separate PR, I'll try to untangle the rest of the params and the corresponding logic (`fetchKeysOnly`, `includeAdditionalFields`, `additionalFields`)

Refactor getIssues in jira source. Part 1

---

sources/jira-source/src/jql-builder.ts
sources/jira-source/test/__snapshots__/jql-builder.test.ts.snap

See FAI-11220 for details
> Fix [#1]() 

FAI-11220 Jira jql builder should follow original behavior

---

sources/bitbucket-source/src/bitbucket/bitbucket.ts

Copy of https://github.com/faros-ai/airbyte-connectors/pull/1353, which can't be merged due to unsigned commits.
> Fix [#1]() 

Fix in buildPipeline function

---

package-lock.json
package.json

Markdown-it Vuln update

---

package-lock.json
sources/jira-source/src/jira.ts
sources/jira-source/test/__snapshots__/index.test.ts.snap
sources/jira-source/test/index.test.ts

- Prevent re-instantiating the Jira client for every stream slice

FAI-11182: Re-use jira instance if exists

---

destinations/airbyte-faros-destination/src/converters/jira/faros_sprint_reports.ts

FAI-10569 - Fix model name to write task

---

sources/jira-source/src/streams/faros_projects.ts

Fix faros_projects schema file reference

---

sources/jira-source/src/streams/faros_issue_pull_requests.ts
sources/jira-source/src/streams/faros_issues.ts
sources/jira-source/src/streams/faros_sprint_reports.ts
sources/jira-source/src/streams/faros_sprints.ts

- When using full sync mode still get the update range to be cutoff dates

FAI-11182: Jira source fix full sync dates

---

sources/bitbucket-server-source/src/bitbucket-server/index.ts

Don't fail bitbucket server pr diffs stream on individual diff error

---

sources/jira-source/src/streams/faros_sprint_reports.ts

Fix sprint reports stream cursorField

---

destinations/airbyte-faros-destination/src/converters/jira/faros_issues.ts
destinations/airbyte-faros-destination/test/converters/__snapshots__/faros_jira.test.ts.snap

FAI-11565 | Add missing tms_TaskProjectRelationship to issues converter

---

sources/circleci-source/src/streams/tests.ts

FAI-11383 - Reduce memory usage in circleci tests stream

---

sources/jira-source/src/streams/faros_board_issues.ts
sources/jira-source/src/streams/faros_boards.ts
sources/jira-source/src/streams/faros_project_version_issues.ts
sources/jira-source/src/streams/faros_sprint_reports.ts

- Add Jira stream dependencies to align order to sync data in

Add Jira stream dependencies

---

Dockerfile
docker/entrypoint.sh
local/Dockerfile

FAI-11632 - Scale heap size with available memory

---

.github/workflows/skip-test-sources.txt

Add xray-source to skip-test-sources

---

sources/jira-source/resources/spec.json
sources/jira-source/src/client.ts
sources/jira-source/src/jira.ts
sources/jira-source/src/streams/faros_team_memberships.ts
sources/jira-source/src/streams/faros_teams.ts

FAI-11033 | Jira Server/DC teams stream 

---

sources/jira-source/resources/spec.json
sources/jira-source/src/streams/common.ts

FAI-11694: Add minimum streams run mode

---

destinations/airbyte-faros-destination/src/destination.ts

FAI-11742 - Additional requirements for determining if a sync is a reset job

---

sources/circleci-source/src/circleci/circleci.ts
sources/circleci-source/src/streams/tests.ts

FAI-11383 - CircleCI: yield test metadata records as they are fetched instead of aggregating

---

Dockerfile

Add new required system package for Apple M chip builds

---

destinations/airbyte-faros-destination/src/destination-logger.ts
destinations/airbyte-faros-destination/src/destination.ts
destinations/airbyte-faros-destination/src/sync.ts

FAI-11735 - Upload logs without hash verification if needed

---

sources/faros-graphdoctor-source/resources/schemas/data-quality-tests.json
sources/faros-graphdoctor-source/src/streams/data-quality-tests.ts
sources/workday-source/resources/schemas/customreports.json

Ensuring 'properties' is present in graphdoctor and ensuring schema is referenced properly

Adding properties to graphdoctor schema

---

faros-airbyte-cdk/src/index.ts
faros-airbyte-cdk/src/testing-tools.ts
sources/jira-source/src/index.ts
sources/jira-source/src/jira.ts
sources/jira-source/test/__snapshots__/index.test.ts.snap
sources/jira-source/test/index.test.ts
sources/jira-source/test/resources/check_connection/valid.json
sources/jira-source/test/resources/issue_pull_requests/catalog.json
sources/jira-source/test/resources/issue_pull_requests/config.json

Refactor source tests

---

destinations/airbyte-faros-destination/src/destination-logger.ts
destinations/airbyte-faros-destination/src/sync.ts

FAI-11735 - Handle error when md5 is disabled

---

destinations/airbyte-faros-destination/src/destination-logger.ts

FAI-11932 - Check if environment is FIPS-compliant before trying to hash logs

---

destinations/airbyte-faros-destination/src/destination-logger.ts

FAI-11932 - Additional FIPS check

---

.github/workflows/skip-test-sources.txt

Skip GitHub Source acceptance test

---

destinations/airbyte-faros-destination/src/converters/workday/customreports.ts

Follow up to #1541 
> Fix [#1]() 

Use getTerminationDate when populating the model

---

destinations/airbyte-faros-destination/src/destination.ts

FAI-12095 - Signal an error if there is evidence that the Source crashed unexpectedly

---

docker/entrypoint.sh
faros-airbyte-cdk/src/destinations/destination-runner.ts
faros-airbyte-cdk/src/runner.ts
faros-airbyte-cdk/src/sources/source-runner.ts

Fix entrypoint to read proper container files to determine heap size

---

sources/github-source/resources/spec.json
sources/github-source/src/index.ts
sources/github-source/src/org-repo-filter.ts
sources/github-source/src/streams/common.ts
sources/github-source/src/streams/faros_organizations.ts
sources/github-source/src/types.ts
sources/github-source/test/resources/config.json

- Added run_mode param for GitHub source
- CopilotEvaluationApp mode streams already finished

FAI-11601 | Added run_mode param for GitHub source

---

sources/github-source/src/index.ts
sources/github-source/src/streams/common.ts

FAI-11601 | Added full run mode (GitHub)

---

sources/agileaccelerator-source/acceptance-test-config.yml
sources/azure-repos-source/acceptance-test-config.yml
sources/azureactivedirectory-source/acceptance-test-config.yml
sources/azurepipeline-source/acceptance-test-config.yml
sources/backlog-source/acceptance-test-config.yml
sources/bamboohr-source/acceptance-test-config.yml
sources/bitbucket-server-source/acceptance-test-config.yml
sources/bitbucket-source/acceptance-test-config.yml
sources/buildkite-source/acceptance-test-config.yml
sources/circleci-source/acceptance-test-config.yml
sources/clickup-source/acceptance-test-config.yml
sources/customer-io-source/acceptance-test-config.yml
sources/docker-source/acceptance-test-config.yml
sources/firehydrant-source/acceptance-test-config.yml
sources/gitlab-ci-source/acceptance-test-config.yml
sources/googlecalendar-source/acceptance-test-config.yml
sources/harness-source/acceptance-test-config.yml
sources/okta-source/acceptance-test-config.yml
sources/pagerduty-source/acceptance-test-config.yml
sources/semaphoreci-source/acceptance-test-config.yml
sources/shortcut-source/acceptance-test-config.yml
sources/squadcast-source/acceptance-test-config.yml
sources/statuspage-source/acceptance-test-config.yml
sources/victorops-source/acceptance-test-config.yml

Skip spec check in acceptance tests

---

sources/workday-source/resources/schemas/customreports.json

Airbyte schema fix - update property

---

faros-airbyte-cdk/src/sources/streams/stream-base.ts
sources/github-source/resources/spec.json
sources/github-source/src/github.ts
sources/github-source/src/index.ts
sources/github-source/src/org-repo-filter.ts
sources/github-source/src/streams/common.ts
sources/github-source/src/streams/faros_pull_requests.ts
sources/github-source/src/types.ts
sources/github-source/test/__snapshots__/index.test.ts.snap
sources/github-source/test/common.test.ts
sources/github-source/test/index.test.ts
sources/github-source/test/resources/config.json
sources/jira-source/src/streams/common.ts
sources/jira-source/test/common.test.ts

Incremental sync support for pull requests stream + cutoff_days param

FAI-11596 | Incremental sync support for pull requests stream

---

destinations/airbyte-faros-destination/src/converters/github/faros_commits.ts
faros-airbyte-common/resources/github/fragments/commit-fields.gql
faros-airbyte-common/resources/github/queries/commits-changed-files-if-available-query.gql
faros-airbyte-common/resources/github/queries/commits-changed-files-query.gql
faros-airbyte-common/resources/github/queries/commits-query.gql
faros-airbyte-common/src/github/codegen.ts
faros-airbyte-common/src/github/generated/index.ts
faros-airbyte-common/src/github/queries.ts
faros-airbyte-common/src/github/types.ts
sources/github-source/README.md
sources/github-source/resources/schemas/farosCommits.json
sources/github-source/src/github.ts
sources/github-source/src/index.ts
sources/github-source/src/org-repo-filter.ts
sources/github-source/src/streams/common.ts
sources/github-source/src/streams/faros_commits.ts
sources/github-source/test/__snapshots__/index.test.ts.snap
sources/github-source/test/index.test.ts
sources/github-source/test/resources/commits/catalog.json
sources/github-source/test/resources/commits/commits.json

Source stream for commits. Following PRS: Converter and incremental sync support.
> Fix [#1]() 

FAI-11598: Commits Source Full Sync

---

destinations/airbyte-faros-destination/src/common/graphql-client.ts
destinations/airbyte-faros-destination/test/__snapshots__/graphql-client.test.ts.snap

Set session for reset delete queries.

FAI-12219: Add delete session tracking to Faros destination

---

destinations/airbyte-faros-destination/src/converters/converter.ts
destinations/airbyte-faros-destination/src/converters/faros-feeds/faros_feed.ts
destinations/airbyte-faros-destination/src/destination.ts

FAI-12109 - Fix faros-feed converter behavior for model resets

---

sources/github-source/resources/spec.json

Add missing parameters to spec
> Fix [#1]() 

Add bucket parameters to spec

---

sources/github-source/src/org-repo-filter.ts
sources/github-source/test/__snapshots__/org-repo-filter.test.ts.snap
sources/github-source/test/org-repo-filter.test.ts
sources/jira-source/test/__snapshots__/project-board-filter.test.ts.snap
sources/jira-source/test/project-board-filter.test.ts

GitHub Connector: Pull all orgs on empty list

---

sources/github-source/README.md
sources/github-source/resources/spec.json
sources/github-source/src/github.ts
sources/github-source/src/index.ts
sources/github-source/src/org-repo-filter.ts
sources/github-source/src/streams/faros_commits.ts

Added permissions required for each GitHub stream

FAI-12391 | Added permissions required for each GitHub stream

---

sources/github-source/resources/schemas/farosPullRequestComments.json
sources/github-source/src/streams/faros_pull_request_comments.ts

GitHub source fix discover

---

faros-airbyte-cdk/src/testing-tools.ts
sources/github-source/test/index.test.ts
sources/jira-source/test/index.test.ts

Move source JSON schema test to common testing tools and add it to GitHub source
> Fix [#1]() 

Add GitHub schema test and move to common

---

faros-airbyte-common/resources/github/queries/labels-fragment.gql
faros-airbyte-common/resources/github/queries/pull-requests-query.gql
faros-airbyte-common/src/github/generated/index.ts
faros-airbyte-common/src/github/queries.ts
faros-airbyte-common/src/github/types.ts
faros-airbyte-common/test/github/queries.test.ts
sources/github-source/src/github.ts

Handle nested pagination for PR labels

FAI-11596 | Handle nested pagination for PR labels

---

sources/github-source/src/github.ts

Fix GitHub build after adding page_size param

FAI-12397 | Fix GitHub build after adding page_size param

---

sources/github-source/resources/spec.json
sources/github-source/src/github.ts
sources/github-source/src/octokit.ts
sources/github-source/src/types.ts

- Avoid fatal error on copilot APIs for 400s
- Removed previews param support (deprecated since 2020)

FAI-11600 | Avoid fatal error on copilot APIs for 400s

---

sources/bitbucket-server-source/src/bitbucket-server/project-repo-filter.ts
sources/bitbucket-server-source/test/project-repo-filter.test.ts

FAI-12447 - Pull all bitbucket-server projects and repos if none are explicitly specified

---

destinations/airbyte-faros-destination/src/converters/github/faros_copilot_seats.ts
destinations/airbyte-faros-destination/test/converters/__snapshots__/faros_github.test.ts.snap

Fix copilot UserToolUsage converted records

FAI-11600 | Fix copilot UserToolUsage converted records

---

destinations/airbyte-faros-destination/src/converters/github/common.ts
destinations/airbyte-faros-destination/src/converters/github/faros_commits.ts
destinations/airbyte-faros-destination/src/converters/github/faros_pull_requests.ts
destinations/airbyte-faros-destination/test/converters/__snapshots__/faros_github.test.ts.snap
sources/github-source/src/org-repo-filter.ts
sources/github-source/src/streams/common.ts
sources/github-source/src/streams/faros_commits.ts

Fixed PR mergeCommit on converter

FAI-12482 | Fixed PR mergeCommit and user emails filter

---

package-lock.json
sources/docker-source/package.json

Fix npm i 404 for @snyk/correlation@^5.6.0

---

sources/github-source/src/github.ts

Fix cases where timeout wrapper isn't properly passed
> Fix [#1]() 

Fix cases where timeout wrapper isn't properly passed

---

sources/sheets-source/src/sheets-reader.ts

Fix google sheet source total rows check
> Fix [#1]() 

FAI-12259 | Fix google sheet source total rows check

---

destinations/airbyte-faros-destination/src/converters/asana/tasks.ts

Dedup projects

---

sources/bitbucket-source/resources/spec.json
sources/bitbucket-source/src/bitbucket.ts
sources/bitbucket-source/src/types.ts
sources/bitbucket-source/test/__snapshots__/index.test.ts.snap
sources/bitbucket-source/test/index.test.ts
sources/bitbucket-source/test/resources/config.json
sources/bitbucket-source/test/resources/repositories/config-bucketing.json
sources/bitbucket-source/test/utils.ts
sources/bitbucket-source/test/workspace-repo-filter.test.ts

FAI-9392: Add bucketing support for BitBucket source

---

sources/bitbucket-source/resources/spec.json
sources/bitbucket-source/src/bitbucket.ts
sources/bitbucket-source/src/types.ts
sources/bitbucket-source/test/index.test.ts
sources/bitbucket-source/test/utils.ts
sources/bitbucket-source/test/workspace-repo-filter.test.ts

FAI-9391:  Expose Bitbucket concurrency limit configuration

---

sources/bitbucket-source/src/bitbucket.ts

FAI-9387: Nit on org repo error logging

---

destinations/airbyte-faros-destination/src/converters/pagerduty/services.ts
destinations/airbyte-faros-destination/test/converters/__snapshots__/pagerduty.test.ts.snap

Delete app association before writing new one to avoid violating uniqueness constraint

---

destinations/airbyte-faros-destination/src/converters/pagerduty/services.ts

Handle multiple associations more robustly

---

destinations/airbyte-faros-destination/src/converters/bitbucket/common.ts
destinations/airbyte-faros-destination/src/converters/bitbucket/pull_requests_with_activities.ts
destinations/airbyte-faros-destination/test/converters/__snapshots__/bitbucket.test.ts.snap

FAI-12278: Fix bitbucket pr activities converter to write all comments

---

destinations/airbyte-faros-destination/src/common/types.ts
destinations/airbyte-faros-destination/src/destination.ts
destinations/airbyte-faros-destination/src/sync.ts
faros-airbyte-cdk/src/protocol.ts
faros-airbyte-cdk/src/sources/source-base.ts

todo: make sure local airbyte run also pushing the version.

[FAI-12637] Write source and destination connector version to Poseidon

---

destinations/airbyte-faros-destination/package.json
package-lock.json

Override protobufjs to ^7.2.6
> Fix [#1]() 

FAI-12901 | Override protobufjs to ^7.2.6

---

destinations/airbyte-faros-destination/package.json
package-lock.json

Removed useless override on destination
> Fix [#1]() 

FAI-12901 | Removed useless override on destination

---

sources/jira-source/resources/spec.json
sources/jira-source/src/client.ts
sources/jira-source/src/jira.ts
sources/jira-source/src/retry.ts
sources/jira-source/test/client.test.ts

Details here: https://confluence.atlassian.com/adminjiraserver0904/adjusting-your-code-for-rate-limiting-1188768983.html

FAI-12831: Handle intermittent 4xx errors on Jira Server

---

package-lock.json

Pick change: https://github.com/faros-ai/airbyte-connectors/pull/1687

FAI-13194: Chale/vuln update

---

sources/jira-source/resources/queries/faros-tms-task-board-options.gql
sources/jira-source/resources/spec.json
sources/jira-source/src/index.ts
sources/jira-source/src/jira.ts
sources/jira-source/src/project-board-filter.ts
sources/jira-source/src/streams/common.ts
sources/jira-source/src/streams/faros_sprint_reports.ts
sources/jira-source/src/streams/faros_team_memberships.ts
sources/jira-source/test/__snapshots__/index.test.ts.snap
sources/jira-source/test/__snapshots__/project-board-filter.test.ts.snap
sources/jira-source/test/index.test.ts
sources/jira-source/test/project-board-filter.test.ts
sources/jira-source/test/utils/test-utils.ts

Added boolean parameter and logic to use Faros Graph for Jira boards selection (inclusions / exclusions)

FAI-13080 | FarosGraph query mode for Jira boards

---

destinations/airbyte-faros-destination/src/converters/testrails/cases.ts
sources/testrails-source/resources/schemas/case.json
sources/testrails-source/src/testrails/models.ts
sources/testrails-source/src/testrails/testrails-models.ts

Added `custom_automation_type` and `custom_update_automation` fields and populated into Case tags.
https://faros-ai.atlassian.net/browse/FAI-13273

FAI-13273: Add custom fields and populate tags field for TestRail

---

faros-airbyte-common/resources/github/queries/pull-request-review-requests-query.gql
faros-airbyte-common/resources/github/queries/pull-request-reviews-query.gql
faros-airbyte-common/src/github/generated/index.ts
sources/github-source/src/github.ts

Fixed gql variable names for PR reviews and review requests
https://github.com/faros-ai/airbyte-connectors/blob/89e3b891b36af9498283919f757d03bdb585b9b2/sources/github-source/src/github.ts#L496
https://github.com/faros-ai/airbyte-connectors/blob/89e3b891b36af9498283919f757d03bdb585b9b2/sources/github-source/src/github.ts#L616
> Fix [#1]() 

FAI-13315 | Fixed gql variable names for PR reviews and review requests

---

destinations/airbyte-faros-destination/src/converters/converter.ts
destinations/airbyte-faros-destination/src/destination.ts
faros-airbyte-cdk/src/protocol.ts
faros-airbyte-cdk/src/sources/source-runner.ts
faros-airbyte-cdk/src/sources/source.ts
sources/jira-source/src/index.ts

Dynamically disable model resets for jira source

FAI-12648: Task board relationship hotspot

---

sources/servicenow-source/resources/spec.json
sources/servicenow-source/src/servicenow/models.ts
sources/servicenow-source/src/servicenow/servicenow.ts

I think we are looking at the wrong field for business service resolution.

FAI-13429 - Fix ServiceNow business service resolution

---

destinations/airbyte-faros-destination/src/converters/github/faros_repositories.ts
faros-airbyte-common/src/common/index.ts
sources/github-source/src/org-repo-filter.ts
sources/github-source/test/org-repo-filter.test.ts

Fix issue on inclusion/exclusion lists with uppercase orgs

FAI-13204 | Fix issue on inclusion/exclusion lists with uppercase orgs

---

sources/github-source/resources/spec.json
sources/github-source/src/github.ts
sources/github-source/src/streams/faros_copilot_seats.ts
sources/github-source/src/types.ts
sources/github-source/test/__snapshots__/index.test.ts.snap
sources/github-source/test/index.test.ts

Add toggle setting for copilot licenses fix on team assignments (default true), so that it can be disabled.

FAI-13447 | Add toggle setting for copilot licenses fix on team assignments (default true)

---

sources/zephyr-source/resources/spec.json
sources/zephyr-source/src/types.ts
sources/zephyr-source/src/zephyr.ts

- Fix Zephyr Spec to meet Airbyte spec for use of [oneOf](https://docs.airbyte.com/connector-development/connector-specification-reference/#using-oneof)

Fix Zephyr spec to meet Airbyte Spec

---

package-lock.json
sources/zephyr-source/resources/spec.json

Add titles to Zephyr Spec
#1734

Add titles to Zephyr Spec for authentication methods

---

sources/zephyr-source/src/streams/common.ts
sources/zephyr-source/src/zephyr.ts

- handle empty list for cycles and project versions

Fix nullish coalesce for airbyte ui empty lists

---

destinations/airbyte-faros-destination/src/converters/github/faros_issues.ts
destinations/airbyte-faros-destination/src/converters/github/faros_pull_requests.ts
destinations/airbyte-faros-destination/test/converters/__snapshots__/faros_github.test.ts.snap
sources/github-source/src/streams/common.ts

Write labels on PRs/Issues streams and remove Labels stream from standard mode
> Fix [#1]() 

FAI-13434 | Write labels on PRs/Issues streams and remove Labels stream from standard mode

---

destinations/airbyte-faros-destination/src/converters/github/faros_dependabot_alerts.ts

Fix dependabot stream converter reading null error
> Fix [#1]() 

FAI-13471 | Fix dependabot stream converter reading null error

---

sources/github-source/src/github.ts

Find app installation using lower-cased org login
> Fix [#1]() 

Find app installation using lower-cased org login

---

faros-airbyte-cdk/src/testing-tools.ts
sources/bitbucket-source/resources/spec.json
sources/bitbucket-source/src/index.ts
sources/bitbucket-source/src/types.ts
sources/bitbucket-source/test/index.test.ts
sources/github-source/resources/spec.json
sources/github-source/src/index.ts
sources/github-source/src/types.ts
sources/github-source/test/index.test.ts
sources/jira-source/resources/spec.json
sources/jira-source/src/index.ts
sources/jira-source/src/jira.ts
sources/jira-source/test/index.test.ts

Added param to filter selected custom streams within source configs (just for Bitbucket / GitHub / Jira where we support run_mode)
> Fix [#1]() 

FAI-13589 | Filter selected custom streams within source

---

faros-airbyte-common/src/common/index.ts
sources/jira-source/src/issue_transformer.ts
sources/jira-source/src/jira.ts
sources/jira-source/test/__snapshots__/index.test.ts.snap
sources/jira-source/test/utils/test-utils.ts

- Jira normalized status name to handle lowercases or spaces

FAI-13709: Normalized Jira workflow status names

---

destinations/airbyte-faros-destination/src/destination.ts
faros-airbyte-cdk/src/sources/source-base.ts

FAI-13859 - Skip resetting models for streams with non-fatal errors

---

destinations/airbyte-faros-destination/src/converters/common/geo.ts
destinations/airbyte-faros-destination/test/converters/__snapshots__/azureactivedirectory.test.ts.snap
destinations/airbyte-faros-destination/test/converters/__snapshots__/geo.test.ts.snap
destinations/airbyte-faros-destination/test/converters/__snapshots__/googlecalendar.test.ts.snap
destinations/airbyte-faros-destination/test/converters/__snapshots__/workday.test.ts.snap
destinations/airbyte-faros-destination/test/converters/geo.test.ts

- Fix nulls for address and co-ordinates
- Validate geo_Coordinates values are numbers

FAI-13823: Better handling for geo locations and tests

---

sources/azureactivedirectory-source/src/index.ts
sources/azureactivedirectory-source/test/__snapshots__/index.test.ts.snap
sources/azureactivedirectory-source/test/index.test.ts

FAI-13924: Fix stream filtering

---

sources/github-source/src/octokit.ts

Updated octokit logger to log on debug only
> Fix [#1]() 

Updated octokit logger to log on debug only

---

destinations/airbyte-faros-destination/src/converters/azurepipeline/builds.ts
sources/azurepipeline-source/resources/spec.json
sources/azurepipeline-source/src/azurepipeline.ts
sources/azurepipeline-source/src/index.ts
sources/azurepipeline-source/src/streams/builds.ts
sources/azurepipeline-source/src/streams/pipelines.ts
sources/azurepipeline-source/src/streams/releases.ts

Add support to discover all pipelines on Azure Pipelines
todo: move duplicated code to Azure common utility

Add support to discover all pipelines on Azure Pipelines

---

sources/azure-workitems-source/package.json
sources/azure-workitems-source/src/azure-workitems.ts

- Use faros-js-client axios
- Add limit to `wit/wiql` fetch
- Change checkConnection to simpler method

Azure Workitems Fixes

---

destinations/airbyte-faros-destination/src/converters/azure-repos/commits.ts
destinations/airbyte-faros-destination/src/converters/azure-repos/pull_requests.ts
destinations/airbyte-faros-destination/src/converters/azure-repos/users.ts

Lowercase azure usernames and add email

---

package-lock.json
package.json
sources/xray-source/package.json
sources/zephyr-source/package.json

https://github.com/open-telemetry/opentelemetry-js/issues/3925
> Fix [#1]() 

Try to fix build

---

destinations/airbyte-faros-destination/src/converters/azure-repos/common.ts
destinations/airbyte-faros-destination/src/converters/azure-repos/models.ts
destinations/airbyte-faros-destination/src/converters/azure-repos/pull_requests.ts

Azure Repos: populate vcs_PullRequestReview.submittedAt and fix PR state

---

destinations/airbyte-faros-destination/src/converters/azure-repos/pull_requests.ts

FAI-14237 - Fix pull request author reference

---

sources/azure-repos-source/src/azure-repos.ts

FAI-14237 - Azure Repos: continue syncing if no branches or tags found for a repo

---

destinations/airbyte-faros-destination/src/converters/azure-workitems/iterations.ts
destinations/airbyte-faros-destination/src/converters/azure-workitems/models.ts
destinations/airbyte-faros-destination/src/converters/azure-workitems/workitems.ts
sources/azure-workitems-source/resources/spec.json
sources/azure-workitems-source/src/azure-workitems.ts
sources/azure-workitems-source/src/models.ts
sources/azure-workitems-source/test/index.test.ts

- Add changelogs for assignees and states
- Add state mapping
- Add type mapping
- More fixes for tms_Task mappings

FAI-14158: Azure WorkItems Hardening

---

destinations/airbyte-faros-destination/src/converters/azurepipeline/builds.ts
destinations/airbyte-faros-destination/test/converters/__snapshots__/azurepipeline.test.ts.snap
destinations/airbyte-faros-destination/test/converters/azurepipeline.test.ts
destinations/airbyte-faros-destination/test/converters/utils.ts

- Azure pipelines - write build artifacts
- added records snapshot on destination
> Fix [#1]() 

FAI-14157 | Azure Pipelines - Write build artifacts

---

sources/azurepipeline-source/src/azurepipeline.ts
sources/azurepipeline-source/src/streams/builds.ts
sources/azurepipeline-source/src/streams/releases.ts
sources/azurepipeline-source/test/index.test.ts

Fix Azure Pipelines - Support individual state per slice

Fix Azure Pipelines - Support individual state per slice

---

destinations/airbyte-faros-destination/src/converters/azure-workitems/models.ts
destinations/airbyte-faros-destination/src/converters/azure-workitems/workitems.ts
sources/azure-workitems-source/resources/spec.json
sources/azure-workitems-source/src/azure-workitems.ts
sources/azure-workitems-source/src/index.ts
sources/azure-workitems-source/src/models.ts
sources/azure-workitems-source/src/streams/workitems.ts
sources/azure-workitems-source/test/index.test.ts

- Azure Work Items support additional fields

FAI-14158: Azure Work Items support additional fields

---

.github/workflows/ci.yml
scripts/source-acceptance-test.sh

Fix source acceptance test script + Add Caching for Turbo build

---

destinations/airbyte-faros-destination/src/converters/azure-workitems/workitems.ts
destinations/airbyte-faros-destination/test/converters/__snapshots__/azure-workitems.test.ts.snap

- Fix sprint uid for sprintboard relationship

FAI-14158: Azure-workitems fix sprint uid 

---

sources/github-source/src/github.ts

Handle PR files unavailable error
> Fix [#1]() 

Handle PR files unavailable error

---

sources/jira-source/resources/spec.json
sources/jira-source/src/index.ts
sources/jira-source/src/jira.ts

FAI-14352 Add round robin support to jira

---

sources/vanta-source/src/streams/vulnerabilities.ts
sources/vanta-source/src/streams/vulnerability_remediations.ts
sources/vanta-source/src/vanta.ts

FAI-12709: Fix Vanta streams cutoff logic and retries

---

destinations/airbyte-faros-destination/src/destination.ts

The backfill check should take more precedence when determining whether to reset data

---

sources/vanta-source/src/vanta.ts

> https://developer.vanta.com/reference/listvulnerabilityremediations#:~:text=by%20remediation%20status.-,remediatedAfterDate,-date%2Dtime 🤦🏽‍♂️
> Fix [#1]() 

Vanta: Fix remediated after param name

---

sources/tromzo-source/src/streams/findings.ts

Fix checking for new cutoff
> Fix [#1]() 

FAI-13813: Bug fix state for comparing state

---

sources/github-source/src/github.ts
sources/github-source/src/index.ts
sources/github-source/src/org-repo-filter.ts
sources/github-source/src/streams/common.ts
sources/github-source/test/__snapshots__/index.test.ts.snap
sources/github-source/test/__snapshots__/org-repo-filter.test.ts.snap
sources/github-source/test/index.test.ts
sources/github-source/test/org-repo-filter.test.ts

FAI-14374 Fail check connection when there are no orgs to fetch

---

package-lock.json
sources/okta-source/package.json
sources/okta-source/resources/spec.json
sources/okta-source/src/okta.ts
sources/okta-source/test/index.test.ts

FAI-14387 Add timeout and retries to Okta

---

destinations/airbyte-faros-destination/src/converters/okta/users.ts

Fixes `Error processing input: cannot upsert null or undefined uid for model org_Department with keys {"uid":null}`
> Fix [#1]() 

FAI-14387 Fix converter

---

destinations/airbyte-faros-destination/src/converters/okta/users.ts

FAI-14387 Fix null uid in converter

---

faros-airbyte-cdk/src/protocol.ts
faros-airbyte-cdk/test/protocol.test.ts

FAI-14421 - Remove newlines on airbyte logs so that they are each log is treated as a single message

---

destinations/airbyte-faros-destination/src/destination.ts
faros-airbyte-cdk/src/index.ts
faros-airbyte-cdk/src/sync-message-tables.ts

FAI-13888 - Start creating sync message table and add warning when no records emitted for stream

---

sources/github-source/src/octokit.ts

Sometimes GitHub graphql requests returns 200 but with no data after server timeout (10 secs). Most of the times the status returned in this case is 502 or 504 which is handled properly by retries. But when the returned status is 200 the logic continues to run as if the response data is there causing read null / undefined errors.
This change hooks into the request to detect this case and simulate a retryable error.
Before https://github.com/faros-ai/airbyte-connectors/pull/1862 we didn't notice this because the resulting errors were wrapped in a try / catch making retries of every possible error..
> Fix [#1]() 

FAI-14530 | Handle GitHub gql requests returning no data after server timeouts

---

destinations/airbyte-faros-destination/src/destination.ts

FAI-13943 - Log warnings at end of sync

---

destinations/airbyte-faros-destination/src/converters/github/faros_pull_requests.ts
destinations/airbyte-faros-destination/test/converters/__snapshots__/faros_github.test.ts.snap

GitHub - populate source/target branch names on pull request
> Fix [#1]() 

FAI-14460 | GitHub - populate source/target branch names on pull request

---

sources/example-source/test_files/spec.json

Fix example-source spec for acceptance test

---

package-lock.json
sources/sheets-source/package.json

Fix CVE-2023-30533

---

faros-airbyte-common/package.json
faros-airbyte-common/src/wolken/index.ts
faros-airbyte-common/src/wolken/types.ts
package-lock.json
sources/wolken-source/bin/main
sources/wolken-source/package.json
sources/wolken-source/resources/schemas/users.json
sources/wolken-source/resources/spec.json
sources/wolken-source/src/index.ts
sources/wolken-source/src/streams/users.ts
sources/wolken-source/src/tsconfig.json
sources/wolken-source/src/wolken.ts
sources/wolken-source/test/index.test.ts
sources/wolken-source/test/tsconfig.json

Wolken source scaffolding
> Fix [#1]() 

FAI-13875 wolken source initial setup

---

faros-airbyte-cdk/package.json
package-lock.json

Add faros-js-client dep to faros-airbyte-cdk

---

destinations/airbyte-faros-destination/src/converters/wolken/users.ts
destinations/airbyte-faros-destination/test/converters/__snapshots__/wolken.test.ts.snap
destinations/airbyte-faros-destination/test/converters/wolken.test.ts
destinations/airbyte-faros-destination/test/resources/wolken/catalog.json
destinations/airbyte-faros-destination/test/resources/wolken/users.log

FAI-13875 Wolken - users converter

---

faros-airbyte-common/src/github/types.ts
sources/github-source/resources/schemas/farosEnterpriseTeamMemberships.json
sources/github-source/resources/schemas/farosSamlSsoUsers.json
sources/github-source/resources/schemas/farosTags.json
sources/github-source/resources/schemas/farosTeamMemberships.json
sources/github-source/src/github.ts
sources/github-source/src/streams/faros_enterprise_team_memberships.ts
sources/github-source/src/streams/faros_saml_sso_users.ts
sources/github-source/src/streams/faros_tags.ts
sources/github-source/src/streams/faros_team_memberships.ts
sources/github-source/test/__snapshots__/index.test.ts.snap

Older version of airbyte (`0.56.0`) is failing the discover schema when a stream primary key contains nested fields. See exception below and note that the fields flagged as missing are actually present in the stream schema.
`Caused by: io.temporal.failure.ApplicationFailure: 
message='Source defined primary key validation failed for stream: faros_enterprise_team_memberships. 
Error: key: 'login' of path: '[user, login]' not found in schema: 
{
"enterprise": {"type": "string"},
"team": {"type": "string"},
"user": {
"type": "object",
"properties": {
"login": {"type": "string"},
"name": {"type": "string"},
"email": {"type": "string"},
"type": {"type": "string"},
"html_url": {"type": "string"}
}
}
},
Source defined primary key validation failed for stream: faros_saml_sso_users. 
Error: key: …

Work around nested field in primary key validation failures for old versions of airbyte

---

faros-airbyte-common/src/wolken/types.ts
sources/wolken-source/resources/schemas/configuration_items.json
sources/wolken-source/resources/spec.json
sources/wolken-source/src/index.ts
sources/wolken-source/src/streams/configuration_items.ts
sources/wolken-source/src/wolken.ts

FAI-13875 Wolken - configuration_items stream

---

sources/github-source/src/github.ts

- Catch authentication error using makeOctokit early before creating GitHub instance if authentication details are missing to surface error
Before when authentication.type is not defined
```
Encountered an error while reading stream xxx: Cannot read properties of undefined (reading 'type')
```
After
```
"Encountered an error while reading stream xxxx: Invalid authentication configuration: type should be \"token\" or \"app\""
```

GitHub source use common makeOctokit to surface authentication error

---

sources/example-source/src/config.ts
sources/example-source/src/index.ts
sources/example-source/src/streams/builds.ts

Update example-source to show config usage

---

sources/datadog-source/resources/spec.json
sources/datadog-source/src/datadog.ts
sources/datadog-source/src/index.ts
sources/datadog-source/test/__snapshots__/index.test.ts.snap
sources/datadog-source/test/index.test.ts

- Allow filtering of streams in Datadog since they need different permissions

FAI-15521: Datadog support filtering streams

---

destinations/airbyte-faros-destination/package.json
package-lock.json

Bump faros-js-client => v0.6.4

---

destinations/airbyte-faros-destination/package.json
faros-airbyte-cdk/package.json
faros-airbyte-common/package.json
package-lock.json
package.json
sources/asana-source/package.json
sources/circleci-source/package.json
sources/faros-graphdoctor-source/package.json
sources/faros-graphql-source/package.json
sources/github-source/package.json
sources/jira-source/package.json
sources/okta-source/package.json
sources/trello-source/package.json
sources/tromzo-source/package.json
sources/vanta-source/package.json
sources/wolken-source/package.json
sources/xray-source/package.json
sources/zephyr-source/package.json

FAI-15591 faros-js-client => 0.6.5

---

destinations/airbyte-faros-destination/src/converters/github/faros_pull_requests.ts

GitHub PR source/target branch name fix
> Fix [#1]() 

GitHub PR source/target branch name fix

---

destinations/airbyte-faros-destination/src/converters/azure-repos/common.ts
destinations/airbyte-faros-destination/src/converters/azure-repos/pull_requests.ts
destinations/airbyte-faros-destination/src/converters/azure-repos/repositories.ts
destinations/airbyte-faros-destination/src/converters/common/vcs.ts
destinations/airbyte-faros-destination/test/converters/__snapshots__/azure-repos.test.ts.snap
faros-airbyte-common/src/azure-devops/types.ts
sources/azure-repos-source/resources/spec.json
sources/azure-repos-source/src/azure-repos.ts
sources/azure-repos-source/src/index.ts
sources/azure-repos-source/src/models.ts
sources/azure-repos-source/src/streams/commits.ts
sources/azure-repos-source/src/streams/pullrequests.ts
sources/azure-repos-source/src/streams/repositories.ts
sources/azure-repos-source/src/streams/users.ts
sources/azure-repos-source/test/__snapshots__/index.test.ts.snap
sources/azure-repos-source/test/index.test.ts
sources/azure-repos-source/test_files/pullrequests.json

- Write out branches for Azure Repos Pull Requests
- Support repo list for Azure Repos
- Allow fetching commits from multiple branches

FAI-15701: Write out branches for Azure Repos Pull Requests

---

destinations/airbyte-faros-destination/src/converters/azureactivedirectory/users.ts
destinations/airbyte-faros-destination/test/converters/__snapshots__/azureactivedirectory.test.ts.snap

FAI-15868 Do not write null email

---

sources/github-source/resources/spec.json
sources/github-source/src/github.ts
sources/github-source/src/types.ts

Copilot metrics support fixed teams config
> Fix [#1]() 

FAI-15474 | Copilot metrics support fixed teams config

---

destinations/airbyte-faros-destination/src/destination-logger.ts

Affects local destination executions -- does not affect containerized executions.
> Fix [#1]() 

FAI-15986 - Use unique dir for storing local logs

---

sources/azure-workitems-source/src/azure-workitems.ts
sources/azure-workitems-source/src/streams/workitems.ts
sources/azure-workitems-source/test/index.test.ts

- Make Azure workitems stream run incrementally

FAI-14373: Make Azure workitems stream run incrementally

---

sources/github-source/src/index.ts

Fix GitHub checkConnection for enterprise mode

Fix GitHub checkConnection for enterprise mode

---

package-lock.json
sources/github-source/package.json
sources/github-source/resources/spec.json
sources/github-source/src/octokit.ts
sources/github-source/src/types.ts

Add proxy url config for GitHub
> Fix [#1]() 

FAI-16078 | Add proxy url config for GitHub

---

Dockerfile

Follow up to #1990 
> Fix [#1]() 

Do not remove mockttp

---

destinations/airbyte-faros-destination/src/index.ts

Actually export all testing fns

---

sources/bitbucket-server-source/resources/spec.json
sources/bitbucket-server-source/src/bitbucket-server/index.ts

FAI-16183 - Retry on bitbucket-server connectivity errors

---

sources/jira-source/src/retry.ts

FAI-16183 - Retry jira calls on ECONNREFUSED error

---

sources/github-source/src/github.ts

Test sync with classic:
Test sync with fine-grained:
> Fix [#1]() 

FAI-15569 GH -- Log token type

---

sources/azure-repos-source/resources/spec.json
sources/azure-workitems-source/resources/spec.json
sources/azurepipeline-source/resources/spec.json

Fix azure spec typos

---

destinations/airbyte-faros-destination/src/converters/vanta/vulnerabilities.ts
destinations/airbyte-faros-destination/test/converters/__snapshots__/vanta.test.ts.snap

Store packageIdentifier in 'affectedVersions' list

FAI-16440 | Storing package Identifier

---

destinations/airbyte-faros-destination/src/converters/faros-org-import/teams.ts

Fix infinite loop when team ancestry contains a cycle. Also improve runtime to O(n)

faros-org-import - Fix team cycle check

---

sources/gitlab-source/resources/schemas/farosProjects.json
sources/gitlab-source/resources/spec.json
sources/gitlab-source/src/gitlab.ts
sources/gitlab-source/src/group-filter.ts
sources/gitlab-source/src/index.ts
sources/gitlab-source/src/streams/common.ts
sources/gitlab-source/src/streams/faros_projects.ts
sources/gitlab-source/src/types.ts
sources/gitlab-source/test/__snapshots__/index.test.ts.snap
sources/gitlab-source/test/group-filter.test.ts
sources/gitlab-source/test/index.test.ts
sources/gitlab-source/test/resources/faros_groups/catalog.json
sources/gitlab-source/test/resources/faros_projects/catalog.json

FAI-16744 GitLab projects stream and include/exclude logic for subgroups

---

faros-airbyte-common/src/gitlab/types.ts
sources/gitlab-source/src/gitlab.ts
sources/gitlab-source/src/streams/common.ts

Porting https://github.com/faros-ai/feeds/blob/56f22d3059c78f680fb2d3fce5d1b853ee9d4565/feeds/vcs/gitlab-feed/src/feed.ts#L270

GitLab: Skip empty repos

---

destinations/airbyte-faros-destination/src/converters/cursor/daily_usage.ts
destinations/airbyte-faros-destination/test/converters/__snapshots__/cursor.test.ts.snap

Fix Cursor user tool usage refs

Fix Cursor user tool usage refs

---

destinations/airbyte-faros-destination/src/converters/azurepipeline/common.ts
destinations/airbyte-faros-destination/src/converters/azurepipeline/pipelines.ts
destinations/airbyte-faros-destination/src/converters/azurepipeline/runs.ts

FAI-17202 Fallback to organization from source config

---

sources/github-source/src/github.ts

Handle copilot seats without assignee. This seems to be a new behavior of the API.
> Fix [#1]() 

Handle copilot seats without assignee

---

sources/github-source/src/github.ts

follow-up https://github.com/faros-ai/airbyte-connectors/pull/2136

Handle copilot seats without assignee (enterprise)

---

sources/googledrive-source/resources/spec.json
sources/googledrive-source/src/googledrive.ts
sources/googledrive-source/test/index.test.ts

Handle retries for google drive
> Fix [#1]() 

FAI-17227 | Handle retries for google drive

---

sources/azure-repos-source/src/azure-repos.ts
sources/azure-repos-source/src/streams/common.ts
sources/azure-repos-source/src/streams/pullrequests.ts

Azure Repos fetch PRs for all branches

FAI-17032 | Azure Repos fetch PRs for all branches

---

sources/azure-repos-source/src/azure-repos.ts
sources/azure-workitems-source/src/index.ts
sources/azure-workitems-source/src/streams/common.ts
sources/azure-workitems-source/src/streams/iterations.ts
sources/azure-workitems-source/src/streams/projects.ts
sources/azure-workitems-source/src/streams/users.ts
sources/azure-workitems-source/src/streams/workitems.ts

- Fix additional fields initialization in AzureWorkitemsSource

FAI-17270: Fix additional fields initialize

---

destinations/airbyte-faros-destination/src/converters/github/faros_copilot_usage.ts
destinations/airbyte-faros-destination/test/converters/__snapshots__/faros_github.test.ts.snap

Follow-up PR to https://github.com/faros-ai/airbyte-connectors/pull/2166
Improve deletions performance by benefiting from startedAt index
> Fix [#1]() 

FAI-17300 | Improve assistant metric deletions performance

---

sources/circleci-source/src/circleci/circleci.ts
sources/circleci-source/src/streams/usage.ts

CircleCI usage catch 404s appearing for only some orgs on create (maybe lack of permissions on some of the visible orgs)
> Fix [#1]() 

FAI-16829 | CircleCI usage catch 404s on create

---

destinations/airbyte-faros-destination/src/index.ts

Expose flush for use in custom-destinations

Make flush available in package

---

destinations/airbyte-faros-destination/test/resources/claude/all-streams.json
faros-airbyte-common/src/claude/types.ts
sources/claude-source/resources/schemas/claudeCodeUsageReport.json
sources/claude-source/src/claude.ts
sources/claude-source/src/streams/claude_code_usage_report.ts
sources/claude-source/test/__snapshots__/index.test.ts.snap

Fix claude code usage stream primary key
> Fix [#1]() 

Fix claude code usage stream primary key

---

package-lock.json
package.json

https://github.com/faros-ai/airbyte-connectors/security/dependabot/95

FAI-18081: Axios update
